### ISSUE TITLE
Is Python 3.4 supported?

### ISSUE THREAD

**Issue by ianozsvald** [manahl/arctic#1]
Hey there. I see Python 2.7 in the Requirements, do you know if this works with Python 3.4? 

I only ask because it isn't clear if it isn't supported or just isn't tested. Personally I've been using Python 3.4+Pandas+PyMongo (on Linux+Windows) for almost 2 years with no hiccups.

**Comment by jamesblackburn** [comment]
Hi @ianozsvald, 

Python 3.x is something we absolutely *want* to support, but no work has gone in to checking / ensuring compatibility.  I don't anticipate any issues - other than the minor syntax tweaks needed to make it work.

The priority list is:
 - getting the public continuous integration going
 - getting the egg on pypi
 - getting the docs up

Once we have the build going (for some reason installing the pymongo egg is using >8GB of RAM -> process being killed), we can use tox or similar to get the build running on multiple versions.

Cheers,
James

**Comment by ianozsvald** [comment]
Hey James! Cool, knowing that no blockers are expected is good. Congrats on making this open, maybe this is something that can be talked about at a future pydatalondon meetup...

**Comment by llazzaro** [comment]
I started to make arctic to be compatible with python 3.4 on my fork

**Comment by bmoscon** [comment]
Just to update you @ianozsvald I have arctic working in Python3.4 (at least, I can run the how_to scripts). It will take some more work and testing, and additional test cases, but I'm confident that within a few weeks I can have a pull request open to allow arctic to support 2.6 - 3.4

**Comment by femtotrader** [comment]
+1 we should all work with Python 3 now!!!

**Comment by llazzaro** [comment]
:+1:

**Comment by bmoscon** [comment]
python 3 support here:

https://github.com/manahl/arctic/pull/89


once its merged in (could be a while, its huge) 3.3 will work out of the box. 3.4 will work, but a lot of unit tests will fail because the version of mock we require breaks in 3.4. 3.5 wont work because of a known issue in pandas.

**Comment by bmoscon** [comment]
Python3 support merged in

**Comment by jamesblackburn** [comment]
Woohoo, issue #1 closed - well done @bmoscon
