### ISSUE TITLE
Querying VersionStore on hour/minute

### ISSUE THREAD

**Issue by TheTradingWarrior** [manahl/arctic#107]
Hello,

I understand that one can query data using a date range but could I specify instead a time range? For example getting all data between datetime.time(9,0) and datetime.time(12,0)?

**Comment by richardbounds** [comment]
You can't do that in the query, but you could use http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.between_time.html on the returned data

**Comment by TheTradingWarrior** [comment]
Thanks, no idea I could do that.
