### ISSUE TITLE
Build fails with src/_compress.c:348:10: fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by strimp099** [manahl/arctic#11]
Using OSX 10.9.5 with Anaconda Python 2.7

Installation fails with both `pip` and `setuptools`.

    jasons-mbp:arctic jason$ sudo pip install git+https://github.com/manahl/arctic.git
    Password:
    Collecting git+https://github.com/manahl/arctic.git
      Cloning https://github.com/manahl/arctic.git to /tmp/pip-g3vzNe-build
    Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): lz4 in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): mockextras in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): pandas in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Collecting pymongo>=3.0 (from arctic==1.0.0)
      Downloading pymongo-3.0.3.tar.gz (419kB)
        100% |████████████████████████████████| 421kB 646kB/s 
    Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/anaconda/lib/python2.7/site-packages (from arctic==1.0.0)
    Collecting tzlocal (from arctic==1.0.0)
      Downloading tzlocal-1.2.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): mock>=0.8.0 in /usr/local/anaconda/lib/python2.7/site-packages (from mockextras->arctic==1.0.0)
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /usr/local/anaconda/lib/python2.7/site-packages (from pandas->arctic==1.0.0)
    Installing collected packages: pymongo, tzlocal, arctic
      Running setup.py install for pymongo
      Running setup.py install for tzlocal
      Running setup.py install for arctic
        Complete output from command /usr/local/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-g3vzNe-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TDueqF-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib.macosx-10.5-x86_64-2.7
        creating build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/_compression.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/_util.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/arctic.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/auth.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/decorators.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/exceptions.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/hooks.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/hosts.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        copying arctic/logging.py -> build/lib.macosx-10.5-x86_64-2.7/arctic
        creating build/lib.macosx-10.5-x86_64-2.7/tests
        copying tests/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/tests
        copying tests/conftest.py -> build/lib.macosx-10.5-x86_64-2.7/tests
        copying tests/util.py -> build/lib.macosx-10.5-x86_64-2.7/tests
        running build_ext
        cythoning src/_compress.pyx to src/_compress.c
        warning: src/_compress.pyx:167:38: Use boundscheck(False) for faster access
        warning: src/_compress.pyx:177:19: Use boundscheck(False) for faster access
        warning: src/_compress.pyx:29:5: Cannot profile nogil function.
        warning: src/_compress.pyx:35:5: Cannot profile nogil function.
        warning: View.MemoryView:294:5: Cannot profile nogil function.
        warning: View.MemoryView:772:5: Cannot profile nogil function.
        warning: View.MemoryView:908:5: Cannot profile nogil function.
        warning: View.MemoryView:1070:5: Cannot profile nogil function.
        warning: View.MemoryView:1077:5: Cannot profile nogil function.
        warning: View.MemoryView:1131:5: Cannot profile nogil function.
        warning: View.MemoryView:1138:5: Cannot profile nogil function.
        warning: View.MemoryView:1149:5: Cannot profile nogil function.
        warning: View.MemoryView:1170:5: Cannot profile nogil function.
        warning: View.MemoryView:1230:5: Cannot profile nogil function.
        warning: View.MemoryView:1301:5: Cannot profile nogil function.
        warning: View.MemoryView:1323:5: Cannot profile nogil function.
        warning: View.MemoryView:1358:5: Cannot profile nogil function.
        warning: View.MemoryView:1368:5: Cannot profile nogil function.
        building 'arctic._compress' extension
        creating build/temp.macosx-10.5-x86_64-2.7
        creating build/temp.macosx-10.5-x86_64-2.7/src
        gcc -fno-strict-aliasing -I/usr/local/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/anaconda/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.5-x86_64-2.7/src/_compress.o -fopenmp
        clang: warning: argument unused during compilation: '-fopenmp'
        src/_compress.c:348:10: fatal error: 'omp.h' file not found
        #include "omp.h"
                 ^
        1 error generated.
        error: command 'gcc' failed with exit status 1
        
        ----------------------------------------
    Command "/usr/local/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-g3vzNe-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TDueqF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-g3vzNe-build

**Comment by AdrianTeng** [comment]
Hi,
It seems openmp is not included in OS X's clang compiler (which disguise itself as gcc!).
You could either:
 - install a real gcc using homebrew by following instructions [here](http://stackoverflow.com/questions/28546288/omp-h-not-found-os-x-yosemite-not-using-newest-gcc-version); or 
 - retrieve a copy of `omp.h` and point clang to it, instructions [here](https://github.com/clang-omp/clang/issues/58)
Let us know if this works!
Cheers,
Adrian

**Comment by strimp099** [comment]
Yup got this going, had to install the real GCC. I had another issue where the module directories were not copied into the installation directory so I was getting module not found errors. I had to manually copy over. Do you want me to open a new issue?

**Comment by AdrianTeng** [comment]
Yes please!

**Comment by strimp099** [comment]
The open pull request also fixed this for me.

**Comment by jamesblackburn** [comment]
Re-opened: https://github.com/manahl/arctic/issues/14
