### ISSUE TITLE
unlabeled dataframes and series changed when read back from arctic

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#113]
Here is a test case (add to tests/integration/test_pandas_store)

````
df = DataFrame(data=[1, 2, 3],
                   index=Index(data=[dt(2016, 01, 01),
                                     dt(2016, 01, 02),
                                     dt(2016, 01, 03)],
                               name='date'))
    library.write('test', df)
    ret = library.read('test').data
    assert_frame_equal(ret, df)
````

basically the to/from records functionality will hard code in some colum/series names if none are present. Series get named 'values', and columns become u'0' to u'N'

Series default name is None, and dataframe column names are 0 -> N (integer, not string). Not sure if this is intentional or not, or if its even something to care about (most series and columns in dataframes will be named). 

From the above example here are the values of df.columns and ret.columns, respectively:

````
Int64Index([0], dtype='int64')
Index([u'0'], dtype='object')
````

note 0 goes from int64 to string object.

**Comment by bmoscon** [comment]
@jamesblackburn

**Comment by richardbounds** [comment]
Pretty sure this was intentional, although I can't remember exactly why. At one point I think we stored the column names in the dtype, so it may be something to do with the type checking/promotion code in _ndarry_store. I wonder whether @jjbmatthews remembers?

**Comment by bmoscon** [comment]
@richardbounds we do store the names IF they are there. If you provide a series name or a column name it works perfectly. Its only if they are absent that there is an issue.

**Comment by bmoscon** [comment]
I have done some digging. The dataframe converter maps all the column names through the str function, so any column name that is a non string (i.e. the default column names) will be converted to a string. 

The converter for Series just uses the name 'values' if one is not supplied.

**Comment by bmoscon** [comment]
resolved by logging when we change column/series/index names
