### ISSUE TITLE
Simple example on querying database using column based criteria ?

### ISSUE THREAD

**Issue by ZetaReticulli** [manahl/arctic#116]
I have just come across arctic. I intend to use it to store EOD data. 

Once data has been loaded, are there any examples that show use cases that show how to query the database uses any of the following, as criteria (for example):

1. Select data between two specified timestamps. The `read()` method takes a date range. How does one query data based on timestamps as well?
 
2. Select data where a column (e.g. open, high, low, close, volume etc.) satisfies a given criteria?

**Comment by bmoscon** [comment]
someone else might need to correct me but I believe this is correct:

1. its date range only. you cannot query between say, 10am and 11am.
2. you cannot query by column. if you need column wise access, you might want to store columns as separate symbols and query them separately.

**Comment by ZetaReticulli** [comment]
@bmoscon Thanks for your response. Regarding the second answer you gave, I believe I did not make my self clear.

What I meant was for example:

Assuming I stored OHLCV data in arctic, how would I select data from the database that satisfied the following criteria:

1. trade dates between d1 and d2
2. Volume was greater than V
3. Close price was greater than C

Thanks

**Comment by bmoscon** [comment]
````
df = library.read(symbol, date_range=DateRange(start, stop))
````

and then something like

````
df[ df['volume'] > V & df['close_price'] > C ]
````

**Comment by ZetaReticulli** [comment]
@bmoscon Thanks for the example. It seems the filtering is being done at the dataframe level. I thought the querying could be pushed to mongodb itself - to avoid too many rows being returned - and thus hogging memory.

I'll see if there's another way of doing what it is I want to do.

**Comment by bmoscon** [comment]
@ZetaReticulli that is possible with Mongo, but not with Arctic. The data is compressed, so you cant really filter the data (other than by date range).

**Comment by ZetaReticulli** [comment]
@bmoscon Ok, thanks for clarifying that.

**Comment by jamesblackburn** [comment]
Note EOD data is really small so you should find that it's as fast to read the entire history for a market as it is to read one data point. So give Bryant's example a try.

**Comment by ZetaReticulli** [comment]
@jamesblackburn. Ok, thanks - will set time aside to do some benchmarking etc., later this week
