### ISSUE TITLE
apparent bug in _ndarray_store::write

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#121]
this code:

````
if not dtype:
        dtype = item.dtype
version['dtype'] = str(dtype)
version['shape'] = (-1,) + item.shape[1:]
version['dtype_metadata'] = dict(dtype.metadata or {})
version['type'] = self.TYPE
version['up_to'] = len(item)
version['sha'] = self.checksum(item)

if previous_version:
        if version['dtype'] == str(dtype) \
````

appears incorrect. version['dtype'] will always equal str(dtype) (in the if statement at bottom) since we have just finished setting it above. I believe the intent here was to make sure the current item dtype (i.e. str(dtype)) is equal to the previously written item's dtype. I think this check should be if previous_version['dtype'] == str(dtype).

Do you agree @richardbounds @jamesblackburn ?

**Comment by jamesblackburn** [comment]
Doing some splunking of the code, this bug has been there since the very beginning (July 2013).

I think your analysis is correct. Presumably we would incorrectly do an attempt if a write came in which changed the dtype?

**Comment by bmoscon** [comment]
I dont think we'd actually be able to get in that case because if the dtpyes are different, i assume the checksum of the first N elements of the recarr would be different too. There might be some really weird corner case, but i think this is more of a initial, cheap, check. Much better to check easy things like equal strings than computing the checksum for the whole thing.

I could, of course, be entirely wrong!

**Comment by jamesblackburn** [comment]
Yeah. I guess the usual case is that a write will nearly always preserve the dtype for a given DF, and this takes the hit of the checksum. 

If @richardbounds doesn't object I would opt for simplifying the code unless we can come up with a test case which exhibits the bug.

**Comment by jamesblackburn** [comment]
Clearly as the condition was always `True` it can be safely removed without affecting users :)
