### ISSUE TITLE
C# API

### ISSUE THREAD

**Issue by fouvy** [manahl/arctic#124]
Where can I find C# API of Arctic? I found your had finished C# API on slideshare.
When will C# API be released?

**Comment by mmitkevich** [comment]
Hi. I did some efforts for .net porting of Pandas Version Store, (but without versions support yet) :)

https://github.com/mmitkevich/narctic

Very alfa stage actually.
You could use it while official API is not published :)

**Comment by jamesblackburn** [comment]
Very cool!

**Comment by shashank88** [comment]
Doesn't seem active anymore, can we close this?
