### ISSUE TITLE
"NB treating all values as 'exists' - no longer sparse"

### ISSUE THREAD

**Issue by jrhe** [manahl/arctic#128]
Hi,

I wasn't sure quite where to bring this up so apologies if it is the wrong place.

I am loading tick data from true fx (http://www.truefx.com/?page=downloads) into Arctic, which consists of panadas dataframes containing, bid and offer, indexed on timestamp, keyed on currency pair.

Whilst doing this I get the warning "NB treating all values as 'exists' - no longer sparse" multiple times. 

I get the gist of this message but am unsure of why I'm getting it and what performance implications there may be.

Could you please elaborate on what this means, if I should be concerned, and if this is a sensible way to load top of book tick data?

Cheers,

Jonathan

**Comment by bmoscon** [comment]
This is benign, it means that everything will be stored in Arctic -- if your data is sparse, a whole lot of NaNs will be stored. Its not a big deal because its compressed when written.

**Comment by reasto** [comment]
If you write using lists of dicts instead of dataframes then the missing data is not stored which saves on space and CPU.

**Comment by bmoscon** [comment]
just to be clear, the dataframes are not sparse when written to tickstore. Thats what the warning is about. Dicts can be, dataframes are not. This means if you have a lot of NaNs (missing values), you're going to be writing them all to mongo, thus using more space. If you want sparse data stored sparsely, use dictionaries.
