### ISSUE TITLE
Best practice storing minute bars

### ISSUE THREAD

**Issue by xgdgsc** [manahl/arctic#152]
I tried to store a 5min dataframe (which indexes look like "2016-06-06 13:40:00", "2016-06-06 13:45:00"), But  `library.read('test', date_range=DateRange('20160613', '20160616'))` would return the entire dataframe instead of just those in the range.  The howto only shows daily bars. What is the best practice of using arctic for 1min bars, given the date_range doesn' t support minutes well?

**Comment by xgdgsc** [comment]
And I would like to ask what would be the performance of arctic compared with KairosDB or OpenTSDB?

**Comment by jamesblackburn** [comment]
> library.read('test', date_range=DateRange('20160613', '20160616')) would return the entire dataframe instead of just those in the range

You can put a `datetime.datetime` in for the DateRange start / end, so you should be able to slice at any granularity you like. The string / int constructor is provided for convenience for interactive use.

> And I would like to ask what would be the performance of arctic compared with KairosDB or OpenTSDB 

Arctic is slightly different to OpenTSDB / Kairos.  It's optimised for read and sends batched chunks of data compressed across the network. The result is that it enables the clients to load and process data efficiently, but doesn't support server side processing. In terms of performance it should compare favourably to OepnTSDB / Kairos.
