### ISSUE TITLE
_pandas_ndarray_store.py - _daterange method DateRange Slicing

### ISSUE THREAD

**Issue by canada4663** [manahl/arctic#156]
Hello - 

I'm having an issue slicing date ranges out of pandas data frames using the date_range feature of the read() method.

Getting error: 

            KeyError: numpy.datetime64('2008-01-01T00:00:00.000000')

Looks like its failing in _daterange() method on line:

            mask[start:end] = 1.0

Stack trace takes the error down to pandas.indexes.base get_slice_bound method.

I then used to_pandas_closed_closed() to convert DateRange to a pandas closed/closed range - and then I get 

             AttributeError: 'datetime.date' object has no attribute 'tzinfo' from _assert_no_timezone

Full code below:

         date_range = to_pandas_closed_closed(string_to_daterange('20080101-20101231', as_dates=True), add_tz=False)

         quotes_repo._connect_arctic()
         data = quotes_repo.arctic_lib.read('optionstats', date_range=date_range)

will keep debugging this and share findings, but if others have had trouble with DateRange slicing, let me know.

Ryan

**Comment by bmoscon** [comment]
is this in tickstore or versionstore?

**Comment by bmoscon** [comment]
version store and tickstore require arctic.date.DateRange objects for the date_range argument. Change to that, and it should address your issue.
