### ISSUE TITLE
preserve the NaN

### ISSUE THREAD

**Issue by luli11** [manahl/arctic#157]
when I run the following code 
store.initialize_library('test_lib')
lib = store['test_lib']
lib.write('tmp1', pd.Series(['test', nan]))

and then read back:
lib.read('tmp1')
nan will be converted to 'nan' in the store. of course there is a choice to preserve NaN instead of forcing it to be a string, just wonder if there is a way to turn on/off the option.

**Comment by bmoscon** [comment]
ChunkStore supports what you want to do. Its serializer keeps track of missing values in string columns and will convert them back to np.NaNs

**Comment by bmoscon** [comment]
Also, as an additional note, this problem is only on string columns. Other numeric columns will have their NaNs preserved. Only string columns do not properly support missing values.

**Comment by dimosped** [comment]
Version has this known issue:
```
In [1]: 
   ...: import pandas as pd
   ...: import numpy as np
   ...: from datetime import datetime as dt
   ...: from datetime import timedelta
   ...: 
   ...: import arctic
   ...: 
   ...: dates = [dt(2016, 1, 1) + timedelta(hours=n+1) for n in range(10)]
   ...: strings = ['abc'] *9 + [np.nan]
   ...: 
   ...: mydf = pd.DataFrame({'col_a': dates, 'col_b': strings})
   ...: 
   ...: serializer = arctic.serialization.numpy_records.DataFrameSerializer()
   ...: # records = serializer._to_records(mydf)
   ...: # print(arctic.serialization.numpy_records._to_primitive(mydf['col_b']))
   ...: 
   ...: # The very root cause
   ...: print(np.array(list(mydf['col_b'])))
   ...: 
```
Gives: 
```
['abc' 'abc' 'abc' 'abc' 'abc' 'abc' 'abc' 'abc' 'abc' 'nan']
```
