### ISSUE TITLE
attribute '__dict__' of 'type' objects is not writable

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#17]
Hello,

    $ pip install git+https://github.com/manahl/arctic.git
    Collecting git+https://github.com/manahl/arctic.git
      Cloning https://github.com/manahl/arctic.git to /var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-u36_hcpf-build
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-u36_hcpf-build/setup.py", line 63, in <module>
            m.Extension.__dict__ = m._Extension.__dict__
        AttributeError: attribute '__dict__' of 'type' objects is not writable

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-u36_hcpf-build

I'm using Mac OS X 10.10 with Anaconda (Python 3)

Kind regards

**Comment by jamesblackburn** [comment]
Thanks for the report! 

- Mac support is wanted - we'll build an egg: https://github.com/manahl/arctic/issues/14
- We want to support Python 3, but not yet done: https://github.com/manahl/arctic/issues/1
