### ISSUE TITLE
No module named Cython.Build

### ISSUE THREAD

**Issue by mickeylau** [manahl/arctic#174]
i am using windows and i use putty to connect to a linux host.
when i enter : git+https://github.com/manahl/arctic.git
my result is as follows:
```
Cloning https://github.com/manahl/arctic.git to /tmp/pip-B5xD0j-build
  Running setup.py (path:/tmp/pip-B5xD0j-build/setup.py) egg_info for package from git+https://github.com/manahl/arctic.git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-B5xD0j-build/setup.py", line 24, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-B5xD0j-build/setup.py", line 24, in <module>

    from Cython.Build import cythonize

ImportError: No module named Cython.Build

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-B5xD0j-build
Storing debug log for failure in /home/mickey/.pip/pip.log

```
how can i fix it?
thx for any help in advance

**Comment by bmoscon** [comment]
Have you installed Cython first?

**Comment by bmoscon** [comment]
never heard anything back, but literally just install Cython, something like


`pip install cython`

**Comment by JoshZastrow** [comment]
Hi, similar problem but I am using Cygwin, and I do have Cygwin installed as it is included in the Anaconda package. I'm currently using Python 3 if that matters


joshua@LAPTOP-C6H0BQOF /cygdrive/c/users/joshu/documents/cs231n/assignment2/cs231n
$ where python
C:\cygwin64\bin\python
C:\Users\joshu\Anaconda3\python.exe

joshua@LAPTOP-C6H0BQOF /cygdrive/c/users/joshu/documents/cs231n/assignment2/cs231n
$

joshua@LAPTOP-C6H0BQOF /cygdrive/c/users/joshu/documents/cs231n/assignment2/cs231n
$ python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build


here is the code to the setup.py file:

from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
import numpy

extensions = [
  Extension('im2col_cython', ['im2col_cython.pyx'],
            include_dirs = [numpy.get_include()]
  ),
]

setup(
    ext_modules = cythonize(extensions),
)


I read somewhere that I need a compiler for cython, so I downloaded and installed MinGW in my C:/. Not sure if that covers everything, but still get the error.

I'm following along these setup procedures:

http://cs231n.github.io/assignments2016/assignment2/

**Comment by bmoscon** [comment]
FYI setup.py has been updated to no longer require that cython is pre-installed
