### ISSUE TITLE
Zipline datasource with Arctic datastore

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#19]
Hello,

Zipline could be an interesting example for Arctic.
here is some instructions to build a datasource for zipline
https://github.com/quantopian/zipline/wiki/How-To-code-a-data-source

Kind regards

PS: on zipline side
https://github.com/quantopian/zipline/issues/660

**Comment by eeaston** [comment]
Thanks for the heads up, we'll have a look!

**Comment by leandroloi** [comment]
Hi,
 Any news about this issue?

Thanks

**Comment by bmoscon** [comment]
Note that the original request links to a wiki page that appears to be out of date. The Zipline documentation spells out a completely different way to support data stores and the method mentioned in the linked wiki page doesnt appear to exist anymore. see http://www.zipline.io/bundles.html#writing-a-new-bundle

**Comment by leandroloi** [comment]
Thanks,

   I got it already. 

Cheers

**Comment by shashank88** [comment]
Hey @femtotrader, @leandroloi this seems pretty old, just wanted check if it's still something you guys wanted or should I close this if not?
