### ISSUE TITLE
Is ChunkStore production-ready?

### ISSUE THREAD

**Issue by mckelvin** [manahl/arctic#192]
Hi guys, thank so much for developing and maintaining such a great datastore.

I see that, unlike `TICK_STORE` or `VERSION_STORE`, the constant variable `CHUNK_STORE` doesn't exist in `arctic/__init__.py`. Also, there're some heavy develop work in `ChunkStore` (like #182). My question is: **Is `ChunkStore` production-ready ? Is the API stable or maybe it's likely to be changed someday?**

My use case of arctic is storing tick data, where the data come one tick after one tick:

```python
# pseudo code

def event_driven_engine_on_tick_event(symbol, one_tick_dict):
    arctic_tick_library.write(symbol, [one_tick_dict])  # one item one chunk

```

But the `TickStore` is designed for large continuously ticking data, the disk usage of mongodb increases greatly in this way. So I have to start cron, which compress these ticks periodically (align by day). 

```python
# pseudo code

def compress_yesterday(symbol):
    date_range = DateRange(yesterday_0000, yesterday_2359)
    ticks_df = arctic_tick_library.read(symbol, date_range)
    arctic_tick_library.delete(symbol, date_range)
    arctic_tick_library.write(symbol, ticks_df)  # rewrite ~10000 items one chunk
```

The problem is solved but bring some other problems. For example, a user may read while the compressing process is deleting the tick library.

After read part code of `ChunkStore`, I guess a `ChunkStore` with `DateChunker(chunk_size='D')` is more suitable in this use case. I'm going to use ChunkStore as a tick buffer. At the end of a day, ticks in the specific day will be migrated from ChunkStore to a TickStore. I'm not sure the migration process is essential. **Is it suitable to store all the ticks in ChunkStore ?**

And I'd appreciate it if some use cases of these different stores(especially the breakdowns between them) are added in [the wiki](https://github.com/manahl/arctic/wiki).

Thanks again.

**Comment by bmoscon** [comment]
It should be fine to store everything in the ChunkStore, thats what its designed for, things that need to be accessed frequently based on some marker/id (in the current case, date). Its really good for that. The API might change, but from now on, everything should be backwards compatible. Its very unlikely we'd remove any of the methods. Its more likely we'd add more optional arguments to existing methods, or add new APIs (like `rename` was just recently added).

We are beginning to use ChunkStore internally, so I expect more code churn as we discover and correct defects and as more use cases are discovered and fleshed out.

**Comment by bmoscon** [comment]
I should note that writing data continuously to a single ChunkStore chunk is not something we've tested or tried. It will work obviously, but I'm not sure what the performance is.

**Comment by mckelvin** [comment]
@bmoscon Thanks for your quick reply.

I did some experiments based on my use case:

## Append(continuously) cost between TickStore and ChunkStore

There's a DataFrame with ~16,000 rows (range from 00:00 to 23:59 yesterday). I tried to append all row by row:

```python
# chunk_library with DateChunker(chunk_size="D")

In [119]: for i in xrange(ticks.shape[0]):
     ...:     row = ticks.ix[i:i+1]
     ...:     t0 = time.time()
     ...:     chunk_library.append(symbol, row)
     ...:     times.append(1000 * (time.time() - t0))
```

Time cost for appending one row to a ChunkStore increased from 7 ms to 27 ms ([looks linearly](https://plot.ly/~mckelvin/0/chunkstoreappend-tick-by-tick/?share_key=NVdtauPbXPFl0iYajvTiAR)) while row count is increased from 0 row to ~16,000 rows, which is explainable since every `append` action needs to 1. read day-chunk 2. append 3. write back:

```python
In [120]: times[-10:]
Out[120]:
[27.11796760559082,
 27.092933654785156,
 27.159929275512695,
 28.378009796142578,
 27.34088897705078,
 27.325868606567383,
 27.325153350830078,
 27.168989181518555,
 28.486013412475586,
 27.103900909423828]

In [121]: times[:10]
Out[121]:
[9.86790657043457,
 7.24482536315918,
 8.012056350708008,
 6.938934326171875,
 6.855964660644531,
 6.731986999511719,
 6.760120391845703,
 6.773948669433594,
 5.972862243652344,
 6.778955459594727]
```

Time cost for appending one row to a TickStore is always around 3 ms.

## Bulk read cost between TickStore and ChunkStore

Time cost for reading all ~16,000 ticks from ChunkStore is `180 ms`, while from TickStore is `11.1 ms`(compressed in one chunk) / `8020 ms` (not compressed, one row one chunk).

No silver bullet. 😂

**Comment by bmoscon** [comment]
Yes, ChunkStore and Tickstore are pretty much opposite use cases. If you need to write data constantly throughout the day ChunkStore is probably not for you. Its much better for writing A LOT of daily/monthly/yearly data and then accessing very specific parts of the data very quickly. Its certainly possible to write a chunker to do what you want to do, but the current date_chunker is not really meant for what you want to do.
