### ISSUE TITLE
Still Cannot compile on Windows

### ISSUE THREAD

**Issue by yyueshek** [manahl/arctic#198]
Hi, My system is Windows 7 64-bit and I've installed the Anaconda 1.9.2(32bit) distribution and python 2.7.6.  I have read open issue and closed issues here but I still cannot make it run.
Following the steps listed by beartastic 
#6 

After install python-lz4 from here,
http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-lz4 

and follow this
https://www.ics.uci.edu/~pattis/common/handouts/mingweclipse/mingw.html
Install MinGW and Make sure the mingw bin directory is inside my Path environment
then  I run `pip install git+https://github.com/manahl/arctic.git`

I met problem like this` fatal error: omp.h: No such file or directory`

Anyone can help?

**Comment by bmoscon** [comment]
Windows is not supported. Not for any particular reason, simply that no one here is using it. I'm not sure if we have any plans to provide any support, but we're certainly happy to have someone submit a patch that fixes the Windows issues.

**Comment by bmoscon** [comment]
also, omp.h is part of OpenMP, so make sure you've installed those libraries and source files in your environment as well.

**Comment by yyueshek** [comment]
Thanks a lot, I may try to use linux instead.
