### ISSUE TITLE
ImportError: cannot import name Arctic

### ISSUE THREAD

**Issue by leolle** [manahl/arctic#203]
Hi, I am trying to run the demo code on my linux, but it reminds me that it can't import artic.
<ipython-input-19-beae5a5a3e79> in <module>()
----> 1 import arctic

/home/weiwu/projects/arctic/arctic.py in <module>()
----> 1 from arctic import Arctic
      2 import quandl
      3 
      4 # Connect to Local MONGODB
      5 store = Arctic('localhost')

ImportError: cannot import name Arctic

**Comment by bmoscon** [comment]
how did you install arctic? Also, you are calling your project/file arctic.py, I think that might be an issue, its also like you have a circular dependency issue here, your file is arctic and you are trying to import something from arctic, it might hit your local source first before checking installed python packages

**Comment by leolle** [comment]
yes, i made a mistake to name my file arctic.py.
the problem is solved, thank you.

**Comment by bmoscon** [comment]
closing
