### ISSUE TITLE
How to store strings in a pd.DataFrame in tickstore?  add 'O' dtype?

### ISSUE THREAD

**Issue by waterkirin** [manahl/arctic#206]
Hi, I am new to arctic and I am trying to write my pandas.dataframe to tickstore.

Pandas uses native python strings, which require an object dtype. Therefore an array of strings in pd.dataframe's dtype is dtype('O'), which is an object.
See the following links.

[http://stackoverflow.com/questions/34881079/pandas-distinction-between-str-and-object-types?noredirect=1&lq=1](url)

[http://stackoverflow.com/questions/21018654/strings-in-a-dataframe-but-dtype-is-object](url)

[http://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.kind.html#numpy.dtype.kind](url)

And I notice that in tickstore.py, function   _ensure_supported_dtypes(array)

```
    def _ensure_supported_dtypes(array):
        # We only support these types for now, as we need to read them in Java
        if (array.dtype.kind) == 'i':
            array = array.astype('<i8')
        elif (array.dtype.kind) == 'f':
            array = array.astype('<f8')
        elif (array.dtype.kind) in ('U', 'S', 'O'):        # add 'O' here, is this OK? 
            array = array.astype(np.unicode_)
```

So I just use python, could I just add dtype 'O' there? Is that OK?

Thank you guys!

**Comment by bmoscon** [comment]
What happens when you try and write strings to it now?

**Comment by richardbounds** [comment]
Artic stores all of its data (including strings) as compressed fixed-width C-style arrays. In an array of type 'O', the array contains pointers to objects that are elsewhere in memory, so Arctic can't do anything with that.

Your change may work if the .astype(np.unicode_) successfully converts the object array to a fixed-width Unicode array, but it will probably raise some other error if the objects in the array are not strings. Personally, I wouldn't do that here - I'd rather do the conversion of any object-type columns before trying to write to Arctic.

**Comment by jonasleotech** [comment]
Richard,

Can you please elaborate on how to do the conversation of an object-type string column to a numpy dtype string in a data-frame before writing it to the TickStore?

It seems like Pandas data-frames always store strings as native python strings even when I try to force them to 'S' and therefore perhaps we should allow the solution of adding 'O' as a supported type and let .astype(np.unicode_) raise an error if it's not a supported string?

Example of forcing a dataframe type to ’S’ and showing that it does not work (from http://stackoverflow.com/questions/34881079/pandas-distinction-between-str-and-object-types?noredirect=1&lq=1)
```python
>>> df.a.astype(np.dtype('S')).dtype
dtype('O')
``` 

Please note I can store strings if I try to save an array of dicts instead. I.e.
```python
df["index"] = df.index
records = df.to_dict('records')
arcticticklib.write('SYMBOL', records)
```

**Comment by harrychan-seekers** [comment]
Hi, I am wondering if I can change line 591 of arctic/tickstore/tickstore.py to
`elif (array.dtype.kind) in ('U', 'S', 'O'):`
So that python string will also be converted to unicode string.

**Comment by bashtage** [comment]
Is there a workaround for this?  Is there currently a way to store a string in a pandas DataFrame (which is always dtype `O`) in a TICK_STORE?

**Comment by bmoscon** [comment]
there is not a work around. You can use other storage engines or serialize the columns ahead of time

**Comment by bashtage** [comment]
Would it be possible to allow 'O' if the column could be verified to contain strings?  Ideally a structured dtype could be used which would replace a column of strings (`O`) with  fixed width string (`S` or `U`).

**Comment by bmoscon** [comment]
ok I created a pull request. 

https://github.com/manahl/arctic/pull/472

**Comment by bmoscon** [comment]
fixed
