### ISSUE TITLE
Renaming arctic libraries

### ISSUE THREAD

**Issue by jonasleotech** [manahl/arctic#224]
I would like support to rename arctic libraries and/or symbols to support double buffered large dataset loading.

The scenario would be having data scientists working against a library (say refinedtrades), while the dataset is reloaded from it's source data (a process that can take hours) without disturbing the data scientist with data outage or unclean data.

To support this I was thinking that renaming of libraries would be able to support the scenario.

I.e. the load process would be able to be done into a new library, i.e. refinedtrades_new and once the loading is done, delete the library refinedtrades and rename refinedtrades_new to refinedtrades.

**Comment by bmoscon** [comment]
@jonasleotech I assume you mean for tickstore? ChunkStore already support this, VersionStore and Tickstore do not. I think its feasbile in tickstore, but would be more challenging in versionstore.

**Comment by jamesblackburn** [comment]
Sounds like he wants to rename `libraries` rather than renaming `symbols`?  Is this correct @jonasleotech

**Comment by jamesblackburn** [comment]
Actually it should be possible to rename a library as mongodb has a rename collection command:
https://docs.mongodb.com/manual/reference/command/renameCollection/

Renaming a database isn't supported, however. So this should definitely be possible as a method on the `Arctic` object.

**Comment by bmoscon** [comment]
yeah, piece of cake. PR opened.

**Comment by bmoscon** [comment]
merged in

**Comment by jonasleotech** [comment]
@jamesblackburn @bmoscon 
Yup, renaming libraries based on the tick store :)

Thanks guys

**Comment by bmoscon** [comment]
@jonasleotech np. let me know if you have any issues

**Comment by rtadewald** [comment]
Maybe that's a stupid question, but... how i rename it? I'm having some issue... 

**store.list_libraries()**
_['BMF.EOD', 'BMF.Intraday_B', 'BMF.Intraday_T', 'BMF.Intraday_A', 'BMF_backup.EOD', 'BMF_backup.Intraday_B', 'BMF_backup.Intraday_T', 'BMF_backup.Intraday_A', 'BOVESPA.EOD', 'BOVESPA.Intraday_B', 'BOVESPA.Intraday_A', 'BOVESPA.TickData_Raw', 'BOVESPA.Intraday_T', 'BOVESPA_backup.EOD', 'BOVESPA_backup.Intraday_T', 'BOVESPA_backup.Intraday_A', 'BOVESPA_backup.Intraday_B', 'BOVESPA_backup.TickData_Raw', 'TickStore.Intraday_T', 'TickStore.Intraday_B', 'TickStore.TickData_Raw', 'TickStore.Intraday_A', 'TickStore.EOD']_

**(Pdb) store.rename_library('TickStore.TickData_Raw', 'TickStore.Bovespa_Raw')**
_pymongo.errors.OperationFailure: source namespace does not exist_

**Comment by bmoscon** [comment]
this is the unit test example:

```python
def test_lib_rename(arctic):
    arctic.initialize_library('test')
    l = arctic['test']
    l.write('test_data', 'abc')
    arctic.rename_library('test', 'new_name')
    l = arctic['new_name']
    assert(l.read('test_data').data == 'abc')
    with pytest.raises(LibraryNotFoundException) as e:
        l = arctic['test']
    assert('Library test' in str(e))
    assert('test' not in arctic.list_libraries())
```
