### ISSUE TITLE
I got Unicode problem when I try to read from library

### ISSUE THREAD

**Issue by wangzhe3224** [manahl/arctic#227]
Hi! 
----------------------------- Update --------------------------
Sorry problem solved.
I still use VersionStore
The problem is the name of my index column, here is the log of the database:

>
"dtype" : "[('\\xef\\xbb\\xbfExecTime', '<M8[ns]'), ('BuySell', 'S1'), ('CCYPair', 'S6'), ('BaseAmt', '<f8'), ('USDAmt', '<f8'), ('Dealt', 'S3'), ('Tag', 'S4')]",

As you can see, the data type of index col is strange, which cause the problem.

**You can close or delete this issue if you want.**

By the way , arctic is really fast!!!

Cheers,
Zhe 

----------------------------- Update --------------------------
I think it is because there is 'str' type data in my DataFrame.
How can I insert DataFrame with 'str' type data? What kind of type of library should I use?

Here is an example of my dataframe:
                                              
index                                               col1 col2        col3        col4           col5   col6                                                           
2015-01-26 21:59:03.653       'x'   'xxxxxx'  10000.0  11206.50   'xxx'  T414

as you can see, the col1, 2 5 and 6 are all str filed. 

Cheers,
Zhe

----------------------------- Old issues -----------------------------
I use python 2.7 and last version of arctic. 
I load raw data from an csv file into a pandas.DataFrame, and then insert them into the library.
I user a VersionStore.
But when I tried to read data from that library, I got following error:
 
'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

Anyone has a clue why this happens? or how to avoid it?

Cheers!
Zhe

**Comment by bmoscon** [comment]
So to be clear, this isnt an issue for you any more? It is strange that your index column name is a unicode string -- i've never seen that before

**Comment by wangzhe3224** [comment]
Problem solved by changing the index column name to a normal str.

Yeah it is strange, I guess it is because my format of CSV file.

**Comment by bmoscon** [comment]
ok, thanks for clarifying!
