### ISSUE TITLE
Axes and content are emptied when writing and re-reading a pd.Panel with np.nan values only

### ISSUE THREAD

**Issue by rudolf-bauer** [manahl/arctic#231]
I'm quite sure, this is not the desired behaviour of the arctic library: When I try to write and re-read a pandas Panel containing only np.nan values, the read object is completely empty i.e. there are no axes or values at all. 

`p = pd.Panel(items=['item'], major_axis=['maj'], minor_axis=['min'])`
`p`

> <class 'pandas.core.panel.Panel'>
> Dimensions: 1 (items) x 1 (major_axis) x 1 (minor_axis)
> Items axis: item to item
> Major_axis axis: maj to maj
> Minor_axis axis: min to min

`lib.write('symbol', p)`
`lib.read('symbol').data`

> <class 'pandas.core.panel.Panel'>
> Dimensions: 0 (items) x 0 (major_axis) x 0 (minor_axis)
> Items axis: None
> Major_axis axis: None
> Minor_axis axis: None

I'm using arctic '1.27.0' and pandas '0.18.1' within a ubuntu '16.04' docker container.

**Comment by bmoscon** [comment]
I don't have any experience with panels. What do you think @jamesblackburn ?

**Comment by shashank88** [comment]
Given pandas.Panel seems to be [deprecated](https://pandas.pydata.org/pandas-docs/version/0.23.4/whatsnew.html#deprecate-panel) , closing this for now. Please reopen if this is still valid for the replacement.
