### ISSUE TITLE
Retrieve data stored into Arctic using Julia

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#245]
Hello,

I stored some tick data using Python / Arctic.
I wonder if / how I could retrieve data using [Julia](http://julialang.org/)
Any help will be great

Kind regards

**Comment by jamesblackburn** [comment]
Arctic doesn't use any native Python data structures.  Instead it's storing compressed C-style arrays.  So it's straightforward to build Java and .Net clients, for example.

This would be neat, but isn't something we're likely to look at as we don't currently use Julia :(

**Comment by shashank88** [comment]
Doesn't seem active anymore, can we close this?

**Comment by bmoscon** [comment]
There are a ton of tickets that have been opened that are not active. I think if we're going to close this it should be for the reason "not going to do" or something along those lines.

**Comment by shashank88** [comment]
Will add a label of not-planned and close these (so it can be searchable easily in closed tickets)
