### ISSUE TITLE
Issues with multiprocessor/threading and later PyMongo versions

### ISSUE THREAD

**Issue by saeedamen** [manahl/arctic#250]
First off, Arctic is a great library, thanks for open sourcing it and I'm going to add a wrapper for Arctic to be used in my own open source financial data libraries findatapy and finmarketpy! 

I found a bit of an issue with using multiprocessor/threading in Python and PyMongo, which might affect other users. Every so often MongoDB appears to deadlock, when I make calls from multiple threads via Arctic. It turns out this is an issue with later versions of PyMongo (mine is 3.2). There is however a workaround by using connect=False (see http://api.mongodb.com/python/current/faq.html#pymongo-fork-safe) - like the below:

```
c = pymongo.MongoClient('127.0.0.1', connect=False)
from arctic import Arctic
store = Arctic(c)
```

Other people have fixed the problem by downgrading to an older version e.g. 2.8 (see https://github.com/dcrosta/flask-pymongo/issues/66 and http://stackoverflow.com/questions/31030307/why-is-pymongo-3-giving-serverselectiontimeouterror/31194981#3119498)

**Comment by bmoscon** [comment]
We can expose that as an option to arctic, but I don't think thats something we'd want to make default. 

thoughts @jamesblackburn ?

**Comment by jamesblackburn** [comment]
This is weird and unexpected.  We make efforts not to connect eagerly in the Arctic constructor, but this doesn't seem to be working right in the raw native Arctic.  Needs investigating.

**Comment by dimosped** [comment]
This might help to resolve this issue:
[https://github.com/manahl/arctic/pull/460](https://github.com/manahl/arctic/pull/460)

**Comment by dimosped** [comment]
Using connect=False doesn't prevent socket being initialized in the parent process before forking (using MongoEngine):
https://github.com/MongoEngine/mongoengine/issues/1234#issuecomment-216769597

**Comment by dimosped** [comment]
@bmoscon @jamesblackburn  do we think this is still an issue?
With multi-threading I doubt we have this issue.
With multiprocessing, creating MongoClient and then fork is known to cause deadlocks, but I expect this change to help mitigate the issue:
https://github.com/manahl/arctic/pull/460/files#diff-fb0e751696a7d90f9c0481d9544e1c53R118

**Comment by bmoscon** [comment]
I think we should close this
