### ISSUE TITLE
Down-sampling, binning, bucketing...

### ISSUE THREAD

**Issue by anthonywise** [manahl/arctic#253]
Not really an issue, but more of a question: I see that Arctic allows "bucketing data by source, user or some other metric (for example frequency: End-Of-Day; Minute Bars; etc.)." But does Arctic actually do the binning/bucketing off of an initial database, or does the data need to be pre-binned/bucketed and then written to the library?

If Arctic can do this, could an example be provided to, say, bucket 15min bars to daily (EOD) bars? Thank you so much!

**Comment by bmoscon** [comment]
since this is a tickstore question I'm going to let someone else answer

@jamesblackburn

**Comment by richardbounds** [comment]
Arctic doesn't do any binning/bucketing itself, it just stores the data.

**Comment by anthonywise** [comment]
Thanks Richard!
