### ISSUE TITLE
Not authorized to manage mLab's Cloud Databases

### ISSUE THREAD

**Issue by rtadewald** [manahl/arctic#254]
Hi,

I'm having an issue trying to manage a Cloud Database created with mLab.
I can manage it well using the PyMongo functions (insert data, drop collections, ...) and even connect with Arctic:

In[5]: store = Arctic(MongoURL)
In[6]: store
Out[6]: Arctic at 0x7f438d0, connected to MongoClient(host=['ds049466.mlab.com:49466'], document_class=dict, tz_aware=False, connect=True, maxpoolsize=4, connecttimeoutms='2000', sockettimeoutms='600000', serverselectiontimeoutms='30000')

But, when i try to insert a library, for example, i got the following error:

In[7]: store.initialize_library('BMF.Intraday_T')
<class 'pymongo.errors.OperationFailure'> initialize_library [command SON([('listCollections', 1), ('cursor', {})]) on namespace arctic_BMF.$cmd failed: not authorized on arctic_BMF to execute command { listCollections: 1, cursor: {} }], retrying 3

Does anyone can help me?

**Comment by bmoscon** [comment]
typically that means you do not have access to Mongo. In this case it looks like listCollections is failing

**Comment by bmoscon** [comment]
since this is a permissions issues, not an arctic issue, im closing this.

**Comment by jamesblackburn** [comment]
Agreed you need write access to a database named like: `arctic_BMF`
