### ISSUE TITLE
Can't pip3 install arctic from Amazon's Linux

### ISSUE THREAD

**Issue by rtadewald** [manahl/arctic#255]
Hi,
I'm trying to install arctic on Python 3.4 on an Amazon Linux, but i'm reciving this error:
error: command 'gcc' failed with exit status 1.

I already have the python3.4-dev installed. Any idea?

**Comment by bmoscon** [comment]
it could be anything. I'm guessing its related to openMP, but without the full error message its pretty much impossible to know.

**Comment by jamesblackburn** [comment]
Need more detail.
