### ISSUE TITLE
error: Setup script exited with platform cygwin is not supported

### ISSUE THREAD

**Issue by smad22** [manahl/arctic#257]
Please advise on the above.  Thanks.

**Comment by bmoscon** [comment]
arctic is only officially supported on linux. some people have had limited success with OSX. I haven't heard of anyone using cygwin with any success, have you @jamesblackburn ?

**Comment by bmoscon** [comment]
arctic now supported on OSX and Linux. Windows is still not supported. Going to mark this as a dupe of #6
