### ISSUE TITLE
TickStore: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mckelvin** [manahl/arctic#268]
The following code (as a workaround for https://github.com/manahl/arctic/pull/267 ) can be use to reproduce the issue. In my setup, this bug could be happen 1 in 20000 cases.

``` python
df = tick_library.read("symbol", date_range)
tick_library.delete("symbol", date_range)

try:
    tick_library.read("symbol", date_range)  # this line breaks 
    ...
except NoDataFoundException:
    pass

```

The traceback points to https://github.com/manahl/arctic/blob/e6ea7164f8706ae1f2cd2ab22b0801d421e94220/arctic/tickstore/tickstore.py#L194 where the variable`chunk` could be `None`

<img width="846" alt="screenshot 2016-10-28 18 36 03" src="https://cloud.githubusercontent.com/assets/865677/19803853/93e744a0-9d3d-11e6-91b4-754c70c235fd.png">

**Comment by bmoscon** [comment]
since the code in question was a workaround, is this ok to close? #267 was merged
