### ISSUE TITLE
No handlers could be found for logger "arctic.store.version_store"

### ISSUE THREAD

**Issue by mattdornfeld** [manahl/arctic#27]
So when I run this code I get the following warning. Do you know what might be causing that?

> > > store.initialize_library('NASDAQ')
> > > No handlers could be found for logger "arctic.store.version_store"

**Comment by eeaston** [comment]
Hi there, this is telling us that there's no loggers initialized yet for arctic.
You can set them up using the logging module using:

    import logging
    logging.basicConfig(format='%(asctime)s %(message)s', level='INFO')

Hope this helps!

**Comment by jamesblackburn** [comment]
Can we set up a default logger if one doesn't exist?

**Comment by frankscholten** [comment]
@jamesblackburn Good idea. Also running into this issue.
