### ISSUE TITLE
Chunk store very slow

### ISSUE THREAD

**Issue by HedgeShot** [manahl/arctic#278]
Hi,

I am experimenting with Arctic and I am slightly confused about the performance I get.
My goal is to have a DB that contains daily stock infos (close, high, low, etc) and to be able to call them by DateRange. The DB is updated daily so I use Chunk Store as it seems to fit best the purpose. In total, I have around 14 MM documents (around 8000 unique tickers).

The operations to create the database and to get single stock information are very slow, around 40-45 seconds to perform 'stocks.update(symbold, df, upsert = True)' and another 40-45 seconds to perform 'stocks.read(symbol)'.

Doing a db.collectionName.find('sy':symbol) directly in the mongo console seems fast.

Any idea why I could get so poor read/write? The mongo server and the python script are on the same machine.

Thank you

**Comment by bmoscon** [comment]
update is a slow operation, it has to read the data for the time frame the updated dataframe corresponds to (this could be a single chunk, or many many chunks depending on your chunking size and the data you are writing), it has to deserialize it, update it, serialize it, and write it back to mongo. If you are just adding/appending new data, use append. 

If you give me more information about your use case, I can help you figure out where the bottleneck is. (Is all the data stored in one symbol? What is the chunk size? When you update, does the data overlap other chunks?)

**Comment by bmoscon** [comment]
Also, ChunkStore is not designed to be super fast writing data. It shouldnt be slow like you are seeing, but its focus is speed on the read side.

**Comment by bmoscon** [comment]
Also, what version of Arctic?

**Comment by jamesblackburn** [comment]
Aslo how have you ended up with 14MM documents? Sounds like you're chunking daily for daily data.  If you're storing daily data I would go for something like yearly chunks. That way you'll get the benefits of compression etc.  VersionStore will do this for you by default ;)

**Comment by HedgeShot** [comment]
Thanks for the fast answer guys.
I guess I understood VersionStore wrong. I thought it wasn't possible to call a symbol by DateRange.

My use case: download data from Yahoo (close, high, low, open, volume, splits and dividends) for several thousand tickers every day and create one DataFrame per ticker with DateTime as the index of the DataFrame. To create the first database, I called the entire history of each ticker from Yahoo (this is the process in Arctic that took 40-45sec per ticker to store in MongoDB). The chunk is indeed daily. 

My actual setup: Win10, MongoDB 3.2.9, Python 2.7.12, Arctic 1.33.0

**Comment by bmoscon** [comment]
VersionStore will work with date ranges, but thats not what its optimized for. For you use case, it sounds like VersionStore would work just fine though. 

For what you are doing, if you want to use ChunkStore, I'd recommend using a larger chunksize, either monthly or yearly, depending on how you plan on reading back the data.

**Comment by HedgeShot** [comment]
Thank you, I tried to create the DB using VersionStore and it is indeed much faster - around 0.2 seconds to write and 0.026 seconds to read. Is there a way to get last date from a VersionStore in order to know from when the DB needs to be updated?

**Comment by bmoscon** [comment]
I dont think there is any easy way to get the last date out. What you can do is store metadata along with the data. VersionStore support storing metadata easily. Just update this on every write with the latest date. You can query the symbols metadata to get the latest date. Any better suggestion @jamesblackburn ?

**Comment by jamesblackburn** [comment]
Yep, as @bmoscon says, storing it as `metadata=` on write is the way to go.  You can get the time of the write of the last version too, but that isn't quite the same as the timestamp of the last value in the timeseries.

**Comment by HedgeShot** [comment]
Thanks for the help!
