### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#279]
@jamesblackburn we should create an issue template so when people create issues, we can get some standard information like arctic version, storeage engine (tick, version, chunk), sample code, etc. What things do you think we should include?

see:
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by jamesblackburn** [comment]
Sounds good. 

Version:
Arctic Storage Type: VersionStore ; ChunkStore ; TickStore
Platform:

**Comment by bmoscon** [comment]
merged
