### ISSUE TITLE
version_store.delete fails has_symbol() assertion

### ISSUE THREAD

**Issue by eeaston** [manahl/arctic#29]
We're seeing the has_symbol() assertion failing sporadically still in a clustered mongo environment, even after making has_symbol force reads from the Primary in the the v1.5.0 release.

    arctic/store/version_store.py", line 666, in delete
        assert not self.has_symbol(symbol)
    AssertionError

A retry on the operation will work, but it's not ideal!

**Comment by mildbyte** [comment]
Confirmed as an in-house library problem.
