### ISSUE TITLE
Problem with TickStore: "arctic.date._mktz.TimezoneError: Timezone "UTC" can not be read"

### ISSUE THREAD

**Issue by rtadewald** [manahl/arctic#291]
I'm with an issue trying to add data to a TickStore Library.

The data is a DataFrame and it's index is a DatetimeIndex.
**_(Pdb) data_new.index
DatetimeIndex(['2014-11-21 16:56:58.534000-02:00',
               '2014-11-21 17:49:56.935000-02:00',
               '2014-11-21 18:00:01.099000-02:00',
               '2014-11-21 18:06:00.012000-02:00'],
              dtype='datetime64[ns, America/Sao_Paulo]', freq=None)_**

When i try to add it to the library, i got this:
**_(Pdb) library.write(i, data_new)
arctic.date.mktz.TimezoneError: Timezone "UTC" can not be read, error: "[Errno 2] No such file or directory: '/usr/share/zoneinfo/UTC'"_**

How can i deal with it?

**Comment by bmoscon** [comment]
What version of arctic? 

What OS?

**Comment by rtadewald** [comment]
I'm using a Windows 7 Professional, 64 bits.
My arctic is in version 1.21.0

**Comment by rtadewald** [comment]
The problem is when dealing with this timezone. I can normally add this kind of a data into a normal arctic's library.

**Comment by bmoscon** [comment]
You'll need to use arctic 1.26.0 at least, it uses a different timezone lib that removes that linux path dependency.

**Comment by rtadewald** [comment]
I've already updated to 1.33 and the problem stays the same.

**Comment by bmoscon** [comment]
@jamesblackburn may know something I don't know. However, Linux is the only supported version

**Comment by bmoscon** [comment]
also, might want to make sure the deps are installed correctly, we use dateutil to get the timezone

**Comment by rtadewald** [comment]
I'll try to run this code in Ubuntu and 'll post the result after.

**Comment by spyamine** [comment]
in the _mktz.py file comment the code and use the following instead 👍 

from tzlocal import get_localzone
tz = get_localzone()

return tz

**Comment by spyamine** [comment]
oups I see in the code that you have already modify it. will update the version I have and try again. but the modifications have the same spirit, using from tzlocal import get_localzone

**Comment by bmoscon** [comment]
@spyamine if you have a fix for this that works on windows and doesnt break any existing functionality we'd love to have you submit a PR

**Comment by spyamine** [comment]
After upgrading, your code seems to work ok for me in windows. 
but before that i've used the simple code mentionned above. Your function seems to me more elaborate than mine.

**Comment by spyamine** [comment]
https://regebro.wordpress.com/2012/09/12/presenting-tzlocal-a-simple-way-to-get-your-local-timezone-for-pytz/

this is the link when i found the solution

**Comment by bmoscon** [comment]
ok that makes sense @spyamine 

We recently changed to use a library rather than relying on the Linux specific file, so it SHOULD work on windows as is, but we haven't tested it

**Comment by spyamine** [comment]
it worked on my station with windows. I tried to use arctic on Mac and I have notice that there is still a problem installing it.

**Comment by bmoscon** [comment]
so, can we close this?

**Comment by spyamine** [comment]
Yes!!
I think it a good idea
