### ISSUE TITLE
Publish the documentation

### ISSUE THREAD

**Issue by jamesblackburn** [manahl/arctic#3]

**Comment by femtotrader** [comment]
You might use http://www.readthedocs.org/

We use it here http://pandas-datareader.readthedocs.org/

**Comment by jamesblackburn** [comment]
@femtotrader says we should consider moving the `Changes.md` at the same time... #75

**Comment by dag4202** [comment]
Is there help needed for this issue?

**Comment by rueberger** [comment]
Any updates with this? Great project, lack of documentation is frustrating though

**Comment by bmoscon** [comment]
yes, I'll start on this this weekend and hopefully have at least a rough draft done by end of next week

**Comment by bmoscon** [comment]
versionstore docs now completed: https://github.com/manahl/arctic/blob/master/docs/versionstore.md

just tickstore left!

**Comment by shashank88** [comment]
@bmoscon I think the documentation can use some more updates. I found it quite hard to browse through the documentation and get an intuitive feel of what arctic is, why would I use it, what real world uses cases can people use this etc when I first came across it. Have used readthedocs / sphinx for a project before, might be a good idea moving to that with what we have and add either a FAQ or some more basic info. Can help with that.

Will create a new ticket with the a list of TODO's wrt documentation. wdyt?

**Comment by bmoscon** [comment]
@shashank88 personal preference I guess. I prefer walk throughs with examples, primarily since the majority of emails/questions I get are about how to use it. I do think a more comprehensive documentation of the project as a whole (via readthedocs/sphinx) is a good idea

**Comment by shashank88** [comment]
I tried both sphinx and mkdocs yesterday, had some trouble getting sphinx to render properly with markdown, though sphinx is the more standard tool for python, but expects rst (it's supposed to work with markdown as well but it's not recommended)
Mkdocs was much easier to use, and worked out of the box with .md files.

So options here might be:
a) Move to Rst and Sphinx works out of the box
b) Just use mkdocs as it works nicely with md files (will paste the images in a bit)
c) Make Sphinx work with md files.

**Comment by yschimke** [comment]
Looks great, though I'll defer to @jamesblackburn and @bmoscon

**Comment by shashank88** [comment]
I guess it's the same with readthedocs, given it has webhooks for new merges to the repo. I don't really mind githubpages vs readthedocs as long as we can use Markdown and mkdocs. Readthedocs seemed easy to configure and setup so just used that. Will take a quick look at that as well

**Comment by shashank88** [comment]
Have merged mkdocs and plan on using https://arctic.readthedocs.io/en/latest/ for now. Should I close this ticket now as this ticket was for publishing the documentation?
Will create a new ticket with a list of TODO items for documentation improvements that people can append to.

**Comment by shashank88** [comment]
Closing this issue, succeeded by #681
