### ISSUE TITLE
Storing orderbook

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#302]
Hello,

I'd like to know if storing orderbook in Arctic is a feature that could be considered.
Compression could help a lot.

You can find here https://www.quora.com/Where-can-I-download-historical-limit-order-book-information where to download some order books

https://lobsterdata.com/info/DataSamples.php provides some examples

Kind regards

**Comment by bmoscon** [comment]
I'm not sure what you're asking for. Those files are CSV files, which can easily be made into a dataframe (.from_csv()), which of course are easily written to arctic.

**Comment by femtotrader** [comment]
So each time you are storing the whole orderbook (not differences between 2 orderbooks)?

**Comment by bmoscon** [comment]
yes

**Comment by femtotrader** [comment]
So it may be very big.
Are you using this in production?

**Comment by bmoscon** [comment]
I don't believe anyone stores orderbooks, but i could be mistaken. this is a question for @jamesblackburn

**Comment by richardbounds** [comment]
We just store the tick stream, which would be the diff between the order book at each timestamp.

**Comment by jamesblackburn** [comment]
@femtotrader as Richard says we store the history of the different levels as individual columns in the tickstore, so whenever there's a level change there may be a delta recorded in a number of columns - taking a couple levels for BID and ASK:

![image](https://cloud.githubusercontent.com/assets/55716/21356968/6dbd9d62-c6cb-11e6-8443-b6e0e56f243e.png)

This is how the data appears on our feeds.  In reality we ingest hundreds of fields, and we aim to store every tick in tickstore.

We have previously used more complex Price Level compression of Level 2 order books (and may do that again in the future), but for the moment we've found that the per-column compression works well enough.

**Comment by femtotrader** [comment]
Thanks @jamesblackburn
