### ISSUE TITLE
Should NoDataFoundException raise for Empty DataFrame?

### ISSUE THREAD

**Issue by mckelvin** [manahl/arctic#306]
#### Arctic Version

```
<= 1.36.0
```

#### Arctic Store

```
Not related
```

#### Platform and version

Not related

#### Description of problem and/or code sample that reproduces the issue

Support there're a few ticks with following indices in the arctic library:

```
2016-12-21 14:00:45+08:00
2016-12-21 14:00:46+08:00
2016-12-21 14:00:49+08:00
```

When read with `DateRange("2016-12-21 14:47:00", 2016-12-21 14:48:00, CLOSED_CLOSED)` (no ticks at that time), an empty DataFrame will be returned. (A `NoDataFoundException` works fine only if the date_range doesn't exist in any data chunks.)

In majority of my use cases, I would expect a `NoDataFoundException` instead of an empty DataFrame. So I have to write code like this:

```python
try:
    df = tick_library.read(symbol, date_range)
    if df.shape[0] == 0:
        raise NoDataFoundException
except arctic.exceptions.NoDataFoundException:
    pass
```

That's a little bit weird that `NoDataFoundException` will not be raised if there's no data! Is that's a feature or bug?

**Comment by jamesblackburn** [comment]
Ah we only raise this is no data has been stored under that particular key.

I think it would cause too much breakage if we changed this behaviour now.

**Comment by bmoscon** [comment]
it is a bit of a misnomer - it really means symbol does not exist.
