### ISSUE TITLE
TickStore when data is length is varying per write

### ISSUE THREAD

**Issue by js190** [manahl/arctic#310]
#### Arctic Version

```
1.36
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Ubuntu 16.04

#### Description of problem and/or code sample that reproduces the issue

After initial load of large dataframe of Quandl daily data to Tickstore, subsequent daily or couple of days updates gives ``OverlappingDataException``. If i insert this data as a list of dicts like ``[{'index': datetime, 'volume': 10, ...}, ...]`` then this data is not persisted.

I guess this is because there was an initial bucket size set by the insert of large DataFrame, then subsequent smaller DataFrames do not match this size...? 

I am using a TickStore to save samples of data from InteractiveBrokers, and this is working nicely for multiple contracts. In this case i am always inserting a list of dicts of length 1. So the bucket size has always been consistent. 

Is a TickStore the wrong tool for the job for storing data which may be received in varying length?

**Comment by bmoscon** [comment]
That exception has nothing to do with the length of the write. That exception means that you've overwriting data. Tickstore doesnt let you overwrite data in a range.

see the exception message:

```python
raise OverlappingDataException("Document already exists with start:{} end:{} in the range of our start:{} end:{}".format(doc[START], doc[END], start, end))
```

**Comment by jamesblackburn** [comment]
> After initial load of large dataframe of Quandl daily data to Tickstore, subsequent daily or couple of days updates gives OverlappingDataException. If i insert this data as a list of dicts like [{'index': datetime, 'volume': 10, ...}, ...] then this data is not persisted.
> I guess this is because there was an initial bucket size set by the insert of large DataFrame, then subsequent smaller DataFrames do not match this size...?

For low-frequency data (non-tick data) you should use the `VersionStore` or `ChunkStore`.

`TickStore` will write a document per `chunk_size` elements passed into the write call.  It won't handle partial writes within the range of data that has already been written for an existing symbol. 

> In this case i am always inserting a list of dicts of length 1. So the bucket size has always been consistent.

This will result in a document per row, which is really inefficient.  TickStore is low-level and mainly used for storing very high frequency data with lots of messages per second.  For lower frequency data I'd recommend using one of the other stores which will help deal with the batching for you.
