### ISSUE TITLE
Proposed change: use dill rather than cpickle in PickleStore

### ISSUE THREAD

**Issue by cmorgan** [manahl/arctic#312]
What do you think of a proposed change of serialiser from cPickle to https://github.com/uqfoundation/dill. Dill is a little slower but has multiple benefits, one of which is pickling by serialising the class definition and not the reference. This would make possible unpickling objects in different namespaces

**Comment by bmoscon** [comment]
We don't typically use the picklestore in VersionStore very much. I think if you submitted a pull request, we'd take a look. 

What do you think @jamesblackburn ?

**Comment by jamesblackburn** [comment]
Interesting idea.

As @bmoscon says we'd generally prefer the stores to understand the structure of the data (rather than arbitrarily pickling).  But not averse to having a better pickle as a fallback.

**Comment by shashank88** [comment]
Closing this. Please reopen if there are any updates
