### ISSUE TITLE
Suggestion: requesting data between times 

### ISSUE THREAD

**Issue by agiap** [manahl/arctic#322]
Is there a way to request data between times? 

For example, suppose I want to get the prices for AAPL from 2010 to 2015 between 10 am and 11 am: 

symbol = 'AAPL'
date_range = DateRange(start_date='2010-01-01', end_date='2015-12-31', start_time='10:00', end_time='11:00')
lib.read(symbol, date_range).data

Is that possible or do I need to request the full day and then keep what I need? 

Thanks!

**Comment by bmoscon** [comment]
I dont think version store supports time, just dates. Right @jamesblackburn ?

**Comment by jamesblackburn** [comment]
No this isn't possible. You'll have to read the data back and resample it in pandas.  It should be quite fast to do this.

**Comment by agiap** [comment]
Thanks for your answers guys. Out of curiosity (I'm not familiar with MongoDB), is it impossible to implement given the current design of VersionStore, or is it just not implemented? I did a comparison of retrieving custom daily bars from 1 minute bars in MySQL (filtering times and daily resampling done in MySQL) vs. Arctic (reading the entire data and then applying the logic) and sadly most of my speed gains from Arctic's amazing reading speed were lost. Thanks!

**Comment by jamesblackburn** [comment]
We store the data compressed in chunks for fast retrieval and access.  So without support in the database for compressed data blobs, the client needs to do this work.  Mongo treats most the data we store as binary blobs with a btree for 'symbol' and date-range slicing.

It's possible to use a more naive scheme, or, alternatively, cache the 10 min slices you want - I can't imagine that data would be very big at all.
