### ISSUE TITLE
mongodb authorisation issue

### ISSUE THREAD

**Issue by rajtho** [manahl/arctic#327]
#### Arctic Version

Latest. >Arctic.__version__ doesnt give any details though :(
```
# Arctic version here
```

#### Arctic Store
VersionStore

#### Platform and version

Ubuntu 16.04LTS
#### Description of problem and/or code sample that reproduces the issue

Newbie to Arctic and Mongodb. i am following the suggested how-to examples on ipython. 
upon >store.initialize_library("eodUSData")
i get:
OperationFailure: not authorized on arctic to execute command { listCollections: 1, cursor: {} }

Any suggestions of how to pass the username and passwd?

**Comment by mckelvin** [comment]
```python
from arctic.auth import Credential
from arctic.hooks import register_get_auth_hook

def arctic_auth_hook(mongo_host, app, database):
    return Credential(
	database="arctic",
	user="username",
	password="password",
    )


def main():
    register_get_auth_hook(arctic_auth_hook)
    store = arctic.Arctic(host, app_name)
    # ...
    

if __name__ == '__main__':
    main()
```

This is the way how I use. I wish it could be more easier.

**Comment by rajtho** [comment]
Thanks a ton kelvin. the hooky way works.

**Comment by firoozye** [comment]
Thank you, @mckelvin  There is nowhere else I see as straight-forward an example as yours. (e.g., unlike the cryptic [Setting up user/password authorization guide? ](https://github.com/manahl/arctic/issues/563). 
It worked!

**Comment by Jufik** [comment]
Dumb question, but shouldn't we be able to use standard mongo connection string?

**Comment by kdauria** [comment]
Try adding arguments to `Arctic.__init__`. `**kwargs` are passed to `MongClient.__init__`. https://pymongo.readthedocs.io/en/stable/examples/authentication.html

``` arctic.Arctic(host, app_name, username='username', password='password') ```

**Comment by cspipaon** [comment]
I assume `host` is the IP address of the Arctic/MongoDB server, right? What should I use as `app_name`, though?
