### ISSUE TITLE
Update MongoDB to 3.4.2 - initialize library warning: couldn't enable sharding 

### ISSUE THREAD

**Issue by bmpalatiello** [manahl/arctic#328]
#### Arctic Version

```
1.37.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Windows 10

#### Description of problem and/or code sample that reproduces the issue

I've recently upgraded to MongoDB 3.4.2 and whenever I initialize a library I get back:

`WARNING:arctic.store.version_store:Library created, but couldn't enable sharding: no such command: 'enablesharding', bad cmd: '{ enablesharding: "arctic" }'. This is OK if you're not 'admin'`

I'm unsure what the implications of this is. I've never gotten it before.

**Comment by bmoscon** [comment]
thats benign, unless of course you are using a sharded database and are admin. Right @jamesblackburn ?

**Comment by richardbounds** [comment]
Exactly. You need to be able to write to the admin database to enable sharding on a collection. VersionStore assumes that the database is sharded and tries to do it, but just warns if it fails.

**Comment by bmoscon** [comment]
going to close this since there isnt really anything to fix/address.
