### ISSUE TITLE
Unable to install arctic using pip install arctic

### ISSUE THREAD

**Issue by flashtraderpro** [manahl/arctic#331]
#### Arctic Version

```
# 1.40
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Linux

#### Description of problem and/or code sample that reproduces the issue
I am trying to install arctic using : pip install arctic but I am getting this error:

Collecting arctic
  Downloading arctic-1.40.0.tar.gz (455kB)
    100% |################################| 458kB 504kB/s
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ZGsXfo/arctic/setup.py", line 24, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

Am I doing something wrong?

thanks,

**Comment by bmoscon** [comment]
No. You just need to install Cython first. Just do ```pip install cython```

**Comment by flashtraderpro** [comment]
I tried to install Cython first.

$ pip install cython
Collecting cython
  Downloading Cython-0.25.2-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 92kB/s
Installing collected packages: cython
Successfully installed cython-0.25.2

But after I try : pip install arctic I still get:

$ pip install arctic
Collecting arctic
  Using cached arctic-1.40.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NrCVeO/arctic/setup.py", line 24, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

**Comment by bmoscon** [comment]
no idea. If Cython is installed, it shouldnt give you this error. Any ideas @jamesblackburn ?

**Comment by bmoscon** [comment]
@flashtraderpro a follow up question. Are you using conda and/or a mac?

**Comment by bmoscon** [comment]
due to lack of information, and fact that this is an environment issue, and not an arctic issue, I am closing this. please reopen if you have more information
