### ISSUE TITLE
how to resolve below error while running python using cntk

### ISSUE THREAD

**Issue by jincyjojy** [manahl/arctic#338]
#### Arctic Version

```
# Arctic version here
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Put here

#### Description of problem and/or code sample that reproduces the issue

Put Here

![image](https://cloud.githubusercontent.com/assets/25997652/24259411/d1f59f52-1016-11e7-9510-0491b3b77501.png)
![capture](https://cloud.githubusercontent.com/assets/25997652/24259510/1200173a-1017-11e7-99b0-2531383c429a.PNG)

**Comment by bmoscon** [comment]
this is nothing to do with arctic
