### ISSUE TITLE
initialize_library can't create a collection to persist data

### ISSUE THREAD

**Issue by bai343901438** [manahl/arctic#340]
#### Arctic Version

1.40.0

#### Arctic Store
VERSION_STORE

#### Platform and version

python 3.6 and IDE is PyCharm 2016.3.2

#### Description of problem and/or code sample that reproduces the issue

I follow the demo.py to create my project.When I run this project,it throw a error:
`<class 'pymongo.errors.OperationFailure'> stats [Collection [arctic_NASDAQ.stock] not found.], retrying 3`

my code is simple:

```
store=Arctic('localhost');
store.initialize_library('NASDAQ.stock');
library = store['NASDAQ.stock'];
```
later,I found that the library(db) arctic_NASDAQ have not include the collection named "stock".
When I create "stock" collections in arctic_NASDAQ use mongodb client and run the project again,there is no errors anymore.

Why the `store.initialize_library('NASDAQ.stock');` can't create collection named  "stock"(even though it already create collections like stock.ARCTIC、stock.changes、stock.versions and etc...)?
It's there any errors in my code?or I use arctic in a wrong way？

Now，I find a way to workaround:

```
import pandas as pd
from arctic.arctic import Arctic
from pymongo import MongoClient

store=Arctic('localhost');
store.initialize_library('NASDAQ.stock');
library = store['NASDAQ.stock'];

#use pymongo to create the collection stock
client = MongoClient('localhost',27017);
db=client['arctic_NASDAQ'];
#judge whether the stock collection is created
if 'stock' not in db.collection_names():
    db.create_collection('stock');
```
but I think it should be my fault to use the arctic in a wrong way.How can I make it correct?

Any information will be help.Thank you guys!

**Comment by bmoscon** [comment]
Does it work if you call it something else, something like nasdaq_stock?

**Comment by bai343901438** [comment]
@bmoscon  Thanks for your response!
When I call it someting else like nasdaq_stock.after initialize_library,the mongodb will build a database like this:
```
TEST_MONGODB
|
|---arctic
	|
	|-------nasdaq_stock.ARCTIC
	|-------nasdaq_stock.changes
	|-------nasdaq_stock.snapshots
	|-------nasdaq_stock.version_nums
	|-------nasdaq_stock.versions

```
After initialize_library,I follow the guide use library.write.It's will return a error "nasdaq_stock does not exists".
If I use pymongo to build the collection nasdaq_stock after initialize_library,the arctic worked very well.
It's strange that the data will store in nasdaq_stock,but the function initialize_library dose not create this collection.
I have tried to figure out why the things happened,search on google,read the arctic code,but I failed...
Now I use pymongo to workaround,and arctic run well in my program.Due to arctic is very useful to store dataframe in mongodb，I think to get clear to this question will help me deep learning arctic.

It's there any errors in my code?
Kind regards!

**Comment by richardbounds** [comment]
It isn't clear which bit doesn't work for you.

This works for me (where I already have a mongo database called `arctic_test`, and have connected as a user with write permission to that database): 

```python
store.initialize_library('test.stock')
library = store['test.stock']
aapl = quandl.get("WIKI/AAPL", authtoken="your token here")
library.write('AAPL', aapl, metadata={'source': 'Quandl'})
library.read('AAPL')
```

**Comment by bmoscon** [comment]
@bai343901438 what version of mondodb are you running?

**Comment by bmoscon** [comment]
_appears_ to be user error, and no further information from the submitter. closing
