### ISSUE TITLE
Datetime Error

### ISSUE THREAD

**Issue by ryanyuan42** [manahl/arctic#341]
#### Arctic Version

```
# Arctic 
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Put here

#### Description of problem and/or code sample that reproduces the issue

Here is the problem. When arctic write data to mongodb, I identify data with a timezone. But when write data next time, arctic will check if there is overlapping problem. When I write my data, mongodb actually will automatically convert data timezone to UTC. So when arctic extract data from mongodb, arctic didn't change the timezone (i.e, data extracted with UTC timezone). So when checking the overlapping problem, it is comparing UTC time with my own timezone time. 

The point is,
In function,
```
arctic.tickstore.tickstore._assert_nonoverlapping_data

if doc:
            if not doc[END].tzinfo:
                doc[END] = doc[END].replace(tzinfo=mktz('UTC'))
```

doc[END].tzinfo seems like always to be None because mongodb itself will automatically transfer timezone to UTC. And when data is extracted, datetime does not have "tzinfo" property.

So arctic defaults make tzinfo to UTC, which make the rest comparison problematic.

I am not sure if my understanding is right. But I think I encounter this problem in production.

Best,
Tianshu Yuan

**Comment by bmoscon** [comment]
I think this is by design (i.e. tickstore stores in UTC) but I should let @jamesblackburn confirm since he is the tickstore expert

**Comment by ryanyuan42** [comment]
got it, no more question.

**Comment by richardbounds** [comment]
Yes, that's right - tickstore stores everything in UTC, it doesn't really do timezones.
