### ISSUE TITLE
VersionStore date_range logic fails to return chunks beyond first instance of end_date

### ISSUE THREAD

**Issue by TomTaylorLondon** [manahl/arctic#346]
When inserting large dataframes with duplicate datetimes (e.g. MultiIndex panels) date_range may fail to return the correct data.

Issue is with: https://github.com/manahl/arctic/blob/master/arctic/store/_pandas_ndarray_store.py#L87

Should be:
```
idxend = min(np.searchsorted(dts, end, side='right'), len(dts) - 1)
```

**Comment by bmoscon** [comment]
@TomTaylorLondon do you want me to fix this, or are you going to push your own fix?

**Comment by bmoscon** [comment]
also, @TomTaylorLondon it would be good if you could give me an example of the dataframe that causes the issue so I can add a unit test :)

**Comment by bmoscon** [comment]
FYI Tom I have a branch with the fix. I'll open a PR tomorrow.

**Comment by bmoscon** [comment]
fixed
