### ISSUE TITLE
_compression.py has AttributeError: 'module' object has no attribute 'compressarr'

### ISSUE THREAD

**Issue by tesla1060** [manahl/arctic#348]
#### Arctic Version

```
# 1.42.0
```

I run into an `AttributeError` in function `compress_array` in file `_compression.py`,
because `lz4` does not have a function named `compressarr`

      AttributeError: 'module' object has no attribute 'compressarr

**Comment by bmoscon** [comment]
LZ4 doesn't, but the cython compression module in arctic does. How was this built?

**Comment by tesla1060** [comment]
@bmoscon I have installed this on a windows 7, 64 bit machine with the following command,

    pip install git+https://github.com/manahl/arctic.git

**Comment by tesla1060** [comment]
actually I have step through the below code in `_compression.py`,

    try:
        from . import _compress as clz4
    except ImportError:
        logger.warning("Couldn't import cython lz4")
        import lz4 as clz4

Apparently, the `except` part is on, and `lz4` is imported as `clz4`, thus does not have the `compressarr` function.

**Comment by bmoscon** [comment]
opened a PR to address this, #349 but a few caveats. The parallel compression is needed to get full speed from arctic, and Windows is not currently supported, so if you want to build the cython component, it will take a lot of manual steps.

**Comment by bmoscon** [comment]
fixed with latest merge, so will be in next release of arctic
