### ISSUE TITLE
publish project on pipy

### ISSUE THREAD

**Issue by llazzaro** [manahl/arctic#35]
this will allow to install the project from pip directly with "pip install arctic"

instructions:
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by alexispetit** [comment]
Error on Windows 8.1: 
IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by jamesblackburn** [comment]
We already upload packages for Linux x86_64 and a source tarball to pypi: https://pypi.python.org/pypi/arctic/ . Is there something your misusing?

**Comment by llazzaro** [comment]
oh great! seems that I had connection issue with pipy.

thanks!
