### ISSUE TITLE
AttributeError : set_quota

### ISSUE THREAD

**Issue by TheTradingWarrior** [manahl/arctic#359]
#### Arctic Version

```
Arctic 1.26.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Windows , Python 2.7.12

#### Description of problem and/or code sample that reproduces the issue

`from arctic import Arctic`
`store = Arctic('LOCALHOST')`
`lib = store['library_main']`
`lib.set_quota(20 * 1024 * 1024 * 1024)`

When inserting data into arctic I got a "full quota warning" so tried to set my quota higher. However, I get "AttributeError: 'VersionStore' object has no attribute 'set_quota' " when trying to set quota. How should I set the quota then ? I'm pretty sure I did this before and it used to work.

**Comment by bmoscon** [comment]
you need to call it on store.

```
store.set_quota('library_main', 20 * 1024 * 1024 * 1024)
```
