### ISSUE TITLE
VersionStore write should preserve dataframe column type

### ISSUE THREAD

**Issue by AdrianTeng** [manahl/arctic#362]
#### Arctic Version

```
Latest master (1.43.0.dev1)
```

#### Arctic Store

```
# VersionStore
```

#### Description of problem and/or code sample that reproduces the issue
Writing to `VersionStore` doesn't preserve dataframe column type. A quick test to reproduce

```
def test_write_preserve_column_type():
    df1 = DataFrame(data=[1.0], index=[dt(2012,1,1)])
    library.write('TEST', df1)
    result = library.read('TEST').data
    assert_frame_equal(df1, result)
```

In particular:
```
>>> df1.columns
Int64Index([0], dtype='int64')
>>> out.columns
Index([u'0'], dtype='object')
```

**Comment by AdrianTeng** [comment]
(I'll attempt a fix)

**Comment by bmoscon** [comment]
@AdrianTeng I think this was intentional. See #113

**Comment by AdrianTeng** [comment]
@bmoscon  Thanks. This is a duplicate then.
