### ISSUE TITLE
How to deal with overlapping data ?

### ISSUE THREAD

**Issue by Frankkkkk** [manahl/arctic#366]
#### Arctic Version

```
git/master
```

#### Arctic Store

```
VersionStore
```

Hello,

I'm sorry if this sounds dumb but I've got a question: how to deal with overlaping data ? I receive data from meters and this data can be overlapping: first csv from 01/01 to 03/01, second csv from 02/01 to 04/01, etc.

In python3 if I try this:
```python
store = Arctic('172.21.0.7')
store.initialize_library('energy')
library = store['energy']

meter = '{}'.format(random.randint(1,99999))

names = ['meter_id', 'date', 'value', 'unit']
data1 = pd.read_csv('data1.csv', header=None, parse_dates=[1], names=names)
d1 = data1.set_index('date')

data2 = pd.read_csv('data2.csv', header=None, parse_dates=[1], names=names)
d2 = data2.set_index('date')


library.write(meter, d1['value'])
library.append(meter, d2['value'])
library.append(meter, d1['value'])


print('Type: {}'.format(type(d1['value'])))
print('First: {}'.format(len(d1)))
print('Second: {}'.format(len(d2)))
print('Total: {}'.format(len(library.read(meter).data)))
```
The result is:
```
Type: <class 'pandas.core.series.Series'>
First: 70
Second: 70
Total: 210
```
Whereas I would expect it to be 140.

How is it possible to do that effectively. I suppose I could, before every save, import all the data, append to the pandas array, and flush it back but it sounds rather expensive.

Is there a better solution that I have missed ?

Many thanks for your help and for the actual product ;-)

Cheers,
Frank

**Comment by richardbounds** [comment]
I think you want the `concat` flag on append, which @AdrianTeng is adding here: https://github.com/manahl/arctic/pull/363

**Comment by Frankkkkk** [comment]
Thanks for your reply !
This seems more or less like it. However it wouldn't work with:

- Adding data in the past.
- "incomplete overlap". Eg. Adding (3,5,6) to (1,2,4). Expected should be (1,3,4,5,6,7) instead of (1,2,4,5,6)

Thanks,

**Comment by richardbounds** [comment]
No, it wouldn't. To do that, you'd have to read the existing data back, merge your changes and write it back.

**Comment by bmoscon** [comment]
I think you can use ChunkStore for this. If you use the update method it will merge/update overlapping data.

**Comment by Frankkkkk** [comment]
Hi,

Sorry but I can't find an example on how to use a ChunkStore. Could you provide me with one please ?

Many thanks,

**Comment by Frankkkkk** [comment]
Perhaps a option **replace_index** like #363 (reverted in #373) could be added:
```python
def append(self, arctic_lib, version, symbol, item, previous_version, concat=False, replace_index=False **kwargs): 
```

So effectively, the serie:
```
1     10
2    234
5      0
```
appended with (concat=True, replace_index=True):
```
5     10
6     24
8    223
```
Would become:
```
1     10
2    234
5     10
6     24
8    223
```

What do you think ?

If I try to do that, is `arctic/store/_pandas_ndarray_store.py` the right place to do that ?

Thanks,

**Comment by bmoscon** [comment]
https://github.com/manahl/arctic/wiki/Chunkstore

**Comment by bmoscon** [comment]
@Frankkkkk did you look into chunkstore? Will it work for your use case?

**Comment by bmoscon** [comment]
havent heard anything back. since this is not a "bug" I'm going to close this. Feel free to re-open or open a new issue if you have more questions

**Comment by asvsfs** [comment]
I'm using tickstore to save trade data , and i have some overlapping data what would be the best solution to avoid the exception ?
