### ISSUE TITLE
Missing data triggers 2 different results: empty data frame and no data found exception

### ISSUE THREAD

**Issue by Cedric-De-Cesare** [manahl/arctic#367]
#### Arctic Version

```
1.43.0
```

#### Arctic Store

```
Tickstore
```

#### Platform and version

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

#### Description of problem and/or code sample that reproduces the issue

Hi,

I'm executing the read() method on 2 different libraries with 1 symbol and a date range as parameters (see below). I expect these 2 queries to return empty data frames but get 2 different results:
in one case I get an empty dataframe, in the otherI get a no data found exception.
Why do I get 2 different results depending on the library that is called?

I'm running the following code:

from arctic.date import DateRange
from arctic import Arctic
d = DateRange(start='2017-01-01', end='2017-01-02')

df1 = Arctic('BLABLA').get_library("BLIBLIBLI").read(symbol='1000', date_range=d)
df2 = Arctic('BLABLA').get_library("BLOBLOBLO").read(symbol='2013', date_range=d)

1) Arctic('BLABLA').get_library("BLIBLIBLI").read(symbol='1000', date_range=d)

returns an emplty data frame (0 rows)

2) Arctic('BLABLA').get_library("BLOBLOBLO").read(symbol='2013', date_range=d)

throws a no data found exception:

---------------------------------------------------------------------------
NoDataFoundException                      Traceback (most recent call last)
<ipython-input-53-2a375b27075c> in <module>()
----> 1 df = Arctic('10.0.1.20').get_library("BLABLABLA").read(symbol='2013', date_range=d)
      2 df.head()

/opt/anaconda3/envs/dev/lib/python3.5/site-packages/arctic/tickstore/tickstore.py in read(self, symbol, date_range, columns, include_images, allow_secondary, _target_tick_count)
    308 
    309         if not rtn:
--> 310             raise NoDataFoundException("No Data found for {} in range: {}".format(symbol, date_range))
    311         rtn = self._pad_and_fix_dtypes(rtn, column_dtypes)
    312 

NoDataFoundException: No Data found for 2013 in range: DateRange(start=datetime.datetime(2017, 1, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')), end=datetime.datetime(2017, 1, 2, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')))

Current investigation:

* When I check if the symbols exist for the libraries, I find that they indeed both exist:

Arctic('BLABLA').get_library("BLIBLIBLI").list_symbols() returns ['1000', '1009', '1013', '1020', ...]
Arctic('BLABLA').get_library("BLOBLOBLO").list_symbols() returns ['2013', '2014', '2015', '2016']

** When I expand the data range I find that both datasets BLIBLIBLI and BLABLABLA contain data.

Many thanks,
Cedric

**Comment by bmoscon** [comment]
I'm less familiar with tickstore's, but I'm pretty sure you're hitting two separate cases. One case you do a read against a symbol that exists, but has no data (which raises the exception). The other case is you're reading a symbol that has data, but no data for the specified date range, so you read out a dataframe and then subset it by date, yielding an empty dataframe.

**Comment by bmoscon** [comment]
does the above answer your questions? If not, let me know, otherwise I'll close this issue

**Comment by Cedric-De-Cesare** [comment]
Hi Bryant,
Sorry for not getting back to you sooner.
Yes thanks very much, you can close the issue.
Cedric
