### ISSUE TITLE
Broken version 1.43.1 on PyPI

### ISSUE THREAD

**Issue by mckelvin** [manahl/arctic#369]
There's a version `1.43.1`on [PyPI](https://pypi.python.org/pypi/arctic) but corresponding git tag can't be found on GitHub. What's worse, If you download [the whl file](https://pypi.python.org/packages/44/2f/419b4314bc7387034fa51af38b77f83f44a4000b4783343b1061e5498801/arctic-1.43.1-cp27-cp27mu-manylinux1_x86_64.whl#md5=43423777bf070a6752cc67882504a92f) and `unzip` it. You'll find it's actually `1.43.0`. (There's a file named `arctic-1.43.0.dist-info/metadata.json`)

Would you please drop the dirty version `1.43.0`,`1.43.1`, and release a dummy version with tag `1.43.2` and make sure all files(`.tar.gz`, `.whl`, `.egg`) listed on [PyPI](https://pypi.python.org/pypi/arctic) are upgrade to `1.43.2`?

**Comment by bmoscon** [comment]
yep. made a mistake on a version number and pypi wont let you fix it. had no choice but to up the 3rd version number so i could upload something. Once 1.44 comes out, I'll be able to upload a wheel with a filename that correctly matches the version number. the wheel for 1.43.0 may have a bad filename, but its the correct wheel.

**Comment by bmoscon** [comment]
new version was released so im closing this.
