### ISSUE TITLE
Overhead: Add EOD(daily ohlcv) every day

### ISSUE THREAD

**Issue by buhbuhtig** [manahl/arctic#370]
#### Arctic Version: 1.44
I try to use Arctic (Versionstore) for end-of-day stock quotes database. I notice the huge overhead incurred in appending (library.append) every new EOD OHLCV record per each ticker
For every new small EOD record (5 doubles+DateTime) that is added to the ArcticDb,  new version record (_id, growing chunk index array, metadata...sha) and new data record (_id,symbol,data, compressed, ... parents) should be created within MongoDB. It's too much.
Is it possible to update\append last data chunk(segment) in Versionstore **without versioning**?

Deleting latest version via API only increases the problem: subsequent append will force ArcticDb to (re-)create new large "aggredated\concatenated" base version (arcticdb does not remove last chunk\segment even with 'do_cleanup=True' option as well as it does not decrease version_num counter for subsequent 'smooth' append).

Best regards,
Vladimir

PS I use Narctic .NET\C# library (alpha, probably abandoned) and native ArcticDB codebase at the same time. Do you have a plan for .NET version?

**Comment by bmoscon** [comment]
Have you tried tickstore? It sounds like its a lot better suited to what you are doing that version store. 

In regards to .NET I don't think anyone is planning on doing it. I dont think many of the developers are using Windows or .NET. @jamesblackburn could probably comment further.

**Comment by richardbounds** [comment]
Yes there is some overhead but VersionStore should be ok for this - we use it for appending 1-minute ohlcv bars in a similar way. VersionStore keeps track of the number/size of appends for each symbol. Once it crosses a threshold, it re-compresses the appended data on the next write and writes it back, so the tiny appended chunks don't persist forever. You don't need to delete the previous versions, that should be handled automatically. 

Don't use TickStore, it isn't designed to support 1-row appends.

**Comment by buhbuhtig** [comment]
>  it re-compresses the appended data on the next write and writes it back, so the tiny appended chunks don't persist forever

Thank your for your insightful answer

**Comment by bmoscon** [comment]
hes right. I think the threshold is something around 60 appends

**Comment by bmoscon** [comment]
@buhbuhtig does this answer your question? Are we ok to close this issue?

**Comment by buhbuhtig** [comment]
Thx!
