### ISSUE TITLE
unable to execute 'g++-6': No such file or directory

### ISSUE THREAD

**Issue by sumantmann** [manahl/arctic#378]
#### Arctic Version

```
1.48.0
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version
Python3, Mac os Sierra

#### Description of problem and/or code sample that reproduces the issue

Unable to install arctic on my mac. It shows these errors

  g++-6 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-common -fno-strict-aliasing -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -g -fwrapv -Os -I/Users/sumant/Desktop/projects/sklearn/venv_3/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c src/_compress.c -o build/temp.macosx-10.6-intel-3.5/src/_compress.o -fopenmp -fpermissive
    unable to execute 'g++-6': No such file or directory
    error: command 'g++-6' failed with exit status 1

Command "/Users/sumant/Desktop/projects/sklearn/venv_3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_g/xm0w99v5701f_yp3g9v59b800000gn/T/pip-build-54i7_0i8/arctic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_g/xm0w99v5701f_yp3g9v59b800000gn/T/pip-w70q2d7j-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sumant/Desktop/projects/sklearn/venv_3/include/site/python3.5/arctic" failed with error code 1 in /private/var/folders/_g/xm0w99v5701f_yp3g9v59b800000gn/T/pip-build-54i7_0i8/arctic/

**Comment by bmoscon** [comment]
I assume then that you do not have g++ installed. Can you install it with homebrew? 

`brew install gcc --without-multilib`

**Comment by bmoscon** [comment]
also, you can install a wheel from pypi with pip:

`pip install arctic`

there are wheels for macOS on there, so you wont need to build it
