### ISSUE TITLE
Saving a panda DataFrame with objects will throw Unsupported datatype exception.

### ISSUE THREAD

**Issue by arturomichel** [manahl/arctic#379]
#### Arctic Version

```
1.43
```

#### Arctic Store

```
TickStore
```

#### Platform and version

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

#### Description of problem and/or code sample that reproduces the issue

The problem is that numpy supports unicode types [numpy dtypes](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.dtypes.html).  I suppose if you save data to tickstore in a more native format (dict or arrays) this works. 
However, when you have your data in a pandas DataFrame, unicode columns are converted to object type. 
dataframe['column'].dtype.kind == 'O'
line 595 in tickstore.py will note be triggered.
```
elif (dtype.kind) == 'U':
```
then in line 607, the check for supported type only checks for unicodes and strings (both supported by numpy but converted to objects in pandas. 
```
elif (array.dtype.kind) in ('U', 'S'):
```
If I try 
```df['SYMBOL'] = df['SYMBOL'].astype(np.unicode)```
or
```df['SYMBOL'] = df['SYMBOL'].astype(np.string_)```
the data frame defaults to 'object' type
```
>>>df.dtype
>>>SYMBOL                           object
```
Shouldn't the check in line 595 be similar to 607 ```elif (array.dtype.kind) in ('U', 'S'):``` and include both unicode and string types? 
And, how should the pandas dataframe issue be handled? Maybe a check for the type of the object being saved and have some dataframe-specific logic to handle columns of type 'O'.

I implemented ```(dtype.kind) in ('U', 'S', 'O'):``` in both cases. I can't see any unintended consequences so far. What your reckon? 

Cheers!

**Comment by bmoscon** [comment]
there is already a PR for this: https://github.com/manahl/arctic/pull/215

and a ticket: https://github.com/manahl/arctic/issues/206

**Comment by bmoscon** [comment]
feel free to open another PR, but going to close this since already a ticket open
