### ISSUE TITLE
How to use arctic.date.DateRange to query for range data

### ISSUE THREAD

**Issue by maroon2012** [manahl/arctic#387]
Hi,
     I am running the example program https://github.com/manahl/arctic/blob/master/howtos/201507_demo_pydata.py and have modified it to read data from csv file (code snippet below)

I am able to read back the complete data from mongodb and print it.

However when I specify a DateRange as a parameter to read there is no change and it prints all the rows back.

Please let me know what if I am using the DateRange object correctly.

The complete code is below.

def arctic_demo():
    print("Listing Libraries...")
    print(arctic.list_libraries())

    # Create a VersionStore library
    arctic.delete_library('jblackburn.stocks')
    arctic.initialize_library('jblackburn.stocks')

    print("Listing Libraries...")
    print(arctic.list_libraries())

    stocks = arctic['jblackburn.stocks']

    # get some prices
    df = pd.read_csv('/home/marco/tmp/min.csv')

    # store them in the library
    stocks.write('ABC', df)
    print ("Data")
    print (stocks.read('ABC').data)
    dd = DateRange(start="2017-07-03T09:15:00+0530", end="2017-07-03T09:29:00+0530")
    print ("Reading back...")
    print (stocks.read('ABC', date_range=dd).data)
    print (dd)

Input data in CSV file below
1453.7,2017-07-03T09:15:00+0530,1453.7,1453.7,1453.7,11
1450.6,2017-07-03T09:16:00+0530,1453.7,1450.6,1453.7,148
1452.8,2017-07-03T09:17:00+0530,1452.8,1450.6,1450.6,70
1452.8,2017-07-03T09:18:00+0530,1452.8,1452.8,1452.8,19
1452.0,2017-07-03T09:19:00+0530,1453.2,1452.0,1452.8,38
1452.0,2017-07-03T09:20:00+0530,1452.0,1452.0,1452.0,19
1452.0,2017-07-03T09:21:00+0530,1452.0,1452.0,1452.0,0
1453.7,2017-07-03T09:22:00+0530,1453.7,1452.0,1453.2,219
1455.0,2017-07-03T09:23:00+0530,1455.0,1453.15,1453.7,18
1455.0,2017-07-03T09:24:00+0530,1455.0,1455.0,1455.0,0
1455.0,2017-07-03T09:25:00+0530,1455.0,1455.0,1455.0,31
1455.05,2017-07-03T09:26:00+0530,1457.0,1455.0,1455.0,12
1456.95,2017-07-03T09:27:00+0530,1456.95,1455.05,1455.05,4
1456.95,2017-07-03T09:28:00+0530,1456.95,1456.95,1456.95,0
1457.0,2017-07-03T09:29:00+0530,1457.0,1455.05,1455.05,7
1457.95,2017-07-03T09:30:00+0530,1457.95,1455.45,1455.45,20
1458.85,2017-07-03T09:31:00+0530,1458.85,1457.95,1457.95,10
1458.85,2017-07-03T09:32:00+0530,1458.85,1458.85,1458.85,0
1457.25,2017-07-03T09:33:00+0530,1458.85,1457.25,1458.85,226
1457.25,2017-07-03T09:34:00+0530,1457.25,1457.25,1457.25,0
1458.5,2017-07-03T09:35:00+0530,1458.5,1458.5,1458.5,14
1458.05,2017-07-03T09:36:00+0530,1459.0,1457.75,1457.75,40
1459.0,2017-07-03T09:37:00+0530,1459.0,1458.05,1458.05,29
1460.0,2017-07-03T09:38:00+0530,1461.1,1459.0,1459.0,63
1459.15,2017-07-03T09:39:00+0530,1460.0,1455.0,1460.0,148
1457.65,2017-07-03T09:40:00+0530,1459.15,1457.65,1459.15,6
1457.65,2017-07-03T09:41:00+0530,1457.65,1457.65,1457.65,0
1458.1,2017-07-03T09:42:00+0530,1458.1,1457.65,1457.65,1
1460.6,2017-07-03T09:43:00+0530,1461.0,1459.95,1459.95,216
1462.0,2017-07-03T09:44:00+0530,1462.0,1458.05,1460.6,58
1461.8,2017-07-03T09:45:00+0530,1462.0,1460.1,1462.0,21
1457.6,2017-07-03T09:46:00+0530,1461.8,1456.05,1461.8,213
1457.6,2017-07-03T09:47:00+0530,1457.6,1457.6,1457.6,0
1457.6,2017-07-03T09:48:00+0530,1457.6,1457.6,1457.6,0
1457.7,2017-07-03T09:49:00+0530,1459.75,1457.7,1459.75,34
1461.2,2017-07-03T09:50:00+0530,1461.2,1457.7,1457.7,39
1462.0,2017-07-03T09:51:00+0530,1462.0,1461.2,1461.2,236

**Comment by bmoscon** [comment]
The main issue is that reading from a CSV to generate a dataframe is very imprecise. Pandas doesnt know that the 2nd column is a datetime, it looks like a string to pandas, so it stores that column in the dataframe as a string object. 

Also, the datetime has to the part of the index of the dataframe for date range subsetting to work in version store. See https://github.com/manahl/arctic/blob/master/arctic/store/_pandas_ndarray_store.py#L90

**Comment by maroon2012** [comment]
Thanks. Its working now.
