### ISSUE TITLE
Correct way to use CHUNK_STORE?

### ISSUE THREAD

**Issue by chrism2671** [manahl/arctic#388]
I'm trying to save the data for futures contracts with Arctic.

For my Corn futures contracts, I have a dataframe with `Index = ['Contract', 'Date']`, where `Contract` is of type integer (e.g. 201712) and date is `np.datetime64`. I intend to do incremental updates, and read the whole thing back at once.

Issues:
- `DateChunker` doesn't like the multi-index and won't run. Fair enough.
- `PassthroughChunker` seems to update on '`Date`', not the joint index `['Contract', 'Date']`, meaning that my final dataset has only one of each date in it.

How do you recommend storing futures data in Arctic?

**Comment by bmoscon** [comment]
ChunkStore's DateChunker supports multiIindexes. The unit tests are full of test cases that involve multiindex. 

PassThrough is really a non chunker. It takes anything you give it and just writes it. You dont really get any update support with that. 


So, you can definitely use tickstore or version store for what you are doing. Chunkstore should work just fine too. What error do you get when you you use DateChunker?

**Comment by chrism2671** [comment]
So I got DateChunker to work; but when doing `library.update()`, it seems to ignore Contract in the `['Contract', 'date']` index, and removes all the date duplicates. Is that what I should expect?

**Comment by chrism2671** [comment]
I'm still playing with this. DateChunker seems to be working OK now; although performance is an issue.

Writing 120,000 rows with DateChunker takes around 1 minute, vs virtually instantaneous for VersionStore. Am I doing something wrong?

**Comment by bmoscon** [comment]
ChunkStore is very slow on the write, but very fast in reading back very specific date ranges. ChunkStore also lets you modify already written data, VersionStore does not. Check out the wiki for more detailed information:

https://github.com/manahl/arctic/wiki/Chunkstore

**Comment by chrism2671** [comment]
Thank you!
