### ISSUE TITLE
Arctic date handling issues

### ISSUE THREAD

**Issue by RayVR** [manahl/arctic#393]
#### Arctic Version

```
1.48
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Linux 

#### Description of problem and/or code sample that reproduces the issue

DateRange automatically assumes times are passed in local time (server time). This is counter to most conventions in python where tz-naive times are assumed to be UTC or they raise an error if a specific time zone is required for comparison. Additionally, this requires the user to worry about the time zone of the server or write a wrapper around the arctic date handling to hide this detail.

An additional issue is returning the time stamps localized to server time zone. This seems like an unintuitive choice. If arctic does not support storing time zones it should default to returning all time stamps in UTC or offer an option.

**Comment by bmoscon** [comment]
see #404 and #161 - do either of those solve your problem?

**Comment by bmoscon** [comment]
never heard back @RayVR, do the previously mentioned tickets address your specific issue?

**Comment by jamesblackburn** [comment]
> This is counter to most conventions in python where tz-naive times are assumed to be UTC 

I think Python does the exact opposite @RayVR. In Python, naive datetimes produced by datetime.now(), for example, are in the local machines timezone:
https://docs.python.org/2/library/datetime.html#datetime.datetime.now

And you need to use `utcnow()` or similar to get utc naive timestamps, which is much rarer.  

> Additionally, this requires the user to worry about the time zone of the server

If you care about this and would prefer UTC you can pass in a `DateRange` with `tzinfo` set to to whatever timezone you want.

For most users querying the API they will be thinking in terms of their local times at which they trade - i.e. from their POV.  The data as returned is presented in the user's local timezone too, non-naive, so is self-consistent.

> An additional issue is returning the time stamps localized to server time zone. This seems like an unintuitive choice

The data is all stored in UTC.  The arctic convention is the Python convention - naive timestamps are 'local'.  When we return data we attempt to be as unambiguous as possible, and changing the timezone on read is trivial.

We could have chosen to always treat naive timestamps as `UTC` but given the way Python works out the box this would have caused needless confusion to users driving the API.  The API supports passing in non-naive datetimes and should do the right thing for applications that want to be explicit.

**Comment by jamesblackburn** [comment]
Closing for now.  Please reopen if there are specific bugs in the API.
