### ISSUE TITLE
Enhancement request - multi-symbol reads

### ISSUE THREAD

**Issue by RichardWarfield** [manahl/arctic#394]
Great project.  We're looking into using VersionStore for EOD data where we have a large number of symbols stored and often need to retrieve series for some arbitrary fraction of those.  So for example, 5000 stored symbols where we often need to read 500 at a time.  

If I understand correctly, we currently need to query each symbol with a separate call to store.read() and thus a separate Mongo query. This isn't ideal from a performance perspective and I was wondering whether some sort of multi-symbol read function had been considered, which could use an $in query to fetch all the symbols in one query. If there isn't a good reason for NOT having this I could potentially work on incorporating it in VersionStore.

**Comment by bmoscon** [comment]
a symbol in arctic does not have to be the same as a stock symbol. Its just a name you've given to the data. You can store 5000 securities in a single data frame and write it as a single arctic symbol. 

That being said, I'm not sure if a multi symbol query is something we'd want or not, so I'll let @jamesblackburn  opine

**Comment by RichardWarfield** [comment]
I get that a symbol can contain multiple series.  But in our case there isn't really a natural way to group the series in data frames for efficient concurrent access, short of putting everything in one frame -- which while I haven't benchmarked it, seems inefficient and would make versioning and metadata awkward.

**Comment by bmoscon** [comment]
@RichardWarfield I'm going to get this done for you next week some time, so i'll tag you on the PR and you can tell me if its what you had in mind or not

**Comment by RichardWarfield** [comment]
Thanks!

**Comment by bmoscon** [comment]
done for chunkstore, ill do it for version store now

**Comment by bmoscon** [comment]
I'm going to open a new ticket for it though so i have something to link against that is different
