### ISSUE TITLE
Method deprecated in latest release of pymongo

### ISSUE THREAD

**Issue by kraphtuos** [manahl/arctic#397]
#### Arctic Version

```
1.49.0
```

#### Arctic Store

```
VersionStore and ChunkStore
```

#### Platform and version

```
pymongo==3.5.0
```

#### Description of problem and/or code sample that reproduces the issue

In the latest pymongo release v3.5.0, `initialize_unordered_bulk_op` method is deprecated.
This directly affects `ChunkStore` and `NdarrayStore`.
Other stores including `VersionStore` are also implicated.

A temporary solution is to pin `pymongo==3.4.0`.

**Comment by kraphtuos** [comment]
Aforementioned temporary solution is implemented.

**Comment by bmoscon** [comment]
resolved
