### ISSUE TITLE
Artic not on PyPi; Awkward to set as a dependency using setuptools. 

### ISSUE THREAD

**Issue by dag4202** [manahl/arctic#400]
Why is the recent version of artic not on PyPi? Placing artic as a dependency in setuptools is overly troublesome.

**Comment by dag4202** [comment]
#35 was closed, but the

**Comment by bmoscon** [comment]
will get the latest one uploaded.

**Comment by dag4202** [comment]
Pardon, accidentally closed the issue. Thank you

**Comment by bmoscon** [comment]
sure. obviously you can use 1.49, which only lacks 2 minor changes in 1.50
