### ISSUE TITLE
authentication without hook

### ISSUE THREAD

**Issue by FaGuoMa** [manahl/arctic#405]
#### Arctic Version

```
Fresh github install from master today
```

#### Arctic Store

```
Tickstore
```

#### Description of problem and/or code sample that reproduces the issue

```
store = Arctic('x.x.x.x')
store._adminDB.authenticate('user','passwd')
```
will fail. But
```
store = Arctic('x.x.x.x')
store.list_libraries()
```
list.libraries will fail, but then
```
store._adminDB.authenticate('user','passwd')
```
will work. 
Sorcery ?

**Comment by bmoscon** [comment]
How is mongo set up? I assume with a user/password? If so, you need to engage the auth hook to auth with the DB to allow execution of authenticated commands

**Comment by bmoscon** [comment]
also:
```
In [1]: from arctic import Arctic

In [2]: store = Arctic('127.0.0.1')

In [3]: store.list_libraries()
Out[3]: []

In [4]: store.initialize_library('bmoscon.test')

In [5]: store.list_libraries()
Out[5]: [u'bmoscon.test']
```


so I can clearly list libraries and create them without the auth hook.

**Comment by bmoscon** [comment]
I also think you can just use authenticate from arctic.auth:

```authenticate(db, user, password)```

**Comment by FaGuoMa** [comment]
Sorry I forgot to close this one, thanks a lot!
