### ISSUE TITLE
Using TickStore

### ISSUE THREAD

**Issue by jasonstrimpel** [manahl/arctic#406]
#### Arctic Version

```
1.52.0 (from github repo)
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Ubuntu 16.04LTS

#### Description of problem and/or code sample that reproduces the issue

This is more of a questions and likely due to a lack of understanding. I'm the consumer of a high-ish frequency price feed. My objects are coming off the queue and an converting them to a `dict` using `json.loads`.

They look something like is:
```
body = {
    u'AssetPair': u'ETHEUR',
    u'IsBuy': True,
    u'Price': 286.39382,
    u'Timestamp': u'2017-08-27T05:36:08.415Z'
}
```
I'm creating a `DataFrame` like this:

```
msg = json.loads(body)
df = pandas.DataFrame(msg, index=[0]).set_index('Timestamp')
df.index = pandas.to_datetime(df.index, utc=True)
```
My issue is how to form a proper `DataFrame` for writing into the `TickStore`. I know that the index has to be a dt-aware timestamp and the value an `int64` or `float64`.

Can you please provide some guidance how I can use the `TickStore` given my data structure?

**Comment by c2h2** [comment]
lack of document and example, this project is a waste of time, I chose cassandra.

**Comment by jasonstrimpel** [comment]
@c2h2 I disagree with that sentiment completely. I saw a demo of Arctic at the AHL offices in London and it's very powerful and used in production. Actually was able to spend 30 minutes with the source code and answered my own questions.

**Comment by c2h2** [comment]
@jasonstrimpel sorry about the impatience to skim through the code, can you please answer your own question? I am stuck with a similar problem and considering to use cassandra.

**Comment by bmoscon** [comment]
@jasonstrimpel sorry I didn't get to this in time to answer your questions. Glad you were able to figure it out. Its true, aside from the documentation for chunkstore in the wiki, there isnt much documentation. I usually refer people to the integration tests, as they exercise a ton of functionality and have many examples.

**Comment by jasonstrimpel** [comment]
@c2h2 my problem stemmed from having incorrect data types which MongoDB was complaining about. Arctic is just a standardized way to transport data to Mongo. @bmoscon had a great suggestion to take a look at the test suite which exercises a lot of features.
