### ISSUE TITLE
AttributeError: 'module' object has no attribute 'version'

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#41]
When trying to run the unit tests I encounter this error. 

 File "/home/bryant/Desktop/arctic/arctic/store/_version_store_utils.py", line 71, in <module>
    pickle_compat_load = _define_compat_pickle_load()
  File "/home/bryant/Desktop/arctic/arctic/store/_version_store_utils.py", line 66, in _define_compat_pickle_load
    if pd.version.version.startswith("0.14"):
AttributeError: 'module' object has no attribute 'version'

In an interpreter:

Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import pandas as pd
pd.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
pd.\_\_version\_\_
u'0.17.0'
 

Does arctic support version 0.17 of Pandas?

**Comment by llazzaro** [comment]
I fixed this changing that line with if pd.__version__.startswith("0.14"):

The fix is in my fork https://github.com/llazzaro/arctic/commit/f9019d13d156ad81dc47802b804393a27a311826#diff-2eeaed663bd0d25b7e608891384b7298
