### ISSUE TITLE
Nightly New Stock Prices

### ISSUE THREAD

**Issue by ACPK** [manahl/arctic#422]
Is there a call to download and save Quandl's bulk partial csv, so that we can update database every night?

**Comment by bmoscon** [comment]
I don't know and have never used Quandl. Since this isn't an arctic issue, I'm going to close this. Their documentation seems reasonable, but I didn't find the answer to your question on their site (I did only look for 5 minutes).

**Comment by ACPK** [comment]
@bmoscon - The readme discusses Quandl. Who did the readme?

**Comment by bmoscon** [comment]
you can see who last modified every line of the README here:

https://github.com/manahl/arctic/blame/master/README.md


It looks like two different people modified the sections that mention quandl. Its just an example, the data could come from anywhere.

**Comment by ACPK** [comment]
@bmoscon - Ok, because I don't see how someone could use Arctic in production as they'd have to resync EVERY ticker EVERY day. It would also not take into account corporate actions such as new listings, ticker changes, etc. that Quandl's batch / bulk API calls easily handle.

**Comment by bmoscon** [comment]
why would you resync them? If you record the ticks in real time from feeds there is no need to sync anything. Alternatively, you can also just add the data once at the end of the trading day, either way, you only need to write new data to existing symbols, you should need to update/delete anything, its just an append operation (as frequent or infrequent as you like).

**Comment by ACPK** [comment]
@bmoscon - Stock prices usually change on a daily basis. :)

**Comment by bmoscon** [comment]
how you update is up to you - once a day, in real time, every 10 minutes, whatever. Its a time series database, so you'd usually just append a new price with the appropriate date/timestamp, not go back and update a price. Arctic is designed to hold years and years of securities prices as timeseries. If you're interested in how AHL uses it, see this slide deck:

https://www.slideshare.net/JamesBlackburn1/2015-pydata-highperformance-iot-and-financial-data-storage-with-python-and-mongodb
