### ISSUE TITLE
Metadata for Tickstore

### ISSUE THREAD

**Issue by SnowWalkerJ** [manahl/arctic#425]
Hi, I see from the documents that metadata can be saved in a VersionStore. However, I'm using TickStore and now I can only save metadata of each symbol in a seperate mongo library, which is very inconvenient.

Is there a way to save metadata in a TickStore?

**Comment by bmoscon** [comment]
There is no way. What sorts of things are you looking to store? simple key: value type things (python dict)? Dataframes? Something else?

Also, what sort of granularity? One piece of metadata per symbol would be extremely easy to add. (that one piece could be as large or small as you want)

**Comment by SnowWalkerJ** [comment]
A python dict is good enough to store something like the creator, privilege, or the source of the data.

It should not be difficult to add this kind of things into mongodb. I just think it would be convenient if a metadata argument is added to the read/write methods.

**Comment by bmoscon** [comment]
fixed
