### ISSUE TITLE
Mongo Quota Exceeded. How do you raise the limit?

### ISSUE THREAD

**Issue by Zvezdin** [manahl/arctic#428]
#### Arctic Version

1.52.0

#### Arctic Store

ChunkStore

#### Platform and version

Python 3.6.2 x64, Arch linux

#### Description of problem and/or code sample that reproduces the issue

After saving a few million lines of dataframe rows in series, I tried to create a new symbol to store different data. This action raised QuotaExceededException and any action to append more rows to a current symbol, or create a new one, throws this exception: 
`arctic.exceptions.QuotaExceededException: Mongo Quota Exceeded: arctic.chunkstore 11.673 / 10 GB used`

I am unsure of what you mean by Quota. [Mongodb has a quota setting](https://stackoverflow.com/a/10001832), but this refers to maximum amount of files, not storage size.

I tried running a MongoDB instance with:

`mongod --quota --quotaFiles 100000 --dbpath /some/where`

But that didn't fix the issue.

What is this limit about and is there a way to raise this? Is this a bug or a feature?

**Comment by kraphtuos** [comment]
This is an arctic feature.
Refer to [`Arctic.set_quota`](https://github.com/manahl/arctic/blob/master/arctic/arctic.py#L273)
Alternatively, use `chunkstore._arctic_lib.set_quota` for your `chunkstore`

**Comment by Zvezdin** [comment]
Thank you! These methods fixed the problem.
Sorry for posting an issue on that, but I didn't find any documentation about this feature. Feel free to the issue it if you will.

**Comment by bmoscon** [comment]
I'll be updating the chunkstore wiki soon, so ill make sure this is included.

**Comment by nateGeorge** [comment]
I'm confused on how to go about and best practices for setting the chunkstore quota.  I found one example here, but haven't seen anything in the arctic docs yet that has cleared things up.

Do we set it once and it is permanently changed?  Can it be set in the config file (and where does this normally reside on linux if so?)? Does it need to be set every time we use arctic?  Thanks for the help.
