### ISSUE TITLE
is it possible to query chunkstore based on column value?

### ISSUE THREAD

**Issue by uriando** [manahl/arctic#430]

**Comment by bmoscon** [comment]
Not sure what you mean. Do you mean you want to read out a single column from chunkstore? If not then please tell me what you mean by querying based on column value.

**Comment by uriando** [comment]
hi @bmoscon 
what i want to do like is get the chunk not only based date-range but also other value in dataframe.

thanks

**Comment by bmoscon** [comment]
no, not possible. Mongo is a NOSQL store, and the data is compressed as well, so none of the inherent features of the data are visible without reading it all out.
