### ISSUE TITLE
Pip installation of arctic 1.5 hangs after full download on the official docker image for python:3.5.

### ISSUE THREAD

**Issue by kekkler** [manahl/arctic#434]
#### Arctic Version

```
1.51
```

#### Arctic Store

```
N/A
```

#### Platform and version

Windows 10 Professional, Docker for windows running on hyper-v, running on the python:3.5 image.

The result of running ```uname -r``` in the shell is: ```4.9.41-moby```.

#### Description of problem and/or code sample that reproduces the issue

Within the bash shell of the aforementioned docker container, pip install arctic 1.51. After the download completes, pip hangs indefinitely. 

This is not the case for arctic 1.49 (1.50 does not appear on PyPi). 

EDIT: provided additional platform information.

**Comment by bmoscon** [comment]
1.50 and 1.51 do not have windows wheels. I'll make sure 1.52 has a wheel built for windows.

**Comment by dag4202** [comment]
Thank you. Let me know if you require or desire some manual pip installation tests on the python:3.5-alpine and/or the python:3.5-jessie docker images.  I'll be using arctic 1.49 for now.

**Comment by bmoscon** [comment]
arctic (as of 1.68.0) is now pure python, so wheels are no longer necessary
