### ISSUE TITLE
library.delete doesn't seem to work

### ISSUE THREAD

**Issue by BarrancoC** [manahl/arctic#435]
#### Arctic Version 1.49

# TickStoreV3

#### Description of problem and/or code sample that reproduces the issue

Libraries seem to include a function delete that removes records with index between 2 extremes.
When I tried to use it, it seemed to not have any effect. 

Example:

data = pd.DataFrame([
    ('2017-07-28 23:59:59',40),
    ('2017-07-29 23:59:59',41),
    ('2017-07-30 23:59:59',42)
],columns=['timestamp','data'])
data.index = data['timestamp'].apply(lambda x: pd.Timestamp(x, tz=pytz.UTC))
data = data.drop(axis=1, labels=['timestamp'])

store.delete_library('user.test_library')
store.initialize_library('user.test_library', lib_type='TickStoreV3')
lib = store.get_library('user.test_library')
symbol=''
lib.write(symbol,data)

lib.delete(symbol, date_range=DateRange(start='2017-07-29 23:00:00', end='2017-07-30 00:59:59'))
lib.read(symbol, date_range=DateRange('2017-07-27', '2017-10-01'))

This code does not give any error, but the command "lib.delete" doesn't have any effect on lib.
Do you have any suggestion about how to make "lib.delete" work or if there are alternative functions?

**Comment by mckelvin** [comment]
I met this issue before. And here's why:

When you write the data into arctic library. Only one chunk is written and the date range of the chunk is `[min(data.index), max(data.index)]` (i.e.:, `[2017-07-28 23:59:59, 2017-07-30 23:59:59]`).

If you want to delete the chunk. **The date range you give to the `.delete` function must cover the date range completely**. For example, this one will work: `lib.delete(symbol, date_range=DateRange(start='2017-07-28 23:00:00', end='2017-07-31 00:59:59'))
`.

From my experience, I'd suggest writing / deleting the chunk with a week-aligned date range.

**Comment by BarrancoC** [comment]
Thank you @mckelvin 
the function indeed works with intervals that include the whole data set.
If there is no way to delete a specific time frame from a library, I don't understand why the function bother asking for a data_range.
Is there any other solution that does not involves the deletion of all data for a symbol?

**Comment by bmoscon** [comment]
It should work with subsets of the dataset, but the start/end dates you give must not be in the middle of a tick/chunk

**Comment by BarrancoC** [comment]
Thanks @bmoscon  this cold be the solution. 
Is there an easy way to figure out which chunks is each symbol divided into?

**Comment by bmoscon** [comment]
not that I'm aware of. You might have to query them all out to find the dates. If you always wrote data with the same granularity, you'd "know" what the chunks were.

**Comment by bmoscon** [comment]
@jamesblackburn

**Comment by jamesblackburn** [comment]
Yes the above is all correct.

They way we use this in TickStoreV3 is that we align the data to natural boundaries - e.g. day, month, year.  If we need to reload or repack data, for example, we can delete the existing data in a date range (specific month) before reloading.

Essentially it's up to the application doing the loading to ensure that the data is chunked at appropriate boundaries in TickStore.
