### ISSUE TITLE
pymongo.errors.CursorNotFound when iterating over and processing large data

### ISSUE THREAD

**Issue by Zvezdin** [manahl/arctic#439]
#### Arctic Version

1.54.0

#### Arctic Store

ChunkStore

#### Platform and version

Arch Linux x64, Python 3

#### Description of problem and/or code sample that reproduces the issue

I have a store and I'm storing three keys with chunk sizes 'M', 'W' and 'D' respectively. I have data in each key that spans from 2015 to current days. I am starting to iterate over the three keys at once and extracting 5 minute intervals from each key. When a key's currently loaded chunk doesn't contain the interval I'm trying to extract, I load the next chunk from that key. I'm using `ChunkStore.iterator()` to iterate.

However, at one point while iterating over my whole dataset, I get an `pymongo.errors.CursorNotFound: Cursor not found, cursor id: 19102652939` exception when I call `newChunkOfAKey = next(iteratorOfACertainKey)`. In previous iterations of the whole data, when the processing of the 5 minute intervals took significantly less time, the issue did not show up. I added an artificial wait to my processing and it throws the exception much earlier while iterating.

As my research goes, this has something to do with mongodb having time limit and if iterating over the data takes longer than that, the exception is thrown.

Full stack trace: https://pastebin.com/iKNQEGqc

Is there something that arctic can do to avoid this limit and issue? I don't have enough memory to load all data at once and process it later. If not, can I disable this limit and will arctic work fine with it disabled?

**Comment by bmoscon** [comment]
the issue here is that there are two cursors being used for iterators - one that returns date intervals, one that reads the data. if the 2nd one is taking along time, the fist one will time out. I can change the iterator to grab all the chunks before using the 2nd cursor (this was the old behavior).

**Comment by Zvezdin** [comment]
Hello. Sorry for asking, but Is there any progress on the issue?

**Comment by bmoscon** [comment]
its in PR. Should be merged over the weekend or first thing next week.

**Comment by bmoscon** [comment]
fixed

**Comment by thakur-isha** [comment]
Hi, I am using mongo 4.2 with python 3.8 and I am also getting CursorNotFound error. How could I resolve it? Any suggestions. 

Thanks in advance.

**Comment by shashank88** [comment]
Can you paste the stacktrace and is it reproducible?

**Comment by thakur-isha** [comment]
Hi @shashank88 : Thanks for your response. I resolved the issue by increasing cursor time in pymongo through db.runCommand({setParameter:1, cursorTimeoutMillis: 600000})
