### ISSUE TITLE
TickStore - Unsupported dtype 'datetime64[ns]' when providing a timezone

### ISSUE THREAD

**Issue by ben-watt-es** [manahl/arctic#443]
#### Arctic Version

```
1.54.0
```

#### Arctic Store

```
TickStore
```

#### Platform and version
macOS Sierra 10.12.1, python 3.6.1, pandas 0.20.3

#### Description of problem and/or code sample that reproduces the issue

I'm creating a pandas dataframe with a timestamp index created with this:
`datetime.datetime.fromtimestamp(int(values["UTM"]) / 1000, tz=mktz("UTC"))`
The original string value includes ns so is too long.

If I use this as an index, on write I get the following error:

```
  File "/usr/local/lib/python3.6/site-packages/arctic/tickstore/tickstore.py", line 548, in write
    buckets = self._pandas_to_buckets(data, symbol, initial_image)
  File "/usr/local/lib/python3.6/site-packages/arctic/tickstore/tickstore.py", line 564, in _pandas_to_buckets
    bucket, initial_image = TickStore._pandas_to_bucket(x[i:i + self._chunk_size], symbol, initial_image)
  File "/usr/local/lib/python3.6/site-packages/arctic/tickstore/tickstore.py", line 651, in _pandas_to_bucket
    array = TickStore._ensure_supported_dtypes(recs[col])
  File "/usr/local/lib/python3.6/site-packages/arctic/tickstore/tickstore.py", line 610, in _ensure_supported_dtypes
    raise UnhandledDtypeException("Unsupported dtype '%s' - only int64, float64 and U are supported" % array.dtype)
arctic.exceptions.UnhandledDtypeException: Unsupported dtype 'datetime64[ns]' - only int64, float64 and U are supported
```
I get the same error when using a pandas timestamp also.

If I do not include `tz=mktz("UTC")` when creating the timestamp, I instead get the following:
```
  File "/usr/local/lib/python3.6/site-packages/arctic/tickstore/tickstore.py", line 545, in write
    self._assert_nonoverlapping_data(symbol, to_dt(start), to_dt(end))
  File "/usr/local/lib/python3.6/site-packages/arctic/date/_util.py", line 107, in to_dt
    raise ValueError("Must specify a TimeZone on incoming data")
ValueError: Must specify a TimeZone on incoming data
```
The TickStore integration tests show datetime objects with timezones being used as pandas indices, so I'm not sure what I am doing wrong here.

**Comment by ben-watt-es** [comment]
It appears to work correctly when using `set_index` on the dataframe; I was previously constructing the dataframe with the `index=...` argument.

**Comment by gaussleescorpio** [comment]
I did not see the difference between using index=.... when creating pandas df and using set_index(). Could you please show more details? I tried set_index and still get the error. 

`import arctic as ac
import pandas as pd
import numpy as np
import pytz as tz


client = ac.Arctic("localhost")
client.initialize_library(library="test_tick_store", lib_type=ac.TICK_STORE)
handler = client["test_tick_store"]

index = pd.date_range("2000-01-01", "2018-02-01", freq="1min", tz="UTC")
data = pd.DataFrame(data=np.random.rand(index.shape[0], 1))
data["date"] = index
data.set_index("date", inplace=True)
print(data)
handler.write("test1", data)`
