### ISSUE TITLE
arctic import error (gcc/cpython)

### ISSUE THREAD

**Issue by suryabahubalendruni** [manahl/arctic#444]
#### Arctic Version

```
1.55.0
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

macOS Sierra 10.12.6
anaconda python3.6

#### Description of problem and/or code sample that reproduces the issue

I am having an error when importing arctic that I believe relates to my current gcc or cython build. I think I need to install gcc --without-multilib, but I am not entirely sure. I also think it is possible that the gcc version python is using is outdated.

Here is the full code output and error statement:

Suryas-MacBook-Pro:~ surya$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arctic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/__init__.py", line 3, in <module>
    from .arctic import Arctic, register_library_type
  File "/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/arctic.py", line 12, in <module>
    from .store import version_store, bson_store, metadata_store
  File "/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/store/version_store.py", line 15, in <module>
    from ._pickle_store import PickleStore
  File "/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/store/_pickle_store.py", line 7, in <module>
    from .._compression import decompress, compress_array
  File "/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/_compression.py", line 3, in <module>
    from . import _compress as clz4
ImportError: dlopen(/Users/surya/anaconda3/lib/python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/surya/anaconda3/lib/python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/surya/anaconda3/lib/python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so 

Here is my output for brew list --versions:
coreutils 8.28_1
gcc 7.2.0
gmp 6.1.2_1
isl 0.18
libmpc 1.0.3_1
mongodb 3.4.10
mpfr 3.1.6
openssl 1.0.2l
pkg-config 0.29.2

**Comment by bmoscon** [comment]
```
~/arctic/arctic$ otool -L _compress.so 
_compress.so:
	/usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
```

What do you get on the .so from arctic? I have the same version of gcc installed. I dont think the `--without-multilib` option works on gcc 7, but I could be wrong. I'm guessing you don't have the correct path to the OpenMP lib, or something else is wrong with your install of gcc. You might try compiling from source (clone arctic, then run `python setup.py install`) to see what errors it gives you, or if it works.

**Comment by suryabahubalendruni** [comment]
I am guessing that the location I should run that line you give is /Users/surya/anaconda3/lib/python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so.dSYM/Contents/Resources/DWARF. Assuming that is correct, this is the output I get:

Suryas-MacBook-Pro:DWARF surya$ otool -L _compress.cpython-36m-darwin.so
_compress.cpython-36m-darwin.so:

I don't get the filepath to libgomp.1.dylib when I run this line. It actually doesn't seem to output anything. 

When I compile from source, the build succeeds but outputs a few warnings:

/usr/local/bin/gcc-7 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-common -fno-strict-aliasing -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -g -fwrapv -Os -Isrc -I/Users/surya/anaconda3/include/python3.6m -c src/_compress.c -o build/temp.macosx-10.7-x86_64-3.6/src/_compress.o -fopenmp -fpermissive
cc1: warning: command line option '-fpermissive' is valid for C++/ObjC++ but not for C
In file included from src/_compress.c:510:0:
src/lz4.h:179:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStream();
 ^~~~
src/lz4.h:237:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStreamDecode();
 ^~~~
/usr/local/bin/gcc-7 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-common -fno-strict-aliasing -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -g -fwrapv -Os -Isrc -I/Users/surya/anaconda3/include/python3.6m -c src/lz4.c -o build/temp.macosx-10.7-x86_64-3.6/src/lz4.o -fopenmp -fpermissive
cc1: warning: command line option '-fpermissive' is valid for C++/ObjC++ but not for C
In file included from src/lz4.c:163:0:
src/lz4.h:179:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStream();
 ^~~~
src/lz4.h:237:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStreamDecode();
 ^~~~
src/lz4.c:687:7: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStream()
       ^~~~~~~~~~~~~~~~
src/lz4.c:1077:7: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStreamDecode()
       ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/bin/gcc-7 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-common -fno-strict-aliasing -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -g -fwrapv -Os -Isrc -I/Users/surya/anaconda3/include/python3.6m -c src/lz4hc.c -o build/temp.macosx-10.7-x86_64-3.6/src/lz4hc.o -fopenmp -fpermissive
cc1: warning: command line option '-fpermissive' is valid for C++/ObjC++ but not for C
In file included from src/lz4hc.c:142:0:
src/lz4.h:179:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStream();
 ^~~~
src/lz4.h:237:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void* LZ4_createStreamDecode();
 ^~~~
src/lz4hc.c:343:5: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 int LZ4_sizeofStreamStateHC()
     ^~~~~~~~~~~~~~~~~~~~~~~
src/lz4hc.c:845:5: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 int LZ4_sizeofStateHC() { return sizeof(LZ4HC_Data_Structure); }

When I try to import arctic again, this is the new error I am getting. It still seems to fail in the same place, but this time without a slightly different error output.

>>> import arctic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/surya/GitHub/arctic/arctic/__init__.py", line 3, in <module>
    from .arctic import Arctic, register_library_type
  File "/Users/surya/GitHub/arctic/arctic/arctic.py", line 12, in <module>
    from .store import version_store, bson_store, metadata_store
  File "/Users/surya/GitHub/arctic/arctic/store/version_store.py", line 15, in <module>
    from ._pickle_store import PickleStore
  File "/Users/surya/GitHub/arctic/arctic/store/_pickle_store.py", line 7, in <module>
    from .._compression import decompress, compress_array
  File "/Users/surya/GitHub/arctic/arctic/_compression.py", line 3, in <module>
    from . import _compress as clz4
ImportError: cannot import name '_compress'

**Comment by suryabahubalendruni** [comment]
I think you were right when you said that my OpenMP path is not correct. How should I go about linking the path correctly?

**Comment by bmoscon** [comment]
I'm not sure. I'm a linux developer, not an OSX developer so I don't think I really know enough to help you.

**Comment by suryabahubalendruni** [comment]
No worries, this is a good start for me. I think what you mentioned about my OpenMP lib not being connected was accurate, would you happen to know how to link it properly?

**Comment by bmoscon** [comment]
Not sure. You could try uninstalling gcc and installing with `brew install gcc --without-multilib`

**Comment by suryabahubalendruni** [comment]
I made a bit of progress with properly linking my gcc. 

Now, the output for "otool -L _compress.cpython-36m-darwin.so" is:
_compress.cpython-36m-darwin.so:
	/usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

This resolved the _GOMP_parallel error, but I am now experiencing some problems with relative imports in the package.

When I try to import arctic, this is the new error message I get:

>>> import arctic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python3.6/site-packages/arctic/arctic.py", line 7, in <module>
    from ._util import indent
ImportError: attempted relative import with no known parent package

Any ideas? All help would be appreciated.

**Comment by bmoscon** [comment]
it looks like the installation has been mucked up somehow. I've had things like this happen when I installed the wheel and then ran `setup.py develop`. I'd recommend recreating the virtual env / conda env and then build or install arctic. Alternatively, you can find all the references to arctic in site packages in the env

**Comment by bmoscon** [comment]
@suryabahubalendruni is this still an issue? I'm happy to help if you still have issues, but I dont think this is an issue with the library as much as it is an issue with your local installation. Feel free to reply here or send me an email if you need help still.

**Comment by mortendaehli** [comment]
@bmoscon I am having the same issue after doing a fresh install with OSX.
@suryabahubalendruni Did you figure this out? If so, could you please share the solution?

**Comment by bmoscon** [comment]
unfortunately i dont think i can really help. I've never had the issue. i recently got a new mac and all i did was install xcode, install homebrew, install gcc with homebrew and then install arctic - no issues

**Comment by suryabahubalendruni** [comment]
@mortendaehli 
Funnily enough, my problem actually got resolved after I updated to High Sierra. I don't know if that is anecdotal or if it will work for others. Regardless, I'd give that a shot. A side note, when you install try running `python setup.py install` instead of `pip install .` for more in-depth error messages. I can't help you much more than that unless I see the exact error you are getting. Could you post the output when you try installing?

Regardless of your exact error, here's a general checklist for troubleshooting that I went through:
- update xcode tools: `xcode-select --install`
- install gcc with homebrew: `homebrew install gcc` 
- make sure that when you use gcc, it is in fact actually gcc. on macs, clang is mapped to the gcc keyword. You'll have to fumble around with your bash_profile in order to have homebrew's directories come before your local bins, and make sure that the right keywords are being used. this makes sure the right gcc gets referenced. Here are the contents of my bash_profile for reference:

```
export CC=/usr/local/bin/gcc-7

export CXX=/usr/local/bin/g++-7

export CPP=/usr/local/bin/cpp-7

export LD=/usr/local/bin/gcc-7

alias c++='c++-7'

alias g++='g++-7'

alias gcc='gcc-7'

alias cpp='cpp-7'

alias ld='gcc-7'

alias cc='gcc-7'

export PATH="/usr/local/bin:/usr/local/sbin:/Users/surya/anaconda3/bin:/usr/bin:/usr/sbin:/bin:/sbin"
```

**Comment by suryabahubalendruni** [comment]
On second thought, you may be able to ignore the changes to your PATH. In the source code for installing, there is a hardcoded path to usr/local/bin. As long as your aliases are correct, that should suffice. Can't help too much beyond that until I see the exact error you're experiencing.

**Comment by bmoscon** [comment]
@mortendaehli there is a much easier way to get it working with clang. I'll be updating arctic over the weekend to add this functionality.

**Comment by mortendaehli** [comment]
Super, then I´ll try a clean install when that is ready. Thanks!

**Comment by bmoscon** [comment]
@mortendaehli https://github.com/manahl/arctic/pull/471

You can pull the branch and give it a whirl if you want. You have to install clang with homebrew: brew install llvm
