### ISSUE TITLE
Is it possible to read all data from a library?

### ISSUE THREAD

**Issue by aaron8tang** [manahl/arctic#447]
#### Arctic Version

```
1.54
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Windows 7

#### Description of problem and/or code sample that reproduces the issue

I put stock EOD data in a chunkstore, with symbol as the key. For now, I have to read data with symbol one by one. Is it possible to read all EOD data once?

Thanks.

**Comment by bmoscon** [comment]
`data = [lib.read(symbol) for symbol in lib.get_symbols()]`

I would argue you are organizing your data incorrectly. You should store all stock symbols in a single data frame (indexed by datetime and symbol) and store that in a single arctic symbol. The symbol would be `eod`.

**Comment by bmoscon** [comment]
@aaron8tang did the above answer your question?

**Comment by aaron8tang** [comment]
@bmoscon Sorry for later reply. It works for me, Thanks.
