### ISSUE TITLE
Context Manager

### ISSUE THREAD

**Issue by johnjihong** [manahl/arctic#448]
Can I please know if we have context manger in Arctic, e.g., drop connections or clear cache?

**Comment by bmoscon** [comment]
MongoDB automatically clears connections out every so often (I believe the default is 10 minutes or something like that). I'm not sure what you mean by "clearing the cache". I don't think there is really a need for a context manager in arctic.

**Comment by bmoscon** [comment]
@johnjihong feel free to explain what you are looking for, otherwise I'll close this.

**Comment by jamesblackburn** [comment]
Agreed @bmoscon - we don't have an explicit cache.
