### ISSUE TITLE
What is the correct way to store, update and query multiple stock symbols?

### ISSUE THREAD

**Issue by imaginary-unit** [manahl/arctic#449]
#### Arctic Version

1.55

#### Platform and version

Linux

#### Description of problem and/or code sample that reproduces the issue

Our use case is to store data for multiple stock contracts (with overlapping date ranges), be able to append / update the data for each contract individually, and to query all the data reasonably quickly. What have we tried:

1. Store all contracts in a single Arctic symbol (using ChunkStore) with the multi-index (symbol, date). This way we can't really get the update functionality to work. DateChunker doesn't seem to support update() for multi-index:
```python
  store = Arctic(mongo_host)
  store.initialize_library(library, lib_type=CHUNK_STORE)
  library = store[library]
  library.update(symbol, new_data, chunker=DateChunker(), upsert=True)
```
The above code will actually rewrite data for corresponding dates with the ones from new_data ignoring the 'symbol' level of the multi-index. So basically it doesn't allow date duplicates on update and this is the problem when we have overlapping date ranges for different contracts.

2. Store each contract in a separate Arctic symbol and merge them on read. No problems with update here, but in this case the query performance is an issue. Requesting multiple symbols one by one is very slow, so it doesn't fell like the correct way to organize the data with Arctic. We've also tries multi-symbol read for ChunkStore introduces in the recent Arctic versions and it makes things a bit faster, but not significantly.

So the question is, what is the correct way to organize and query the data with Arctic to get the behavior we need? I suppose these are very basic requirements, so we're likely just doing something wrong.

Thanks.

**Comment by bmoscon** [comment]
I assume you've seen this:

https://github.com/manahl/arctic/wiki/Chunkstore

It describes how update works, but it seems like you've already figured out a lot of that. `Update` replaces a `chunk`, so if you want to use updated, you need to make sure the dataframe you are updating with has all the data you want for that chunk/date range. 


You could also use versionstore, but it really only supports append operations. Its very fast for rewriting complete symbols/date ranges though so if you had a very large dataframe, you could modify it slightly and overwrite it with the new one very efficiently. Have you tried versionstore at all?

**Comment by imaginary-unit** [comment]
@bmoscon, thanks for the reply.

No, we didn't try VersionStore. But as I understand the algorithm you suggest is very similar for both ChunkStore and VersionStore: read data --> update locally --> write back. The difference is that for ChunkStore I can also specify a date_range to only read/write a subset of the data.

So basically there is no way to do an update just on the mongo side, like I would do in a SQL database with an update query?

**Comment by bmoscon** [comment]
arctic serializes the data frames and compresses them, so its not really possible to just update small sub sections of chunks without reading it all back out, deserializing it, updating it, and then rewriting it.

**Comment by imaginary-unit** [comment]
OK, got it. Thanks!

**Comment by bmoscon** [comment]
@imaginary-unit sure thing, let me know if you have more questions
