### ISSUE TITLE
Cannnot save dataframes with numpy ndarray

### ISSUE THREAD

**Issue by Zvezdin** [manahl/arctic#453]
#### Arctic Version

1.54.0

#### Arctic Store

ChunkStore

#### Platform and version

Arch Linux, Python 3.6

#### Description of problem and/or code sample that reproduces the issue

Can't save dataframes that include a numpy array:

```
>>> a = pd.DataFrame([{'date': dt(2017,5,10), 'a': 3, 'b' : np.ndarray((2,3))}]) 
>>> a
   a                                                  b       date
0  3  [[4.65710094002e-310, 3.80985826184e+180, 1.95... 2017-05-10
>>> ch.write('testKey', a)
Traceback (most recent call last):
  File ".../arctic/serialization/numpy_arrays.py", line 74, in _convert_types
    a = np.array([s.encode('ascii') for s in a])
  File ".../arctic/serialization/numpy_arrays.py", line 74, in <listcomp>
    a = np.array([s.encode('ascii') for s in a])
AttributeError: 'numpy.ndarray' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../arctic/chunkstore/chunkstore.py", line 351, in write
    data = self.serializer.serialize(record)
  File ".../arctic/serialization/numpy_arrays.py", line 176, in serialize
    ret = self.converter.docify(df)
  File ".../arctic/serialization/numpy_arrays.py", line 115, in docify
    raise e
  File ".../arctic/serialization/numpy_arrays.py", line 106, in docify
    arr, mask = self._convert_types(df[c].values)
  File ".../arctic/serialization/numpy_arrays.py", line 77, in _convert_types
    raise ValueError("Column of type 'mixed' cannot be converted to string")
ValueError: Column of type 'mixed' cannot be converted to string
```

Is there a way to get this fixed, please?

**Comment by Zvezdin** [comment]
I tried saving as a string using following workaround:
```
output = io.BytesIO()
np.savetxt(output, theFaultyArray)

x = output.getvalue()
x.decode() 
```
Yet this suffers from a lot of precision losses. `np.savez` on the other hand doesn't want to decode as `ASCII` or `UTF-8`

**Comment by bmoscon** [comment]
You can't store objects, other than strings, in the dataframes and serialize them. You can use version store to do this, but it uses pickle to store the data and it isnt as fast/efficient. why not break out the data in the numpy array and store it in the dataframe?

**Comment by Zvezdin** [comment]
I am saving multi dim arrays, which can be 2D, 3D or even 4D. Correct me if I'm wrong, but I haven't found a pretty way to do encode / decode such arrays via basic dataframes.

**Comment by bmoscon** [comment]
I don't think this is going to be possible. Once you have objects in a pandas dataframe its not really easy to distinguish what sort of object it is. We only support string objects so numpy arrays wont work.

**Comment by bmoscon** [comment]
Spoke too soon - looks like you can tell if its an ndarray by taking the type of `series.values`. If its an ndarray, you can take the  dtype of that and assuming its something like int64 or float64 you can call tostring() on it.
