### ISSUE TITLE
"Error decompressing" and "MemoryError" when updating chunkstore with large strings

### ISSUE THREAD

**Issue by Zvezdin** [manahl/arctic#454]
#### Arctic Version

`1.54.0`

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Python 3.6, Arch Linux s64

#### Description of problem and/or code sample that reproduces the issue

In a dataframe, if one of the columns of that dataframe contains strings of only the letter `a`, repeated ~1000-4000 times, saving that via ChunkStore sometimes leads to `Error decompressing` or `MemoryError`. I used strings of `aaaa....` to reproduce, but it seems to happen with any string contents with that length.

I'm saving large strings, because I'm pickling objects in order to save arrays inside a ChunkStore key. This is the only solution I found when dealing with #453 

It may not happen during initial write, but if this dataframe is updated with newer rows in the future, it can also throw an exception.

Please refer to the following stack traces I got: https://pastebin.com/KXkjqhu2

The errors are consistent. That is, using the same data, the exception is thrown at the same time each run.

**Comment by Zvezdin** [comment]
In the aforementioned setup, a third kind of exception can also be thrown, whist saving large strings: `ValueError: string size must be a multiple of element size`. Here's a full trace: https://pastebin.com/kmmpuq3z

I will try to provide sample code that reproduces the issue asap, but it is of certain difficulty, due to the very specific setup for the problem.

**Comment by bmoscon** [comment]
I've tried lots of combinations of different sizes of strings ('a' * 1000, 100000, 1000000, 200000, etc) and I've written this, updated it, added new rows, etc. Haven't seen any issues. I'll need a reproducible test case if I am to fix this.

**Comment by bmoscon** [comment]
tried again to fix this, wasnt able to reproduce it. closing this, but feel free to re-open if you are able to reliably reproduce this? (This time i tired very very long strings, but of random characters)
