### ISSUE TITLE
Missing data when storing dataframe with many columns

### ISSUE THREAD

**Issue by SnowWalkerJ** [manahl/arctic#456]
Arctic 1.51.0 TickStore Python 3.5/3.6

I have a dataframe containing stock prices, with columns as stock codes(about 3000 columns) and rows as datetime (daily, about 6000)
When I write it to database, it raises DocumentToolarge exception, so I adjust library._chunk_size to a much smaller size, like 500. It successes. But When I read from the database, only 500 records are returned.

How am I able to write and read large dataframes with TickStore?

**Comment by bmoscon** [comment]
3000 columns is a lot. The max document size in mongo is about 16MB, so you can't have updates bigger than that in Tickstore. Tickstore is not designed for large dataframes, its designed for ticks, i.e. very small, very frequent updates. You should consider using versionStore or chunkstore.

**Comment by jamesblackburn** [comment]
For daily stock data like thsi @SnowWalkerJ we use `VersionStore` not tickstore.  We use tickstore for data on the order of ~200 columns maximum.

**Comment by bmoscon** [comment]
closing this. if you still have issues please reopen
