### ISSUE TITLE
Improve the performance by mitigation of excessive re-authentication

### ISSUE THREAD

**Issue by dimosped** [manahl/arctic#464]
#### Arctic Version

```
1.55
```

#### Arctic Store

```
All stores (VersionStore, TickStore, or ChunkStore)
```

#### Description of problem and/or code sample that reproduces the issue

With a previous PR (https://github.com/manahl/arctic/pull/329/files) , almost any access to ArcticLibraryBinding would trigger a re-authentication.
This caused a significant performance drop, especially if the registered "_get_auth_hook" is a slow operation.

This change introduces a design where auth is triggered when:
  - arctic instance is created
  - arctic's reset() method is called
  - a new ArcticLibraryBinding instance is created.

**Comment by bmoscon** [comment]
fixed via #460
