### ISSUE TITLE
Feature Request: Add fast operations for write only metadata and restore symbol to a given version

### ISSUE THREAD

**Issue by dimosped** [manahl/arctic#465]
#### Arctic Version
```
1.55
```

#### Arctic Store

```
# VersionStore
```

#### Description of problem and/or code sample that reproduces the issue

Currently there is no easy way to update the metadata only for a symbol without reading/re-writing the data for the given symbol.

Also, the users have no option to restore a given symbol to a version, without reading/re-writing the data/metadata form the reference version.

We need the Arctric's VersionStore API to be extended to support those two operations, whose runtime must be constant, regardless of the data size.

**Comment by bmoscon** [comment]
@dimosped we can close this right?

**Comment by shashank88** [comment]
Closing this, feel free to reopen if needed.
