### ISSUE TITLE
Arctic Installation error in virtualenv

### ISSUE THREAD

**Issue by SystemRage** [manahl/arctic#480]
#### Arctic Version

```
1.56.0
```

#### Arctic Store

```
N/A
```

#### Platform and version

Linux Mint 18.0

#### Description of problem and/or code sample that reproduces the issue

(virtua) matt@Matt ~ $ pip3 install arctic
Collecting arctic
  Using cached arctic-1.56.0.tar.gz
Requirement already satisfied: cython in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: decorator in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: enum34 in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: mockextras in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: pandas in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: pymongo in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: python-dateutil in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: pytz in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: tzlocal in ./Matt/pyth/virtua/lib/python3.5/site-packages (from arctic)
Requirement already satisfied: numpy>=1.9.0 in ./Matt/pyth/virtua/lib/python3.5/site-packages (from pandas->arctic)
Requirement already satisfied: six>=1.5 in ./Matt/pyth/virtua/lib/python3.5/site-packages (from python-dateutil->arctic)
Building wheels for collected packages: arctic
  Running setup.py bdist_wheel for arctic ... error
  Complete output from command /home/matt/Matt/pyth/virtua/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4wc76m_f/arctic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp31081g3ypip-wheel- --python-tag cp35:
  running bdist_wheel
  Warning: Extension name 'arctic._compress' does not match fully qualified name '_compress' of 'src/_compress.pyx'
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/arctic
  copying arctic/_util.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/multi_index.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/decorators.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/auth.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/exceptions.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/hooks.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/arctic.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/_compression.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/hosts.py -> build/lib.linux-x86_64-3.5/arctic
  copying arctic/__init__.py -> build/lib.linux-x86_64-3.5/arctic
  creating build/lib.linux-x86_64-3.5/arctic/serialization
  copying arctic/serialization/numpy_arrays.py -> build/lib.linux-x86_64-3.5/arctic/serialization
  copying arctic/serialization/_serializer.py -> build/lib.linux-x86_64-3.5/arctic/serialization
  copying arctic/serialization/numpy_records.py -> build/lib.linux-x86_64-3.5/arctic/serialization
  copying arctic/serialization/__init__.py -> build/lib.linux-x86_64-3.5/arctic/serialization
  creating build/lib.linux-x86_64-3.5/arctic/tickstore
  copying arctic/tickstore/toplevel.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
  copying arctic/tickstore/tickstore.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
  copying arctic/tickstore/__init__.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
  creating build/lib.linux-x86_64-3.5/arctic/fixtures
  copying arctic/fixtures/arctic.py -> build/lib.linux-x86_64-3.5/arctic/fixtures
  copying arctic/fixtures/__init__.py -> build/lib.linux-x86_64-3.5/arctic/fixtures
  creating build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/_pickle_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/version_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/_ndarray_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/metadata_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/audit.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/bitemporal_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/bson_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/_pandas_ndarray_store.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/__init__.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/versioned_item.py -> build/lib.linux-x86_64-3.5/arctic/store
  copying arctic/store/_version_store_utils.py -> build/lib.linux-x86_64-3.5/arctic/store
  creating build/lib.linux-x86_64-3.5/arctic/chunkstore
  copying arctic/chunkstore/date_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
  copying arctic/chunkstore/passthrough_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
  copying arctic/chunkstore/__init__.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
  copying arctic/chunkstore/chunkstore.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
  copying arctic/chunkstore/_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
  creating build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/_daterange.py -> build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/_generalslice.py -> build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/_util.py -> build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/_mktz.py -> build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/_parse.py -> build/lib.linux-x86_64-3.5/arctic/date
  copying arctic/date/__init__.py -> build/lib.linux-x86_64-3.5/arctic/date
  creating build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_create_user.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_list_libraries.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_fsck.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_prune_versions.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/utils.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_copy_data.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_init_library.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_delete_library.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/__init__.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  copying arctic/scripts/arctic_enable_sharding.py -> build/lib.linux-x86_64-3.5/arctic/scripts
  creating build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
  copying arctic/chunkstore/tools/tools.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
  copying arctic/chunkstore/tools/__init__.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
  running build_ext
  building 'arctic._compress' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/usr/include/python3.5m -I/home/matt/Matt/pyth/virtua/include/python3.5m -c src/_compress.c -o build/temp.linux-x86_64-3.5/src/_compress.o -fopenmp -fpermissive
  cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
  src/_compress.c:32:20: fatal error: Python.h: File o directory non esistente
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for arctic
  Running setup.py clean for arctic
Failed to build arctic
Installing collected packages: arctic
  Running setup.py install for arctic ... error
    Complete output from command /home/matt/Matt/pyth/virtua/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4wc76m_f/arctic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bt6q0b2c-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/matt/Matt/pyth/virtua/include/site/python3.5/arctic:
    running install
    Warning: Extension name 'arctic._compress' does not match fully qualified name '_compress' of 'src/_compress.pyx'
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/arctic
    copying arctic/_util.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/multi_index.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/decorators.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/auth.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/exceptions.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/hooks.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/arctic.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/_compression.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/hosts.py -> build/lib.linux-x86_64-3.5/arctic
    copying arctic/__init__.py -> build/lib.linux-x86_64-3.5/arctic
    creating build/lib.linux-x86_64-3.5/arctic/serialization
    copying arctic/serialization/numpy_arrays.py -> build/lib.linux-x86_64-3.5/arctic/serialization
    copying arctic/serialization/_serializer.py -> build/lib.linux-x86_64-3.5/arctic/serialization
    copying arctic/serialization/numpy_records.py -> build/lib.linux-x86_64-3.5/arctic/serialization
    copying arctic/serialization/__init__.py -> build/lib.linux-x86_64-3.5/arctic/serialization
    creating build/lib.linux-x86_64-3.5/arctic/tickstore
    copying arctic/tickstore/toplevel.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
    copying arctic/tickstore/tickstore.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
    copying arctic/tickstore/__init__.py -> build/lib.linux-x86_64-3.5/arctic/tickstore
    creating build/lib.linux-x86_64-3.5/arctic/fixtures
    copying arctic/fixtures/arctic.py -> build/lib.linux-x86_64-3.5/arctic/fixtures
    copying arctic/fixtures/__init__.py -> build/lib.linux-x86_64-3.5/arctic/fixtures
    creating build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/_pickle_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/version_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/_ndarray_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/metadata_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/audit.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/bitemporal_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/bson_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/_pandas_ndarray_store.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/__init__.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/versioned_item.py -> build/lib.linux-x86_64-3.5/arctic/store
    copying arctic/store/_version_store_utils.py -> build/lib.linux-x86_64-3.5/arctic/store
    creating build/lib.linux-x86_64-3.5/arctic/chunkstore
    copying arctic/chunkstore/date_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
    copying arctic/chunkstore/passthrough_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
    copying arctic/chunkstore/__init__.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
    copying arctic/chunkstore/chunkstore.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
    copying arctic/chunkstore/_chunker.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore
    creating build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/_daterange.py -> build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/_generalslice.py -> build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/_util.py -> build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/_mktz.py -> build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/_parse.py -> build/lib.linux-x86_64-3.5/arctic/date
    copying arctic/date/__init__.py -> build/lib.linux-x86_64-3.5/arctic/date
    creating build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_create_user.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_list_libraries.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_fsck.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_prune_versions.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/utils.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_copy_data.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_init_library.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_delete_library.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/__init__.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    copying arctic/scripts/arctic_enable_sharding.py -> build/lib.linux-x86_64-3.5/arctic/scripts
    creating build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
    copying arctic/chunkstore/tools/tools.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
    copying arctic/chunkstore/tools/__init__.py -> build/lib.linux-x86_64-3.5/arctic/chunkstore/tools
    running build_ext
    building 'arctic._compress' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/usr/include/python3.5m -I/home/matt/Matt/pyth/virtua/include/python3.5m -c src/_compress.c -o build/temp.linux-x86_64-3.5/src/_compress.o -fopenmp -fpermissive
    cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
    src/_compress.c:32:20: fatal error: Python.h: File o directory non esistente
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/matt/Matt/pyth/virtua/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4wc76m_f/arctic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bt6q0b2c-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/matt/Matt/pyth/virtua/include/site/python3.5/arctic" failed with error code 1 in /tmp/pip-build-4wc76m_f/arctic/

**Comment by bmoscon** [comment]
You appear to not have the python development libraries installed. I believe the package name is something like `python-dev` or `python-devel`
