### ISSUE TITLE
Unexpected column order when data are collected from a library

### ISSUE THREAD

**Issue by BarrancoC** [manahl/arctic#481]
#### Arctic Version

```
# 1.49.0
```

#### Arctic Store

```
# TickStoreV3
```

#### Description of problem and/or code sample that reproduces the issue

When data are collected from an Arctic library columns seems to be arbitrarily rearranged.
An example can be seen here:

import pytz
data = {
    'id':[1], 
    'col01':[0.01], 'col02':[0.02], 'col03':[0.03], 'col04':[0.04], 'col05':[0.05],
    'col06':[0.06], 'col07':[0.07], 'col08':[0.08], 'col09':[0.09], 'col10':[0.1],
    'timestamp':[dt.datetime.now()]
}
data = pd.DataFrame(data=data)
data.index = data['timestamp'].apply(lambda x: pd.Timestamp(x, tz=pytz.UTC))
data = data.drop(axis=1, labels=['timestamp'])

store.delete_library('user.test_library')
store.initialize_library('user.test_library', lib_type='TickStoreV3')
lib = store.get_library('user.test_library')
symbol=''
lib.write(symbol,data)
df = lib.read('')

data.sample().T # correct order
df.sample().T # unexpected order

I would like to ask what is the criteria behind this sorting, so that it could be possible to know in advance the order of the columns when data are collected from a library.
Thanks a lot.

**Comment by bmoscon** [comment]
@jamesblackburn

**Comment by richardbounds** [comment]
I suspect calling `lib.read('', columns=['col1', col2', ...])` might do the trick.

**Comment by BarrancoC** [comment]
Indeed. But I'd like to know the criterion of the column order in output when columns=[...] is not used.

**Comment by jamesblackburn** [comment]
@BarrancoC undefined.

Python dictionaries become Mongo SON objects in tickstore so there are no guarantees on column ordering:

https://github.com/manahl/arctic/blob/master/arctic/tickstore/tickstore.py#L440
```
        column_set.update(doc[COLUMNS].keys())
```

Note that in general each bucket may not have data for every single column, so even if we did guarantee ordering, the column_set would be different between different chunks...

As @richardbounds says use the `columns=` parameter to guarantee a specific column order.
