### ISSUE TITLE
Pymongo ssl parameter

### ISSUE THREAD

**Issue by ben10he** [manahl/arctic#493]
#### Arctic Version

1.43.0

#### Arctic Store

VersionStore

#### Platform and version

Python 3.5.2

#### Description of problem and/or code sample that reproduces the issue

In pymongo, we have the option to set ssl = True while connect to Mongo Cluster that requires ssl connection. However, in Arctic class, I cannot find this option while initialise an Arctic object. Did I miss anything or we should add ssl parameter(s) into Arctic initialisation?

**Comment by bmoscon** [comment]
i cant see any reason why its not supported. We should add it

**Comment by aflag** [comment]
This is addressed in this PR: https://github.com/manahl/arctic/pull/552
