### ISSUE TITLE
GOMP_4.0 not found

### ISSUE THREAD

**Issue by alpinechicken** [manahl/arctic#495]
#### Arctic Version

# VersionStore
```

#### Platform and version

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
#### Description of problem and/or code sample that reproduces the issue

Arctic won't import:

>>from arctic import Arctic

ImportError: /ext/anaconda3/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/user/.local/lib/python3.5/site-packages/arctic/_compress.cpython-35m-x86_64-linux-gnu.so)

**Comment by bmoscon** [comment]
I actually just hit this very issue - in my case I was using the same repo with multiple virtualenvironments. I had built arctic in 3.6 but was trying to use it in 2.7. It did not like that. I'd suggest purging the repo and rebuilding

**Comment by alpinechicken** [comment]
I installed with pip3 with Anaconda. I just did it without Anaconda and it worked fine.

**Comment by bmoscon** [comment]
there is an arctic package in anaconda - its the same library, but its really outdated and its not maintained by AHL or any of the arctic maintainers. best best is to install from source or pypi

**Comment by bmoscon** [comment]
sounds like we can close this, right @alpinechicken ?

**Comment by alpinechicken** [comment]
Yes - thank you!
