### ISSUE TITLE
import _compress results in no suitable image found

### ISSUE THREAD

**Issue by cavnerj** [manahl/arctic#500]
#### Arctic Version

```
1.59.0
```

#### Arctic Store

```
from . import _compress as clz4
```

#### Platform and version

macOSx 10.11.6

#### Description of problem and/or code sample that reproduces the issue

when I run a simple import arctic, I get a problem where it gets hung on 

from . import _compress as clz4

The error it produces is:

```
ImportError: dlopen(python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so, 2): no suitable image found.  Did find: lib/python3.6/site-packages/arctic/_compress.cpython-36m-darwin.so: mach-o, but wrong architecture
```

From what I have found out through google searches of this type of error, it seems like this is caused by a 32 bit install of either python or the package in question, however my python seems to be fine in other cases. I have tried different types of versions of arctic but to no avail. I have a hunch this has something to do with my computer and is not an arctic issue, but I thought I would try asking here before I punt my computer.

Thanks for any suggestions

**Comment by bmoscon** [comment]
this is no longer an issue. Arctic is a pure python module now, it no longer builds a compression module.
