### ISSUE TITLE
TickStore throwing unhandled dtype

### ISSUE THREAD

**Issue by 4ndygu** [manahl/arctic#514]
#### Arctic Version

```
# Arctic version here
```
arctic 1.60.0
#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```
Tickstore
#### Platform and version

Python 3.5.2

#### Description of problem and/or code sample that reproduces the issue

Say I load a Dataframe into this Tickstore.
```
154         tz = ('US/Eastern')
155         current_time = datetime.datetime(2016,1,4, 1, 1, 1, 1,tz)
156 
157         for symbol in data_schema.keys():
158             print("writing")
159 
160             print(time_index)                                                                                                                                                            
161             data_frame = pd.DataFrame(data={'data': data_schema[symbol],
162                 'time': time_index}, index=[current_time])
163             library.write(symbol, data_frame)
```
The only thing I get back is:
```
    library.write(symbol, data_frame)
  File "......./tickstore.py", line 573, in write
    buckets = self._pandas_to_buckets(data, symbol, initial_image)
  File ".......tickstore.py", line 594, in _pandas_to_buckets
    bucket, initial_image = TickStore._pandas_to_bucket(x[i:i + self._chunk_size], symbol, initial_image)
  File "........tickstore.py", line 687, in _pandas_to_bucket
    array = TickStore._ensure_supported_dtypes(recs[col])
  File ".......tickstore.py", line 646, in _ensure_supported_dtypes
    raise UnhandledDtypeException("Unsupported dtype '%s' - only int64, float64 and U are supported" % array.dtype)
arctic.exceptions.UnhandledDtypeException: Unsupported dtype 'datetime64[ns]' - only int64, float64 and U are supported
```

**Comment by gaussleescorpio** [comment]
I also encountered the same problem. Any solutions? It seems there is no good tutorial for arctic library.

**Comment by bmoscon** [comment]
@gaussleescorpio see the documentation in: https://github.com/manahl/arctic/tree/master/docs

**Comment by bmoscon** [comment]
@4ndygu this is because tickstore does not support datetimes as a datatype except in the index. If you need them in there, convert them to unix timestamps or something else. As the error says, tickstore only supports integers, floats and strings. Nothing else.

**Comment by DennyZen** [comment]
@bmoscon got UnhandledDtypeException also. checked all types ..
<class 'str'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'float'>
float64 not ok?

**Comment by DennyZen** [comment]
@bmoscon sorry. i am fool.
it was NoneType also inside
