### ISSUE TITLE
Calling VersionStore append may replicate data

### ISSUE THREAD

**Issue by aflag** [manahl/arctic#517]
#### Arctic Version

```
1.61.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Python 2.7.11

#### Description of problem and/or code sample that reproduces the issue

When the connection to mongo is lost during the execution of VersionStore.append (eg. a host restarted or a primary stepped down) two versions be created and the latest version will have duplicated data.

That is caused by two issues:
- The find_versions step in _prune_previous_versions is not retried as expected.
- _prune_previous_versions is executed after the version is added to the versions collection

Due to the second issue, when the connection is lost and _prune_previous_versions raises an exception, the whole method is retried. However, since the version was already written, it is taken as the base on the next execution of the method, replicating the latest data.

Note that this issue will not happen if the parameter prune_previous_version is set to False in append.

**Comment by bmoscon** [comment]
@aflag has this been resolved?

**Comment by aflag** [comment]
Yes. Sorry, I forgot to close the issue.
