### ISSUE TITLE
VersionStore read performance

### ISSUE THREAD

**Issue by trendelkampschroer** [manahl/arctic#523]
#### Arctic Version

```
Latest git as of yesterday (2018-03-21), installed via 'pip install git+https://github.com/manahl/arctic.git'
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

macOS, High Sierra

#### Description of problem and/or code sample that reproduces the issue

First of all thanks a lot for developing this very useful library.

I am trying to understand best practices for Arctic, especially with regard to performance.

I am using the following code-snippet to benchmark arctics performance using a local instance of MongoDB . 

```python
import time
import numpy as np
import pandas as pd

from arctic import Arctic

if __name__ == "__main__":
    M = 10000
    N = 1000
    df = pd.DataFrame(np.random.rand(M, N), index=pd.date_range("1960-01-01", periods=M, freq="D"), columns=np.arange(N).astype(str))

    # Connect to Local MONGODB
    store = Arctic('localhost')
    store.initialize_library("test.random_series")
    library = store["test.random_series"]
    for col in df.columns:
         library.write(col, df[col])        
    
    store.initialize_library("test.random_df")
    library = store["test.random_df"]
    library.write("df", df)

    t0 = time.time()    
    library = store["test.random_series"]
    sequences = {}
    for symbol in library.list_symbols():
        sequences[symbol] = library.read(symbol).data
    df = pd.DataFrame(sequences)
    t = time.time() - t0    
    print("Time for reading %i sequences of length %i is %.3fs" %(df.shape[1], df.shape[0], t))

    t0 = time.time()
    library = store["test.random_df"]
    df = library.read("df").data
    t = time.time() - t0
    print("Time for reading DataFrame with shape (%i, %i) is %.3fs" %(df.shape[0], df.shape[1], t))
```

The output on my machine is 
```
Time for reading 1000 sequences of length 10000 is 1.771s
Time for reading DataFrame with shape (10000, 1000) is 1.050s
```
I want to know if these numbers seem reasonable ( I am reading from SSD) and whether there is something that I can do to further improve the performance of my read operations. I have seen that there is already an issue for multi-symbol reads for VersionStore (#413) but this has been open for a couple of months already.

Also, I was not able to determine the exact version of arctic I was using. It would be very helpful if it could be obtained via
```python
import actic
arctic.__version__
```

Thanks,
Benjamin

**Comment by jamesblackburn** [comment]
That said I think the performance numbers you posted don't look bad - 1000 symbol reads in < 2s ~ 2ms per DF which seems pretty good.

**Comment by bmoscon** [comment]
take a look at #582 

going to close this, but if you have more questions please re-open, open a new ticket, or email me directly!
