### ISSUE TITLE
Reading data from Tickstore db limit

### ISSUE THREAD

**Issue by akshay55** [manahl/arctic#524]
#### Arctic Version

```
1.62
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Windows
#### Description of problem and/or code sample that reproduces the issue

When i read a symbol data from Tickstore database it does not show the complete data even though my date_range=None , so i should get entire series.
library.read("symbol")

Also i checked using max_date the last index of the symbol, i could see the last index entry is greater than what i see while reading the symbol. Is there a limit to number of ticks which read fetches ?

**Comment by jeffneuen** [comment]
Could you please post your sample code? I had a similar issue, but setting a date range resolved it for me.

**Comment by jamesblackburn** [comment]
You need to pass a `date_range` in that isn't `None`.  By default it will only read a month of data if you don't specify what you want in TickStore - as the data can be very large indeed...
