### ISSUE TITLE
Compression requires GIL in prange

### ISSUE THREAD

**Issue by bashtage** [manahl/arctic#529]
#### Arctic Version

```
# 1.64 (Master)
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Any

#### Description of problem and/or code sample that reproduces the issue

`_compressarr` does not use `@cython.boundscheck(False)` and so some of the advantage of using prange may be lost;

This may be by design although I don't see why the GIL would be required here since there are no Python manipulations. 

![image](https://user-images.githubusercontent.com/5585221/38494031-4c4a7898-3bec-11e8-8800-66a335e53f82.png)

**Comment by jamesblackburn** [comment]
Very likely because we didn't know better :)

Would gratefully accept a PR with some benchmark showing the speedup.

**Comment by bmoscon** [comment]
that just looks like its saving the state of the gil and releasing if necessary, or am i missing something? The only block in there that is explicitly without the GIL is the `with nogil` block

**Comment by jamesblackburn** [comment]
Fixed in: pull/530
