### ISSUE TITLE
If the dtype for a symbol changes, but not the underlying data, then write may fail

### ISSUE THREAD

**Issue by aflag** [manahl/arctic#534]
#### Arctic Version

```
1.63
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Python 2.7

#### Description of problem and/or code sample that reproduces the issue

After migrating from arctic 1.25 to 1.63 we had issues when using multi index columns (but it would happen when upgrading to any version before 1.41). Previously, arctic would not support multi index columns, so it would just convert the column names into strings. In version 1.63 arctic started supporting multi index columns.

However, previous versions of arctic would not raise an exception when saving multi column data frames, but would instead silently convert the column names to strings. That is effectively a different dtype from what arctic saves now, even though the underlying data is exactly the same.

When doing a write the following code is evaluated:

```python
        if previous_version:
            if 'sha' in previous_version \
                    and self.checksum(item[:previous_version['up_to']]) == previous_version['sha']:
                # The first n rows are identical to the previous version, so just append.
                # Do a 'dirty' append (i.e. concat & start from a new base version) for safety
                self._do_append(collection, version, symbol, item[previous_version['up_to']:], previous_version, dirty_append=True)
                return
```

The checksum check will succeed even though the dtype is different. This will cause an append to happen instead of a write. If the data was writing with arctic 1.41 on that is not a problem, since it will never try to read the previous value and do a concatenation. However, before the implementation of dirty_write, a uncompressed chunk could have been created. Thus, executing _do_append with a uncompressed chunk will cause a read and concatenate to happen, which will raise `TypeError: invalid type promotion`.

The solution for this is to check the previous version. The check already existed in past, but it was removed. This issue has the discussion about it: https://github.com/manahl/arctic/issues/121. I think it's safe to add it back.

**Comment by shashank88** [comment]
This seems to be fixed and merged. Closing
