### ISSUE TITLE
Installation on mac fails: ValueError("You must install clang-6.0 or gcc/g++

### ISSUE THREAD

**Issue by SteffenNa** [manahl/arctic#537]
#### Arctic Version

```
latest (1.66)
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

MacOS High Sierra 10.13.4, conda 4.5.1, Python 3.6.5

#### Description of problem and/or code sample that reproduces the issue

pip install git+https://github.com/manahl/arctic.git
Collecting git+https://github.com/manahl/arctic.git
  Cloning https://github.com/manahl/arctic.git to /private/var/folders/37/pj3q445120nbrg_jd778320c0000gp/T/pip-zmoq6jbu-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/37/pj3q445120nbrg_jd778320c0000gp/T/pip-zmoq6jbu-build/setup.py", line 44, in <module>
        raise ValueError("You must install clang-6.0 or gcc/g++. You can install with homebrew: brew install gcc or brew install llvm")
    ValueError: You must install clang-6.0 or gcc/g++. You can install with homebrew: brew install gcc or brew install llvm
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/37/pj3q445120nbrg_jd778320c0000gp/T/pip-zmoq6jbu-build/

Both clang and gcc are installed. Any guidance how get it installed will be hugely appreciated.

**Comment by bmoscon** [comment]
the instructions are in the error message - use homebrew to install it: `brew install llvm`

Also, you can install from pypi and there are wheels on there for macOS

**Comment by SteffenNa** [comment]
I have llvm installed. conda install llvm. Not using homebrew.

**Comment by bmoscon** [comment]
then you cannt build from source. Please install the wheel from pypi

**Comment by SteffenNa** [comment]
ok will try. thanks so much!

**Comment by aflag** [comment]
pip install clang will just install python bindings to clang. I think the problem is that you need the actual compiler.

**Comment by SteffenNa** [comment]
i do have Xcode installed.

**Comment by bmoscon** [comment]
you need to install the versions of g++ or clang provided by homebrewk (which you can read more about here: https://brew.sh/
The versions that come with xcode do not support openMP and thus will not work. You can install arctic simply by running `pip install arctic`

**Comment by SteffenNa** [comment]
wow. that worked indeed. my conda was screwed. did a complete clean reinstall of conda earlier today and now pip install arctic worked. thanks soooo much for your patience and help. Much appreciated.
