### ISSUE TITLE
Update your project(s) building on CircleCI 1.0 with this configuration tool

### ISSUE THREAD

**Issue by jamesblackburn** [manahl/arctic#541]
We noticed that the projects listed below are building on CircleCI 1.0 without a configuration file.
https://circleci.com/gh/manahl/arctic 

As a result of sunsetting CircleCI 1.0 on August 31st, 2018, the project(s) listed above require action from your team in order to continue building on CircleCI.

CircleCI 2.0 delivers a number of improvements, but has changed our configuration approach to be more deterministic. However, CircleCI 2.0 does not support projects without a configuration file. This means that all projects will now need a .circleci/config.yml file to continue building. 

To create your configuration, you have two options:

Option 1: Manual setup:
If you prefer to create your configuration file yourself, see our documentation on configuring CircleCI 2.0 for your project.

Option 2: Generated setup:
Generate a CircleCI 2.0 configuration file based on the recent build history of your project using our configuration generator script. The tool should explicitly output a configuration similar to what our system was previously implicitly doing. While not always perfect, this will give you a starting point from which to optimize and customize to your build.

Once you’ve completed all the steps, you should see a new job in CircleCI on the `circleci-20-test` branch that runs the generated configuration. If you run into problems please submit a support ticket here.

Note: If you’ve already migrated any of the above projects to CircleCI 2.0, disregard this message and happy building!

Thanks,
The CircleCI Team

**Comment by shashank88** [comment]
This seems to be done already by@jamesblackburn , closing this.

**Comment by bmoscon** [comment]
actually we never fixed this, I just disabled circle ci (after consulting with james). Travis works fine and I dont think circle is really buying us much else
