### ISSUE TITLE
Publish arctic releases via conda-forge

### ISSUE THREAD

**Issue by jamesblackburn** [manahl/arctic#542]
Conda is increasingly used in the data science community.  Conda-forge provides build infrastructure for many project.  Aim to get arctic built automatically for conda:
https://conda-forge.org/#about

**Comment by trendelkampschroer** [comment]
Unfortunately this won't help much users who rely on the conda-ecosystem as the requirement resolution of conda relies on conda packages being available for all dependencies.

To mitigate this problem a conda package for arctic has been released by @birnbaum on conda-forge, cf. https://github.com/conda-forge/arctic-feedstock
