### ISSUE TITLE
Benchmarks need to be updated

### ISSUE THREAD

**Issue by bmoscon** [manahl/arctic#543]
A skeleton of benchmarks exists in the top level directory, `benchmarks`. There are some very basic examples and a readme (https://github.com/manahl/arctic/blob/master/benchmarks.md), but these should be expanded upon to include all the storage engines and some more involved use cases and examples (i.e. chunkstore with numerics only, vs chunkstore with strings, version store with pickled objects, etc).

**Comment by dimosped** [comment]
@bmoscon  this is a potential duplicate with #545 
Do you mind if I merge the two?

**Comment by bmoscon** [comment]
yes thats fine, I was just adding this in the hopes someone would take it up :)
