### ISSUE TITLE
If the new LZ4 implementation (frame) is significantly faster, update Arctic to use this.

### ISSUE THREAD

**Issue by dimosped** [manahl/arctic#557]
#### Arctic Version

1.65

#### Arctic Store

All stores which use compression

#### Description of problem and/or code sample that reproduces the issue

The new LZ4 library has a very fast implementation, significantly faster than Arctic's Cythonized LZ4.

Port the new LZ4 (non frame) to Arctic, to pickup the implementation improvements. This is to maintain compatibility with existing compressed data.

Port the new LZ4 (frame) compression in Arctic's cython. Note this is is amazingly fast even in single threaded mode. Even faster if ported and used in parallel with Cython.

Current experimentation suggests that when decompressing an lz4-frame blob using the old lz4 is not working. The opposite works, as lz4-frame is backwards compatible.compresing old lz4 and fast lz4 frame, don't seem to be binary compatible.

We need to verify this and if true, update Arctic to store in the version metadata the compression scheme used (old lz4 vs lz4 frame).

We want compressed segments with lz4-frame to be decompressable with older arctic versions.

**Comment by dimosped** [comment]
Initial tests suggest it is really really fast:

```
tests/integration/test_compress_integration.py::test_bench_compression_comparison[300-50000.0] 
LZ4 Test 300x len:50000.0
    Arctic Cython old LZ4 (single thread) 0.068944 s
    Arctic Cython old LZ4 (parallel) 0.073188 s
    Arctic Cython old LZ4 High Compression (single thread) 3.979464 s
    Arctic Cython old LZ4 High Comporession (parallel)0.718893 s
    New LZ4 (frame) 0.063885 s
    Arctic Cython new LZ4 Frame (single thread) 0.065019 s
    Arctic Cython new LZ4 Frame (parallel) 0.030622 s
PASSED
tests/integration/test_compress_integration.py::test_bench_compression_comparison[16-2000000.0] 
LZ4 Test 16x len:2000000.0
    Arctic Cython old LZ4 (single thread) 0.159633 s
    Arctic Cython old LZ4 (parallel) 0.071848 s
    Arctic Cython old LZ4 High Compression (single thread) 21.764785 s
    Arctic Cython old LZ4 High Comporession (parallel)2.967039 s
    New LZ4 (frame) 0.231165 s
    Arctic Cython new LZ4 Frame (single thread) 0.269024 s
    Arctic Cython new LZ4 Frame (parallel) 0.067139 s
PASSED
```

**Comment by bmoscon** [comment]
I was under the impression all LZ4 implementations were decompressable by all versions (i.e. they are all backwards compatible). Is this not true?

They even have a test for it: https://github.com/lz4/lz4/blob/dev/tests/test-lz4-versions.py

**Comment by dimosped** [comment]
Yes, same here, I am surprised.
This is quite interesting:
https://github.com/manahl/arctic/blob/new-lz4-experimentation/tests/integration/test_compress_integration.py#L104

Also, I don't see the two-fold improvement that @jamesblackburn  mentioned yesterday of current't Arctic's LZ4 (non HC) vs the new LZ4 frame.

**Comment by dimosped** [comment]
Keep in mind that the "Arctic Cython old LZ4" is not really the old/existing Arctic code.
I have updated/ported the latest/greatest:
https://github.com/python-lz4/python-lz4 

Yesterday James run with the the very old lz4 Arctic code (0.7.0) which might explain why we see similar numbers now.

**Comment by dimosped** [comment]
It seems that with the new LZ4, the decompression has improved.

**Comment by TomTaylorLondon** [comment]
Was the library upgraded in setup.py?

**Comment by TomTaylorLondon** [comment]
Sorry, I missed the change. I see lz4 added back into requirements. Am I
correct in thinking:
- The new lz4 releases the GIL, which is why python multithreading works?
- As the cython is gone, consumers who don't upgrade lz4 along with arctic
will see a degraded performance?

Cheers
Tom

**Comment by dimosped** [comment]
@TomTaylorLondon 

The benchmark figures suggested that the old Cython LZ4 code was not faster than then new python-lz4. Actually the latter with multithreading was faster 

Yes, it releases the GIL:
https://github.com/python-lz4/python-lz4/blob/master/lz4/block/_block.c#L231,L247

There is no need to add the python-lz4 library version in setup.py as our code is handling imports in a backwards compatible manner.

The new lz4 implementation  (0.9.1 or later) is faster in single threaded, vs the very old implementation we used to have. I believe that even older versions, i.e. 0.8.1 had support for multithreding/gil-release, so most users who use a recent arctic with a comparably recent lz4 should see no performance drop.

If you wish to fine-tune the compression parameters, I would suggest to run these benchmarks on your hardware:
https://github.com/manahl/arctic/tree/master/benchmarks/lz4_tuning
Keep always in mind that on a loaded server with long runqueues, using more parallelism will potentially rather decrease than improve performance.

If you use Tickstore or you use HighCompression, the gains from parallelism are more evident up to 8x threads. For non-HC even with 2x threads you should be good.
