### ISSUE TITLE
Multindexed Interval TimeSeries Dataframe .write advice 

### ISSUE THREAD

**Issue by risktechnet** [manahl/arctic#560]
#### Arctic Version

```
1.66.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Anaconda Python 3.6

#### Description of problem and/or code sample that reproduces the issue

I have time series for crypto currencies (5min, 15min, etc) that are stored in flat files (.csv) and used in Python as multindex Dataframe, the format in the flat files are as in the example attached.
[test.xlsx](https://github.com/manahl/arctic/files/1986973/test.xlsx)

I read those files in my python environment and use it as multiindexed (by time and ticker) rows dataframe, which has the format :
		
```
                                close	       high	        low	       open	       quoteVolume	       volume       	weightedAverage

date            ticker							
1/1/2018 0:00	USDT_BTC	13266.720000	13800.000000	13211.000000	13800.000000	541.401396	7.333345e+06	13545.117180
                USDT_ETH	722.900000	737.004538	721.429057	736.044359	1922.059490	1.401251e+06	729.036436
                USDT_LTC	215.110000	226.000000	214.919455	226.000000	1281.396694	2.816681e+05	219.813389
1/1/2018 2:00	USDT_BTC	13369.404990	13628.799580	13218.012870	13301.000000	444.093988	5.954596e+06	13408.413260
                USDT_ETH	728.367555	734.901353	718.407182	722.900000	1088.350324	7.927551e+05	728.400657
                USDT_LTC	219.000000	221.479733	215.200000	215.292565	746.526798	1.630454e+05	218.405326
```

I am testing transfer all flat files to Arctic and i was wondering what would be the optimal way to .write those flat files to the Mongod enviroment? As the flat file format, as the multindexed dataframe or any other way ?

**Comment by bmoscon** [comment]
in a dataframe definitely. There are different features for each of the stores, you might try versionstore to start with.

**Comment by risktechnet** [comment]
Great thanks i will try it out.

**Comment by risktechnet** [comment]
Sorry to bother again just one additional question.
I am importing 1 multindex df per period e.g. :
- 1MIN (for all tickets BTCUSD, ETHUSD, LTCUSD, ...)
- 5MIN (for all tickets BTCUSD, ETHUSD, LTCUSD, ...)
- ....
This approach has any advantage on importing 1 dataframe per ticket per interval e.g. :
- 1MIN for BTCUSD
- 1MIN for ETHUSD
- 1 MIN for LTCUSD 
- ....
