### ISSUE TITLE
VersionStore .load with Multiindex Parameters

### ISSUE THREAD

**Issue by risktechnet** [manahl/arctic#565]
#### Arctic Version

```
1.66.0
```

#### Arctic Store

```
VersionStore
```

#### Platform and version

Anaconda Python 3.6

#### Description of problem and/or code sample that reproduces the issue

I write a multiindex Dataframe to an arctic VersionStore db with the following format:

```
                                close	       high	        low	       open	       quoteVolume	       volume       	weightedAverage

date            ticker							
1/1/2018 0:00	USDT_BTC	13266.720000	13800.000000	13211.000000	13800.000000	541.401396	7.333345e+06	13545.117180
                USDT_ETH	722.900000	737.004538	721.429057	736.044359	1922.059490	1.401251e+06	729.036436
                USDT_LTC	215.110000	226.000000	214.919455	226.000000	1281.396694	2.816681e+05	219.813389
1/1/2018 2:00	USDT_BTC	13369.404990	13628.799580	13218.012870	13301.000000	444.093988	5.954596e+06	13408.413260
                USDT_ETH	728.367555	734.901353	718.407182	722.900000	1088.350324	7.927551e+05	728.400657
                USDT_LTC	219.000000	221.479733	215.200000	215.292565	746.526798	1.630454e+05	218.405326
...........................................
```

Is it possible to load a slice of the data using the library.load command ? For example how would i request the data for USDT_BTC between 01-01-2018 and 01-31-2018 ?

**Comment by bmoscon** [comment]
you can use the `date_range` keyword arg to limit by a date range:

https://github.com/manahl/arctic/blob/master/arctic/store/version_store.py#L310

(there are examples in the unit and integration tests).

**Comment by risktechnet** [comment]
I was able to use date_range to extract a date interval, but still wasn't able to do a date_range for a specific **ticker** . can you provide me guidance if this is possible and if so, an example code ?

**Comment by bmoscon** [comment]
there isnt. You'd need to either store different pairs in different arctic symbols, or subset after you read.

**Comment by risktechnet** [comment]
thanks for the feedback
