### ISSUE TITLE
100% server cpu usage on reading tickstore

### ISSUE THREAD

**Issue by rick-sanchez-c137** [manahl/arctic#573]
#### Arctic Version

```1.66
# Arctic version here
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Put here

#### Description of problem and/or code sample that reproduces the issue

Put Here

I have a few coroutines periodically pulling ticks, single pull cost 2 secs as I tested. averaged pulls per minutes is 15. Does it has something do with async?

**Comment by bmoscon** [comment]
Arctic does not use asyncio. 

What storage engine are you using? They have different advantages and caveats - for example chunkstore is slower on writes but faster on reads. What platform (linux, osx, etc). What version of mongodb? Also, please try the latest version from master (its not in pypi yet) as there have been performance upgrqdes

**Comment by rick-sanchez-c137** [comment]
Thanks Bryant, currently the only clue I found is the time resolution. The library I was having issue with is filled with arbitrary timestamps, resolution, from second to nano second.  It performs better  once I aggregated the data in a certain resolution.

Is it something with range query mechanism?

**Comment by bmoscon** [comment]
You need to aggregate data and write it in uniform size (in terms of time) with tickstore. Example, do not write data in real time, do write data in chunks of 2 seconds (or whatever).

**Comment by richardbounds** [comment]
Unless you have extremely high frequency data, you probably want to write in chunks of hours or days, rather than seconds.

**Comment by rick-sanchez-c137** [comment]
Thanks, the final resolution was an in-memory buffer for hot data.
pardon my ignorance 🤣
