### ISSUE TITLE
Add cache for list_libraries

### ISSUE THREAD

**Issue by jamesblackburn** [manahl/arctic#587]
#### Description of problem and/or code sample that reproduces the issue

List libraries is O(n) for number of libraries, so is slow for large numbers of databases and libraries, and over high latency links.  Provide a cache of the libraries in a top-level database to speed up initial connections.

**Comment by dimosped** [comment]
@jamesblackburn  reg the "high latency links", is the RTT "payed" multiple times during the qyery, (i.e. iterative), or this is simply for the TCP in order to transfer a large response?

**Comment by jamesblackburn** [comment]
For each db, it lists all the collections:

```
    @mongo_retry
    def list_libraries(self):
        """
        Returns
        -------
        list of Arctic library names
        """
        libs = []
        for db in self._conn.database_names():
            if db.startswith(self.DB_PREFIX + '_'):
                for coll in self._conn[db].collection_names():
                    if coll.endswith(self.METADATA_COLL):
                        libs.append(db[len(self.DB_PREFIX) + 1:] + "." + coll[:-1 * len(self.METADATA_COLL) - 1])
            elif db == self.DB_PREFIX:
                for coll in self._conn[db].collection_names():
                    if coll.endswith(self.METADATA_COLL):
                        libs.append(coll[:-1 * len(self.METADATA_COLL) - 1])
        return libs
```

**Comment by yschimke** [comment]
We are also discussing using this to avoid locking up when there are global locks on the database cc @dimosped @rob256

**Comment by shashank88** [comment]
Have something simple'ish working, just need to add some tests.
