### ISSUE TITLE
install blocks on macOS anaconda with virtualenv

### ISSUE THREAD

**Issue by SnowWalkerJ** [manahl/arctic#603]
#### Arctic Version

```
1.68.0
```

#### Platform and version

macOS + anaconda python3.6 + virtualenv

#### Description of problem and/or code sample that reproduces the issue

When I install arctic with `pip install arctic` or `python setup.py install` under virtualenv,
it just blocks, with no output at all. But without virtualenv, it succeeds.

**Comment by bmoscon** [comment]
I'll need much more information if I'm to look into this, since it works for me. I also notice you're using anaconda python + virtualenv? Or are you using conda?

**Comment by SnowWalkerJ** [comment]
I'm using anaconda python + virtualenv. What else do you need?
```
(env) /p/tmp ❯❯❯ virtualenv env
(env) /p/tmp ❯❯❯ source env/bins/activate.fish
(env) /p/tmp ❯❯❯ pip install arctic
Collecting arctic
  Downloading https://files.pythonhosted.org/packages/5e/f2/d08dd61d8ee6e172385237ac0c3e248cae654362e128186109c71baaff02/arctic-1.67.1.tar.gz (498kB)
    100% |████████████████████████████████| 501kB 1.6MB/s
(then it blocks)
```

**Comment by bmoscon** [comment]
it works for me so I don't know what to tell you. I'm guessing its building the packages, but i dont know - usually you get output from that. Can you try installing the "bigger" dependencies first and then install arctic? (cython, numpy, pandas, pymongo)?

**Comment by bmoscon** [comment]
also, you're using 1.67.1, not 1.68

**Comment by bmoscon** [comment]
if the above doesnt work, try this:

https://github.com/manahl/arctic/blob/master/docs/developing-conda-mac.md

**Comment by SnowWalkerJ** [comment]
After installing the dependencies, it worked.
Thank you!

**Comment by bmoscon** [comment]
Awesome!

**Comment by rtadewald** [comment]
Same for me here.
But this time, I'm using Ubuntu 18.04, and the issue happen when I tried to upgrade to artic 1.69.

**Comment by bmoscon** [comment]
arctic has a lot of dependencies that might need to be built on your machine - they can take a while, ot you can preinstall them. The big ones are pandas, numpy, lz4  and pymongo.
