### ISSUE TITLE
how to query versionstore metadata and get all resulting documents in one shot?

### ISSUE THREAD

**Issue by PabTorre** [manahl/arctic#609]
Hi guys, 

I'm working to use arctic to replace a relational db we use for market data.
  
For the most part I've been able to understand how to get things done, by looking at the howtos, and some of the conversations around previous issues/features discussed here. 
There's one particular dataset which has proven hard to fit into the version store. 

It is the DY1 dataset from Quandl. Which contains fundamental data for Chinese stocks. 
 
They deliver this data as ~1 million+ dataframes with {ticker}_{fundamental_field} as their name. 

As a requirement, I need to accommodate 2 types of users; the ones who need to look at all the fundamental data for 1 stock, and the ones who need to look at one fundamental for all stocks. 

On relational db's  I address this issue by dumping all these datasets in a table and then slicing to get all rows matching a ticker or all rows matching a fundamental_field.  
I've thought of a couple of suboptimal solutions, like having 2 libraries for the dataset, each one with documents labelled for one of the use cases. This approach however feels wrong since I'm basically duplicating all the data and that probably won't scale well. 

Also tried storing the the data in its "raw" format with a library which holds documents following quandl's naming convention. However this approach suffers from network io, both when writing each individual document from my ETL pipeline and when reading back to the clients.  
From what I've seen in mongo's documentation, I should be able to $query a list of all matching documents by querying the metadata, after adding ticker and fundamental_field to the metadata for each doc. But I can't seem to get arctic to download all the resulting documents in one shot. 

Is there a way to run such a query on the metadata and get back all the resulting documents in one shot? 

(Please excuse me if I'm thinking about this whole thing from my SQL bias and trying to do something that is obviously wrong. )

Cheers.

**Comment by bmoscon** [comment]
first take a look at the docs:

https://github.com/manahl/arctic/tree/master/docs

If I understood the usecase correctly, you have two types of "reads" - all data vs single symbol.

Do you always read all date ranges? i.e. if you have data from say 1980 to now, are you always reading 1980 for now for all stock or for the single symbol? 

assuming you are, the only thing i could think of would be to use chunkstore, since it lets you read out specific columns. You'd have to have the column names be symbol names, and then have the ohlc, etc as part of multiindex. Not sure how well that would or wouldnt work, but i believe it would address the use case. The alternative is to store every symbol separately. You could get them all with something like this (assuming you were storing the data as [symbol, datetimeindex] as the multiindex, [ohlc+] as the columns).

```
df = pd.DataFrame()
for symbol in library.list_symbols():
    df = pd.concat([df, library.read(symbol).data])
```

(note: I did not test that code)

**Comment by PabTorre** [comment]
I've been through the docs, they were very helpful in setting up my store for OHLCV data. 


But this one is a little different. 
Each document is rather small, a few hundred rows each. But there are lots of these small documents. Since the data is only updated quarterly it doesn't add to that many rows in any one data type. 
Each one matches 1 symbol and 1 type of data. 

for example let's say the collection has 2 symbols and 3 datatypes, its metadata would look something like this:

{symbol: AAPL, type: EPS}
{symbol: AAPL, type: Assets}
{symbol: AAPL, type: debt}
{symbol: MSFT, type: EPS}
{symbol: MSFT, type: Assets}
{symbol: MSFT, type: debt}

and each of these has a dataframe attached to it. 

What I would like to know is if it is possible to query the metadata and get something similar to the output of running these queries directly in mongo:

db.my_collection.find( { $query: {symbol: "MSFT" } } )
db.my_collection.find( { $query: {symbol: "EPS" } } )

or is this something that would need to be stiched together on the client after running each individual query? 

thanks again.

**Comment by PabTorre** [comment]
ok. 
cheers.

**Comment by bmoscon** [comment]
I'd think since its so small the symbols (arctic symbols) could be the type: EPS, Assets, etc and you could store all the tickers under those symbols.

**Comment by PabTorre** [comment]
yeah, ended up making 2 collections... one has tickers as keys the other has data types as keys :)
