### ISSUE TITLE
Decimal type

### ISSUE THREAD

**Issue by kothique** [manahl/arctic#615]
Is it possible to store data in Decimal type? If I try that, I get:
> arctic.exceptions.UnhandledDtypeException: Casting object column to string failed

**Comment by kothique** [comment]
I use TickStore. I worked around it by storing my decimals as strings, but I wonder if there is a better way.

**Comment by bmoscon** [comment]
I dont think so. I think decimal.Decimal just uses strings as well for the representation, but i could be wrong. Pandas/numpy only support specific types, so we're limited by that, unless you're using versionstore which will pickle objects in columns.

**Comment by kothique** [comment]
OK, thank you for your response
