### ISSUE TITLE
TickStore Vs ChunkStore for large amount of ticks

### ISSUE THREAD

**Issue by krywen** [manahl/arctic#623]
#### Arctic Version

```
1.68.0
```

#### Arctic Store

```
TickStore or ChunkStore
```

#### Platform and version

Pyhton 2.7

#### Description of problem and/or code sample that reproduces the issue

In our use case we collect and need to store about 2.5 millions ticks per day, but that can increase with market condition. 
Based on the documentation I understood that TickStore is optimised for writes and can store chunks of any size, while ChunkStore has a DateRange Chunker which split ticks into chunks day by day, and is optimised for reads. 
Both stores have to fetch at minimum 1 chunk of compresses data, so I suspect if I use TickStore with chunks of 1 day the read performances would be the same as using a ChunkStore with a DataRange Chunker; is that correct?

In my case 2.5 millions ticks might be too much to retrieve at once, or might even reach mongo limit on a single document size, so I think the only option is to use a TickStore with chunks smaller than 1 day. Alternatively, It is possible to use ChunkStore with a different chuncker which split in chunks of 1 hours or less?

Note: I would also prefer optimising reads, not writes. Is there a more obvious solution I am missing?

**Comment by bmoscon** [comment]
ChunkStore works with any pandas frequency string. Take a look at the docs for it. You can use D, Q, M, W, T, S, 6H, H, etc. So you do not have to do just one day. I'd probably break it down into something like 6H, but thats up to you. 

a 2.5m row dataframe is not that big and is not hard to retrieve in one go, but performance will depend on things like are there strings? how many? how many columns? etc. You can definitely chunk in smaller ranges with chunkstore, take a look at the chunkstore docs, or the pandas freq strings here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

Note you can combine them, so even though H is hourly, 2H, 3H, etc are all fine.

**Comment by bmoscon** [comment]
are you all set? Can I close this?
