### ISSUE TITLE
Querying multiple tickers at once?

### ISSUE THREAD

**Issue by hj1234** [manahl/arctic#626]
#### Arctic Version

```
1.65
```

#### Description of problem and/or code sample that reproduces the issue

Not a problem, just a query...

Is there a means of returning a joined table from version store for multiple tickers? 

At the moment I use the following (very) inelegant solution (where 'stocks' is a list of tickers in the version store):

```
count = 0
for s in stocks:
    s_series = library.read(s).data
    if count == 0:
        s_series = s_series .to_frame()
        s_series .columns = [s]
        big_table = s_series 
    else:
        s_series = s_series .to_frame()
        s_series .columns = [s]
        big_table = big_table.join(s_series, how='outer')
    count += 1

```

As an aside, thank you so much for making such an awesome utility open source!

**Comment by bmoscon** [comment]
Theres no way to do this via a mongo query if thats what you're asking.
