### ISSUE TITLE
enum34 should be used via enum-compat for python 3.6+ compatibility

### ISSUE THREAD

**Issue by fersarr** [manahl/arctic#628]
**enum34** (one of arctic's dependencies in [setup.py](https://github.com/manahl/arctic/blob/5ef7f322481fcee7a275e3b3708c6c3ecdab6304/setup.py#L83)) should be used via [enum-compat](https://pypi.org/project/enum-compat/0.0.2/) for **python 3.6+ compatibility**

Please see: https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

enum34 should not be installed anymore starting from python 3.6

**Comment by dimosped** [comment]
@fersarr  merged, will be out with the next release
