### ISSUE TITLE
Numpy serializer modifies the 'columns' parameter

### ISSUE THREAD

**Issue by bcbrock** [manahl/arctic#629]
#### Arctic Version

```
Master branch
```

#### Arctic Store

```
Chunkstore
```

#### Platform and version

Probably applies to all

#### Description of problem and/or code sample that reproduces the issue

Hi,

First, thank you for making this code available. Here is my issue:

The Numpy serializer modifies the value passed as the 'columns' keyword, which was causing my code to fail when I next used the list of column names. I assume this is an oversight, since one could inspect the returned DataFrame to see which other columns had been added to the returned data, and this behavior is not documented. 

numpy_arrays.py, lines 209-214:
```
        if columns:
            if index:
                columns.extend(meta[INDEX])
            if len(columns) > len(set(columns)):
                raise Exception("Duplicate columns specified, cannot de-serialize")
```

Making a copy of ```columns``` before modifying it fixes the problem for me.
```
        if columns:
            if index:
                columns = columns.copy()
                columns.extend(meta[INDEX])
            if len(columns) > len(set(columns)):
                raise Exception("Duplicate columns specified, cannot de-serialize")

```

**Comment by bmoscon** [comment]
ok, I'll fix that this weekend. thanks for the tip!

**Comment by bmoscon** [comment]
fixed

**Comment by bcbrock** [comment]
Thanks!
