### ISSUE TITLE
Floating point precision issue on read

### ISSUE THREAD

**Issue by krywen** [manahl/arctic#636]
#### Arctic Version

```
1.69.0
```

#### Arctic Store

```
TickStore
```

#### Platform and version

python 2.7.4, Ubuntu 14.04.5 LTS
arctic==1.68.0
numpy==1.13.1
lz4==2.1.0
pandas==0.19.2

#### Description of problem and/or code sample that reproduces the issue

When reading a DataFrame consisting of one list of floats, one of those floating point number is not the same as when it was written. Do the dataframe serialization/compression has data loss?

the following code write a list of floats `comp_data`, retrieves it, and compare the input with the output.
One element of this list is modified (1.45 becomes 1.44995117188)

Note that this code fails or do not fail based on the specific `comp_data` list of floats. 
The minimal example where this occurs has about 10.000 floats in it and can be found here https://github.com/krywen/arctic_precision/blob/master/data.py 
Removing some elements from that list hide the error, and do not reproduce the issue.

```
import pandas as pd
import pytz
from arctic import Arctic, TICK_STORE
from arctic.date import DateRange
from datetime import datetime, date, timedelta
import urllib2

mongo_client = ...

def get_data():
    url = 'https://raw.githubusercontent.com/krywen/arctic_precision/master/data.py'
    comp_data = eval(urllib2.urlopen(url).read().split('=')[1])
    return comp_data


def main():
    store = Arctic(mongo_client)
    lib_name = 'lib'
    lib_type = TICK_STORE
    symbol = 'APPLESTOCKS'

    current_range = DateRange(datetime(2010, 1, 1, tzinfo=pytz.utc),
                              datetime.combine(date(2010, 1, 1), datetime.max.time()).replace(tzinfo=pytz.utc))
    comp_data = get_data()
    print comp_data

    store.initialize_library(lib_name, lib_type=lib_type)
    library = store[lib_name]
    index = [datetime(2010, 1, 1, tzinfo=pytz.utc) + timedelta(milliseconds=i) for i in range(len(comp_data))]
    df = pd.DataFrame(data={'data': comp_data}, index=index)

    library.delete(symbol, date_range=current_range)
    library.write(symbol, df)
    read_df = library.read(symbol, date_range=current_range)

    input_list = df['data'].tolist()
    output_list = read_df['data'].tolist()
    if input_list != output_list:
        for i in range(len(df)):
            if input_list[i] != output_list[i]:
                raise ValueError("{} != {} : {}".format(input_list[i], output_list[i], i))


if __name__ == '__main__':
    main()


```
Can I have suggestion what to look at in the library to fix this?
[Edit]: a one click version of the code

**Comment by krywen** [comment]
The issue happened with arctic 1.68.0 but not with 1.67.1 . can #572 have introduced the problem? Might be a lz4 issue

**Comment by krywen** [comment]
Hi, we think this is caused by lz4 and opened an issue with them https://github.com/python-lz4/python-lz4/issues/150

**Comment by ajholyoake** [comment]
This can be fixed by bumping to lz4==2.1.1

**Comment by bmoscon** [comment]
sounds like we can close the issue then, no?

**Comment by ajholyoake** [comment]
Close away!

**Comment by krywen** [comment]
Should "tzlocal>=2.1.1" be added in setup.py ?
