### ISSUE TITLE
date util test fail when run from a Europe/London timezone

### ISSUE THREAD

**Issue by krywen** [manahl/arctic#638]
#### Arctic Version

```
1.69.0
```

#### Arctic Store

```
Any
```

#### Platform and version

Ubuntu 14.04.5 LTS, python 2.7.6

#### Description of problem and/or code sample that reproduces the issue

Test `tests/unit/date/test_util.py#test_datetime_to_ms_and_back()` fails when run from a machine located in the timezone `mktz('Europe/London')`

I've made a suggested fix here https://github.com/manahl/arctic/pull/637

**Comment by bmoscon** [comment]
this was merged, closing
