### ISSUE TITLE
unexpected chunks when using uneven frequencies

### ISSUE THREAD

**Issue by dnlwgnd** [manahl/arctic#639]
#### Arctic Version

```
# Arctic version 1.69
```

#### Arctic Store

```
# ChunkStore
```

#### Platform and version

Win, Python 3.7.0, pandas 0.23.4

#### Description of problem and/or code sample that reproduces the issue
Hi there,

I was testing the ChunkStore when I notices strange behaviour. I have a sample dateframe that hast data every 30s and I wanted to chunk that into 5-minute-chunks. 

```
from arctic.chunkstore.date_chunker import DateChunker
import arctic as at
import pandas.util.testing as pdt

if __name__ == '__main__':
    data = pdt.makeTimeDataFrame(nper=50, freq='30S')
    data.index.name = 'date'
    print(data.head(10))
    database = at.Arctic('localhost')
    database.initialize_library('ticks', lib_type=at.CHUNK_STORE)
    lib = database['ticks']
    lib.append('btcusdt', data, chunker=DateChunker(), chunk_size='5T', upsert=True)
```

It appears that it indeed created 5-minute chunks, but they are all overlapping by 4 minutes. Look at start and end times in each chunk (assuming that each chunk is a mongo document). 
![image](https://user-images.githubusercontent.com/35139788/47257151-88c53100-d48a-11e8-941d-94ea9f7bda99.png)

Now is this the expected behaviour or is there a bug?

**Comment by bmoscon** [comment]
If you could send me the sample data that generates this issue I can take a look. Definitely looks like a bug, but can't say for sure

**Comment by dnlwgnd** [comment]
the code I posted does create the complete sample data. I ran this on an completely empty mongo (i.e. deleted the arctic database before)

**Comment by bmoscon** [comment]
definitely not expected, issues seems to be with the behavior of `to_period` in pandas. Sometimes it does what I expect, some times it doesnt. It seems that it definitely does not work with an index with a frequency like your example creates. I can probably redo the date range endpoint creation with intervals, but not sure since that is a newer feature of pandas and the goal of arctic is to support older version of pandas

**Comment by bmoscon** [comment]
@dnlwgnd I have a fix in mind, I'll try and get it tested today and hopefully have a fix ready to be reviewed tomorrow or early next week

**Comment by dnlwgnd** [comment]
thanks so far for looking into it. I will be happy to test it.

**Comment by bmoscon** [comment]
I opened a bug against pandas, it looks like its giving 1M periods as opposed to the requested 5M period

https://github.com/pandas-dev/pandas/issues/23253

**Comment by bmoscon** [comment]
@dnlwgnd it does seem if you use single frequencies it works as expected - S,T, H, D, M, W, Q, Y, etc. For some reason once you go from T to 2T it breaks in pandas

**Comment by dnlwgnd** [comment]
@bmoscon yes I did suspect a pandas problem also and tried to step trough their code. however it is a bit to much of vodoo going on for my tast :-).
I will follow your pandas bug then.

**Comment by shashank88** [comment]
Closing this as there doesn't seem to be anything to do here.
