### ISSUE TITLE
ChunkStore Speed for 300MB per dataframe

### ISSUE THREAD

**Issue by dingding72** [manahl/arctic#640]
#### Arctic Version
```
1.70.0
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Windows Server 2008 R2
MongoDB on Amazon Linux AMI

#### Description of problem and/or code sample that reproduces the issue

Dear Arctic, I am experimenting with Arctic.  Using ChunkStore, each dataframe about 300 MB, one year of data, using 'M' as chunk_size, about 1000 dataframes in this ChunkStore library.  Took about 4 seconds to read the dataframe, is this normal or slow?  MongoDB on AWS E2 m5.large instance.  If I want to store about 100K dataframes in this ChunkStore Library, would I see performance degrading linearly? Thanks!

**Comment by bmoscon** [comment]
Is the data evenly distributed? i.e. if 300 MB is a years worth of data, is each month roughly 25MB of data? 

When you say it took 4 seconds to read the dataframe, do you mean the 300MB, 1 year DF? If so that seems reasonable to me, depending on the network and disk constraints.

**Comment by bmoscon** [comment]
you can take a look at the spreadsheet here for some rough benchmarks

https://github.com/manahl/arctic/issues/582

**Comment by bmoscon** [comment]
never heard back in response to my questions, closing
