### ISSUE TITLE
Arctic doesn't have library_exists method

### ISSUE THREAD

**Issue by dimosped** [manahl/arctic#660]
#### Arctic Version

```
1.72.0
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Description of problem and/or code sample that reproduces the issue

There is no "library_exists('my_library_name')"  method, which forces users to use the expensive:
'my_library_name' in a.list_libraries()

Instead use a lightweight "library_exists()" method (no regex support, just exact lib name match), which wraps get_library().

**Comment by bmoscon** [comment]
fixed
