### ISSUE TITLE
Codebase pep8 cleanups

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#670]
#### Arctic Version

```
Latest
```

#### Description of problem and/or code sample that reproduces the issue

Was going through the codebase and I spotted lots of small cleanups (mostly pep8 related - eg. Extra newlines, unused variables, import ordering) that can be fixed quickly. I have some changes in my fork that I can send for this?

**Comment by shashank88** [comment]
Also, in the same vein, any thoughts on using a pep8 check on merges + using black or some other auto-formatter?

**Comment by shashank88** [comment]
So I know the devs were using black for marge-bot, but they haven't committed in the black config. The pylint strict checks are here: https://github.com/smarkets/marge-bot/blob/master/pylintrc 

In my last placemost people set it to auto format in their editors, and the lint checker validates that.

**Comment by bmoscon** [comment]
as long as we aren't going with PEP8's horrible 80 column limit...

**Comment by shashank88** [comment]
I am used to 110 which seems like a good balance.

If @jamesblackburn is ok, we can either decide on using a given pep8 fixer (eg. autopep8 / yapf / black are what I have used before)  once to fix the repo, and then use set up a flake8/pylint/pep8 checker, people can use their own auto formatting tools (or everyone agrees to use a common tool eg. black) as long as it passes the checks.
