### ISSUE TITLE
bson.Binary is just bytes in python 3

### ISSUE THREAD

**Issue by fersarr** [manahl/arctic#673]
I think that for better python 3 support, these lines in arctic
https://github.com/manahl/arctic/blob/210a7ef95b4c65a2c5cfe771572f7fb8458596a3/arctic/store/_version_store_utils.py#L47

https://github.com/manahl/arctic/blob/210a7ef95b4c65a2c5cfe771572f7fb8458596a3/arctic/chunkstore/chunkstore.py#L125

should return `bytes` in python 3, not `bson.Binary`

Read more here:
http://api.mongodb.com/python/current/python3.html
and here
https://github.com/mongodb/mongo-python-driver/commit/6a11888a9cfccf1f564fa4abfab30e5174f3756f

This previous issue seems related:
https://github.com/manahl/arctic/issues/135

**Comment by bmoscon** [comment]
i think having `Binary(....)` for all versions is much cleaner than anything we'd have to do to support Py2 and Py3 (eg, if statements or exception handling)

**Comment by bmoscon** [comment]
I'm voting we close this since its not really an issue

**Comment by shashank88** [comment]
Sure. Closing it.
