### ISSUE TITLE
More formatting fixes, and adding minimal pep8 checks to ensure it's being followed.

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#674]
#### Description of problem and/or code sample that reproduces the issue

Similar to the #670 more formatting changes (eg. indent issues, more unused stuff) are required for pep8 compliance. Will add some minimal pep8 checking to ensure the checking is integrated in travis

**Comment by yschimke** [comment]
@shashank88 can you remove the boilerplate from the issue you raise?
