### ISSUE TITLE
Update a dataset automatically

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#68]
Hello,

It will be nice if you could show how to update a dataset automatically

For example

Let's say that we have run this in 2015-01-01

```
from arctic import Arctic

# Connect to Local MONGODB
store = Arctic('localhost')

# Create the library - defaults to VersionStore
store.initialize_library('CURRFX')

# Access the library
library = store['CURRFX']

# Load some data - maybe from Quandl
authtoken = "your token here"
eurusd = Quandl.get("CURRFX/EURUSD", authtoken=authtoken, trim_start='20140101', trim_end='20141231')

# Store the data in the library
library.write('EURUSD', eurusd, metadata={'source': 'Quandl'})

# Reading the data
item = library.read('EURUSD')
aapl = item.data
metadata = item.metadata
```

now (2015-12-21) we want to update data (so from 2015-01-01 to today).

So we could query Quandl this way:

    eurusd_new = Quandl.get("CURRFX/EURUSD", authtoken=authtoken, trim_start='20150101')

I don't think that reading previous (stored) dataset (and putting the whole dataset to memory in order to get `Max(Date)` (`eurusd.index.max()` so 2014-12-31) is very efficient.

Moreover we will need to concatenate `eurusd` and `eurusd_new` and write this new concatenate dataset to the library.

I think that we should also store frequency (daily in our case as metadata)

Isn't there any API for this ?

Updating a library automatically and the whole datastore is something to also consider.

Kind regards

**Comment by jamesblackburn** [comment]
> I don't think that reading previous (stored) dataset (and putting the whole dataset to memory in order to get Max(Date) (eurusd.index.max() so 2014-12-31) is very efficient.


There's an `append` call on the VersionStore library, that should do what you want.

Note that for daily data, we find the read-modify-write (which should take `ms`) is so fast in arctic that we just do that.  This has the advantage that any data revisions in the historical data are picked up - the reason why VersionStore is versioned.  For minute bars, we use `append`.

> I think that we should also store frequency (daily in our case as metadata)
> Isn't there any API for this ?

You can stick this on the `metadata` document you pass in on write?

**Comment by femtotrader** [comment]
When you use a `VersionStore` library. How to know max date (and also min date) of stored data ?

I noticed a  `max_date(self, symbol)` method in `TickStore` but nothing similar in https://github.com/manahl/arctic/blob/master/arctic/store/version_store.py

**Comment by femtotrader** [comment]
I also wonder if there is a way to "prepend"

**Comment by jamesblackburn** [comment]
The VersionStore doesn't expose much, nor require much structure on the stored data frames. Though it supports slicing by date range, it doesn't actually require a timestamp index on the stored data.  For additional metadata, we recommend storing that alongside your data in the `metadata=` field, or store it into another Mongo Collection.

How do you see prepend being used?  I would think in the rare case that data changes historically a read-modify-write would be reasonable to do. 

For daily data you should find that reads and writes of all history for a ticker takes a few `ms`.

**Comment by femtotrader** [comment]
Ok I should write to metadata both `min_date` and `max_date` to be able to update correctly. Thanks for your nice support

**Comment by xgdgsc** [comment]
@jamesblackburn I feel read-modify-write would take double space on disk every time. How many versions does arctic keep now? Is there a method that I can update metadata without writing data again?

**Comment by jamesblackburn** [comment]
It depends.  We chunk data by some range (size or date) we checksum the chunks.  For ranges that don't change we reuse the chunks.  If the chunk changes then it is duplicated.  When old versions are deleted the chunks are a garbage collected.
