### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#681]
- [x] Add label on top of README pointing to readthedocs.

- [x] Point wiki to readthedocs and move over remaining documents in wiki to readthedocs.

- [x] Add more documentation on tickstore

- [x] Quickstart section in readthedocs.

- [x] Some FAQs with commonly asked questions.

- [x] Comparision section with real world use cases of VersionStore/TickStore/Chunkstore since this seems to be a pretty common question.

- [x] Thread safety notes in FAQ

- [x] Cleanup current doc on readthedocs

**Comment by femtotrader** [comment]
Maybe you can also add doc link also in Arctic repository description

**Comment by bmoscon** [comment]
I'd also add a checkbox for the API documentation, as this is something we really should do

**Comment by shashank88** [comment]
@bmoscon if you get time, can you add some FAQs based on the most common things people asked with plain text or the issue link if you replied in the Github issue anyways to save pasting?

**Comment by bmoscon** [comment]
@shashank88 can do!

**Comment by shashank88** [comment]
Added all of the above to documentation. This is a never ending process, but I think I am happy for now. Some things I would like to add is a nice diagram for Version/ChunkStore that describes how the chunking / serialization / compression works on a top level.
