### ISSUE TITLE
Negative len from get_info() ChunkStore

### ISSUE THREAD

**Issue by fl4p** [manahl/arctic#686]
#### Arctic Version

```
github
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Ubuntu

#### Description of problem and/or code sample that reproduces the issue

I'm currently using InfluxDB, tried to import some tick data to arctic with this code (df are weekly chunks queried from influx):
```
        if key not in tr_hist.list_symbols():
            tr_hist.write(key, df, chunk_size='7d')
        else:
            tr_hist.update(key, df, chunk_size='7d')
```

For one single I wrote around 220M ticks, but this is what `get_info()` returns:
```
{'chunk_count': 112,
 'len': -439714587,
 'appended_rows': -439914018,
 'metadata': {'columns': ['date', 'amount', 'price']},
 'chunker': 'date',
 'chunk_size': '7d',
 'serializer': 'FrameToArray'}
```

A `read` returns the 220M ticks, so appears to work fine

**Comment by bmoscon** [comment]
its possible that the values there have wrapped, not sure. also not sure if your chunk size is really working or not, due to https://github.com/manahl/arctic/issues/639, which itself is due to a pandas bug

**Comment by f4bsch** [comment]
Has this been fixed?

**Comment by bmoscon** [comment]
there isnt anything to fix - using '7d' isnt a valid chunksize due to pandas #639. I cant reproduce this issue while using valid chunk sizes. this info is also 'best effort' and not guaranteed to be accurate.
