### ISSUE TITLE
Tests and Benchmarks for async arctic

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#687]
Currently, async arctic has a single benchmark and doesn't have any tests at this point. Having more tests will allow us to understand how to use and get some more confidence. More benchmark for different load types (updates / writes / reads) etc. would be a good idea.

**Comment by shashank88** [comment]
@bmoscon did you or @dimosped have a bunch of benchmarking stuff or tests that you guys used locally for testing performance stuff? Was planning on doing some benchmarks with feature flags enabled / disabled for comparison but thought to check if there is something I can use.

Also do you know which frame is the benchmarks/benchmarks.py file using?

**Comment by bmoscon** [comment]
did you see this?

https://github.com/manahl/arctic/blob/master/benchmarks.md

**Comment by shashank88** [comment]
Thanks. Closing this issue as I didn't see https://github.com/manahl/arctic/issues/545
