### ISSUE TITLE
Fix flaky integration test: test_multiprocessing_safety 

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#692]
This test seems to be quite flaky, have seen it fail half the times. Will take a look at it if there is an underlying issue or just the test being flaky.

LOG:

    @pytest.mark.timeout(600)
    def test_multiprocessing_safety(mongo_host, library_name):
        # Create/initialize library at the parent process, then spawn children, and start them aligned in time
        total_processes = 64
        total_writes_per_child = 100
    
        register_get_auth_hook(my_auth_hook)
    
        global MY_ARCTIC
        MY_ARCTIC = Arctic(mongo_host=mongo_host)
    
        MY_ARCTIC.initialize_library(library_name, VERSION_STORE)
        assert isinstance(MY_ARCTIC.get_library(library_name), VersionStore)
    
        processes = [Process(target=f, args=(library_name, total_writes_per_child, True)) for _ in range(total_processes)]
    
        for p in processes:
            p.start()
    
        for p in processes:
>           p.join()

tests/integration/test_arctic_multithreading.py:66: 

self = <multiprocessing.forking.Popen object at 0x7fdc1d3d5350>, flag = 0

    def poll(self, flag=os.WNOHANG):
        if self.returncode is None:
            while True:
                try:
>                   pid, sts = os.waitpid(self.pid, flag)
E                   Failed: Timeout >600s
Failed

**Comment by bmoscon** [comment]
I'm pretty sure its a travis issue. There are other tests that intermittently fail that never fail on local envs

**Comment by shashank88** [comment]
This was also failing on our internal builds so I assumed it's a test issue. You can close it if you think it's the framework runner issue

**Comment by bmoscon** [comment]
I'm not saying don't spend time trying to fix it, but just mentioning that travis having random failures is something thats been happening since we started using travis :)

**Comment by shashank88** [comment]
Ahh cool, will take a look at this then.

**Comment by shashank88** [comment]
Seems to be fine now, will close for now.
