### ISSUE TITLE
TickStore stats() returns negative size

### ISSUE THREAD

**Issue by fl4p** [manahl/arctic#696]
#### Arctic Version

```
# github
```

#### Arctic Store

```
# TickStore
```

#### Platform and version

Ubuntu, Python 3.7, Pandas '0.24.0.dev0+1542.g4bf3a0e11', Arctic '1.74.0'

#### Description of problem and/or code sample that reproduces the issue

`stats()`returns negative size after deleting all symbol data:
```
{'sharding': {'collections': []},
 'dbstats': {'db': 'arctic',
  'collections': 42,
  'views': 0,
  'objects': 87585,
  'avgObjSize': 841203.3159102586,
  'dataSize': 73676792424.0,
  'storageSize': 95022342144.0,
  'numExtents': 0,
  'indexes': 84,
  'indexSize': 9261056.0,
  'fsUsedSize': 383083565056.0,
  'fsTotalSize': 434037628928.0,
  'ok': 1.0},
 'chunks': {'ns': 'arctic.l2_ft2',
  'size': -2673610,
  'count': 0,
  'storageSize': 12926074880.0,
  'capped': False,
  'wiredTiger': {'metadata': {'formatVersion': 1},
```

**Comment by shashank88** [comment]
@fl4p stats() just uses the pymongo command collstats, it seems to be a known issue. See here: https://docs.mongodb.com/manual/reference/command/collStats/#accuracy-after-unexpected-shutdown

Not sure we can do much from the arctic side of things. Let me know if it's ok and I can close this issue.
