### ISSUE TITLE
'python setup.py install' leaves out several subpackages

### ISSUE THREAD

**Issue by bjorskog** [manahl/arctic#7]
Hi. 

Running the current version of setup.py will leave out several of the subpackages, e.g. arctic.store and arctic.tickstore.

Instead of using "packages=['arctic', 'tests']" in setup.py, would it not be better to use "packages=find_packages()"? After applying this change it installs nicely.

I'm on OSX so I don't have a pull that fixes this due to clang and OpenMP lacking compatibility leading to other changes, and thus lots of failing unittests.

**Comment by jamesblackburn** [comment]
Ok, thanks for the heads up. I'll take a look.

Re the OS X issue, OpenMP is only used for parallel lz4 compression (which isn't strictly needed, but useful for large frames).  I filed a bug against home-brew on this not clear whether there's something wrong with my setup or an issue with the brew recipe:
https://github.com/Homebrew/homebrew/issues/40391

**Comment by bjorskog** [comment]
Ok, I'll take a look at OpenMP. My quick goocle search only indicated problems, so I didn't try all that hard..

Nice package though, thanks!
