### ISSUE TITLE
Scripts to archive and unarchive libraries

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#702]
We were discussing having an option in Arctic to archive and unarchive unused libraries. The detection of unused libraries is something that's left upto the user. 
The idea is to have something like:
```arctic.archive_library('test_library', dest='/tmp/mongo_archives/', compress=True, reason="unused for 30 days")```
When someone tries to use the library we can log something like:
This library was archived due to: unused for 30 days. To restore it you can run:
```arctic.restore_from_archive('test_library', src='/tmp/mongo_archives/')```

Some implementation details to mesh out:
a) Only archive the data collection or all collections related to the library. I would prefer archiving all given we should be archiving only in cases where we are sure it's not likely to be used.
b) How to store details of which libraries have been archived, could be a mongo collection with names of libs and some metadata
c) TBD

**Comment by shashank88** [comment]
Yeah, it would be a thin wrapper over mongodump and mongo restore but it would have to store some additional metadata about when something was archived, when was it restored etc.

The soft archive seems nice, can add support for that in the same mongo collection that will store additional metadata.

**Comment by rob256** [comment]
> Yeah, it would be a thin wrapper over mongodump and mongo restore

What I mean, is `archive` sounds like a combination of `mongodump` (we don't necessarily have to use mongodump) and `delete_library`. It would be nice if there was a way to `dump` without deleting the library. That way, we could copy data to disk for testing/backup purposes outside the use case of archiving.

**Comment by shashank88** [comment]
Ahh sure, so you want an separate atomic archive operation. Should be fine. For actually archiving inactive libraries we can use a combination of just archive and delete.

**Comment by yschimke** [comment]
Should we consider options that, move libraries or old versions in VersionStore to filesystem, but are still accessible but slower?  Or is this an entirely separate feature?

cc @willdealtry

**Comment by yschimke** [comment]
Also, is there a form of temporary hiding of libraries until we confirm that the data really isnt needed?  For columns, oracle has a similar feature https://medium.com/@complete_it_pro/what-is-an-invisible-column-in-oracle-and-why-would-you-use-it-90a4c20a8430

**Comment by rob256** [comment]
If you stored metadata (a flag) that a library has been archived, then yes... However, bear in mind that you would require read access to the library's metadata. If you achieve this, then you could filter whilst checking the metadata during [`list_libraries`](https://github.com/manahl/arctic/blob/master/arctic/arctic.py#L200). This isn't super-trivial on an authenticated MongoDB instance.

**Comment by shashank88** [comment]
@rob256 could we not store this info in a common collection that's accessible to all? That collection could have library mode as a field and list_libraries will just use that for operations.

**Comment by shashank88** [comment]
Ended up doing this as a mongo level operation instead. The soft admin is still a valid enhancement, but closing this.
