### ISSUE TITLE
Enable continuous integration with Travis

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#72]
Hello,

it will be nice to enable continuous integration (with Travis)

https://docs.travis-ci.com/user/database-setup/#MongoDB

It will help external contributors to send PRs and see if they can be merged safely.

Kind regards

**Comment by jamesblackburn** [comment]
We have CI running with Circle CI (as linked from the main README):
https://circleci.com/gh/manahl/arctic

We do build incoming pull requests.

Do you see something missing here?

**Comment by femtotrader** [comment]
Sorry...

maybe a badge https://circleci.com/docs/status-badges
