### ISSUE TITLE
Reading a column that does not exist in all chunks fails in CHUNK_STORE

### ISSUE THREAD

**Issue by alberto-exabel** [manahl/arctic#722]
#### Arctic Version

```
1.74.0
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Ubuntu 18.04.1 LTS

#### Description of problem and/or code sample that reproduces the issue

When data frames with several columns are stored in symbols in ChunkStore, reading a time series of a selection of columns with the `columns` parameter will give an error if one of the columns does not exist in one of the chunks.
It would be nice to have this error caught automatically and to have NA values imputed in the missing columns, so that the user does not need to look for all columns that exist in each chunk first, then read the data differently for different chunks and finally append the results imputing NA on the missing columns in some chunks.

Example code:

```
import pandas as pd
from arctic import Arctic, CHUNK_STORE
from arctic.date import DateRange
Arctic('localhost').initialize_library(
    'test_library',
    lib_type=CHUNK_STORE
    )
df = pd.DataFrame(
    {'column_A': [1, 2, 3], 'column_B': [1,2,3]},
    index=pd.DatetimeIndex(
        pd.date_range('2019-01-01', periods=3, freq='D'),
        name='date'
        )
    )
Arctic('localhost')['test_library'].write(
    'test_symbol',
    df,
    chunk_size='D'
    )
df = pd.DataFrame(
    {'column_A': [4, 5, 6]},
    index=pd.DatetimeIndex(
        pd.date_range('2019-01-04', periods=3, freq='D'),
        name='date'
        )
    )
Arctic('localhost')['test_library'].update(
    'test_symbol',
    df,
    chunk_size='D',
    chunk_range=DateRange('2019-01-04', '2019-01-07')
    )
# this will work:
Arctic('localhost')['test_library'].read('test_symbol')
# this will work:
Arctic('localhost')['test_library'].read(
    'test_symbol',
    columns=['column_B'],
    chunk_range=DateRange('2019-01-01', '2019-01-03')
    )
# this will fail:
Arctic('localhost')['test_library'].read(
    'test_symbol',
    columns=['column_B']
    )
Arctic('localhost').delete_library('test_library')
```

**Comment by bmoscon** [comment]
I believe this used to work as you expect it to. I believe it relied on a behavior in pandas that likely has changed. I should be able to fix this pretty easily and quickly
