### ISSUE TITLE
Backwards incompatibility with pandas < 0.23

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#725]
With https://github.com/manahl/arctic/pull/724 it uses features that are not in pandas <0.23 which would cause builds to fail or people using older versions of pandas to fail without warning. 

@bmoscon we hit this as sort parameter is not compatible with pandas 0.22 which we use internally.

**Comment by bmoscon** [comment]
i'll get a travis config file running that will run pandas on 0.22.0 on a specific build so these things will be more obvious at commit time

**Comment by bmoscon** [comment]
sounds like i should add a partial or something to bind the kwarg if the pandas version is > 0.24 otherwise leave it as is

**Comment by shashank88** [comment]
sort was added as a possible param in 0.23.0 I think, so yeah a partial should work for +0.23.0 pandas.

**Comment by shashank88** [comment]
https://github.com/manahl/arctic/pull/729 fixes this
