### ISSUE TITLE
Code quality metrics: add codify / landscape to project

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#73]
Hello,

it will be nice to enable Landscape https://landscape.io/
It can help to track many bugs (even before you noticed them)

For example 
this https://github.com/manahl/arctic/issues/49 
https://github.com/manahl/arctic/blob/master/arctic/tickstore/tickstore.py#L106
should be found easily by Landscape

Codacy https://www.codacy.com/ might also be something to consider

Coveralls provide code coverage https://coveralls.io/
and is also something that should be considered

Landscape and Codacy are very easy to use as they are services.
Coveralls is a little bit harder to setup... but nothing impossible.

It can be also interesting to test code quality locally...

so it may be worth to also set tox https://testrun.org/tox/latest/
flake8 https://flake8.readthedocs.org/ ...
(other tools are pylint http://www.pylint.org/ pychecker http://pychecker.sourceforge.net/
pyflaskes https://launchpad.net/pyflakes/
flake8 https://flake8.readthedocs.org/
pep8 http://pep8.readthedocs.org/
mccabe http://www.mccabe.com/
) but flake8 is a wrapper around PyFlakes, pep8, Ned Batchelder’s McCabe script
so it may be enough

You can find interesting project templates with these tools enabled 
https://github.com/audreyr/cookiecutter-pypackage

We use Travis, Landscape, Coveralls in 
https://github.com/pydata/pandas-datareader

So a first step could be to enable Landscape as it's easy and can help a lot.

Kind regards

**Comment by jamesblackburn** [comment]
We've currently use Coveralls (as linked from the main README):
https://coveralls.io/github/manahl/arctic?branch=master

Agree there are a bunch of other services we could use too.

**Comment by femtotrader** [comment]
Yes sorry about Coveralls...

but Landscape worth to be enabled

**Comment by bmoscon** [comment]
@jamesblackburn landscape doesnt seem to work anymore. I can't get anything to build for arctic and I've found several blog posts from the creator basically saying hes taking a hiatus from landscape, etc. We can try a different one like CodeClimate. I'd add it myself (its free) but I'm not an owner so you'd have to do it

**Comment by bmoscon** [comment]
added landscape
