### ISSUE TITLE
Github First Release Process

### ISSUE THREAD

**Issue by yschimke** [manahl/arctic#731]
I think we should make the release process, github first.  Floating the idea, but already our internal releases can involve a new releaes being cut that we can't adopt immediately if it breaks something and we currently have a 700 line script internally we could kill off.

Thoughts? 

cc @shashank88 @jamesblackburn @bmoscon

**Comment by bmoscon** [comment]
I'm fine with that. I do remember the arctic deploy script being a pain  to work with. Doing it manually is not too difficult

**Comment by shashank88** [comment]
We discussed this internally, and we will move to a Github first release, and then bring it in internally after testing with our wrapper.

**Comment by bmoscon** [comment]
so is there anything here to "do" ? Releasing externally first is easy, build wheel/egg/etc, create release on github and upload, then deploy to pypi, then bump version number in setup.py

**Comment by shashank88** [comment]
I will have to update some internal docs, delete some release scripts, get pypi credentials and document the process in the wiki. Am working on the py2->3 issue, once I have a fix I can try and follow this process and close this issue after it's done?

**Comment by shashank88** [comment]
Did all the above things. Closing this
