### ISSUE TITLE
 out-of-order in tickStore

### ISSUE THREAD

**Issue by DennyZen** [manahl/arctic#732]
i am using  Arctic ver 1.73.0
TickStore on Windows Server 2016 

saving orderbook ticks stream to db..
quite big flow(20-50 ticks/sec)..
before it was good. but i add threading.Timer function that produce one additional tick every 1 second
I got "UnorderedDataException timestamps out-of-order " after some hours now.
i use array for buffering ticks. during adding this array to db - error occurs 
```
> msg['index'] = datetime.now()
> self.data.append(msg)
> if len(self.data)==100000:
>     self.lib.write(self.sym, self.data)
```
my theory is: when we got new tick, formed new message, added time to it, but still not append to array - if in this moment another process(Timer) runs - maybe we'll have this kind of error.. 
(delay in out of order tick is very small - ~10ms)
What you think?
Any suggestions?

**Comment by DennyZen** [comment]
already fixed it!
i put my additional ticks to another collection. Easy

**Comment by bmoscon** [comment]
so we can close this?
