### ISSUE TITLE
Correct way to use VersionStore? 

### ISSUE THREAD

**Issue by FilipJanitor** [manahl/arctic#733]
I have read the available documentation (even watched the presentations) and skimmed through the code but I am still not sure if I understand how to achieve semantics of patching timeseries data in VersionStore.

Let's say that I store large timeseries under one symbol - it has a large number of datapoints indexed by their datetime info, possibly from many years. I understand, that in the background, data is split to chunks/segments by the datetime and associated with one version. Now I want to replace certain existing datapoints with their corrections - lets say I want to patch datapoint with timestamp `j`.

Illustration:
```
original timeseries           patch                            data with applied patch
date           data           date         data                date           data
2016-01-01      1             2016-01-02    42                 2016-01-01      1
2016-01-02      2                                              2016-01-02      42
2016-01-03      3                                              2016-01-03      3
...                                                            ...
```

Now if I used `write` the new version would contain only the patch, unless I inserted the whole patched dataset again which I want to avoid as the dataset is too large and I don't want to transmit and store duplicates. Of course, I want to retain the data before correction as a previous version. How to accomplish such write? What would happen internally if I used `append` with `prune_previous_version=False` to write the patch? Is such operation even legal? (the name `append` is confusing me a bit in this case as I am not appending new data).

Let's say I used some correct method of writing and now I want to read the patched data. Given the interval `<j-5,j+5)` how can I read original data with all applied patches from this interval? The `from_version` parameter in `read` seems promising, but does it actually apply all the patches?  In case of many subsequent patches, are all of them read and aggregated in memory or is there some trick that minimizes read amplification by avoiding reading a large number of small documents containing unneeded patches?

I am sorry for such a battery of questions but I am sure most of these things are trivial with enough knowledge of Arctic internals.

Thanks for help!

**Comment by gabriel-b2c2** [comment]
did anyone reply to this? I have the identical question.

thanks

**Comment by bmoscon** [comment]
version store isnt designed for the operation you describe. You'd need to rewrite the entire timeseries. As you have noted, version store really supports write and append. write will overwrite any existing data, and append will append new data.

**Comment by gabriel-b2c2** [comment]
ok thanks. So, amongst the other classes, e.g. ChunkStore, TickStore, is it possible to append data to an existing dataset, such that duplication is taken care of automatically?

Right now, using VersionStore, I've written a little routine to append a dataframe to an existing one, remove duplicates and then write back in a single dataframe. So two writes every time I get some new data. This not a problem for EOD data, but is more of a problem if one starts to look at intraday data.

Historically I have used Pandas and HDF5 files. I'm keen to look at Arctic, but evidently the way duplicates are handled could be better.

**Comment by shashank88** [comment]
> Right now, using VersionStore, I've written a little routine to append a dataframe to an existing one, remove duplicates and then write back in a single dataframe. So two writes every time I get some new data. This not a problem for EOD data, but is more of a problem if one starts to look at intraday data.

I am not sure I understand your use-case in this line here: "append a dataframe to an existing one, remove duplicates and then write back in a single dataframe" ..

**Comment by gabriel-b2c2** [comment]
It's inefficient to download data that you have downloaded already.
In effect, this is what you have to do if you use VersionStore.
In contrast, if a Pandas DataFrame is stored in an HDF5 file, a paradigm where you download data once, and keep appending new data to that existing DataFrame, is supported.

**Comment by bmoscon** [comment]
Version store is append only like you want but it won’t handle duplicate data. The operation you describe is not or shouldn’t not be a common one when working with time series data. You get data with a time stamp and you write it. If you need deduplication or some other aggregation I suggest doing that preprocessing before writing the data to arctic
