### ISSUE TITLE
dict saved using arctic in python 2.7 read as uninterpretable bytes in python 3.7

### ISSUE THREAD

**Issue by seandickert** [manahl/arctic#736]
Not sure how to get the version # for arctic. I can add if there's a way to find it.

But, when upgrading from python 2.7->3.7, a dict that was saved in a version store in a python 2.7 environment is returned as an uninterpretable byte stream when reading in python 3.7.

Generally, are there any good docs for moving objects between python 2.7 -> 3.x? The object types could vary greatly e.g. dict, DataFrame, lists, etc as I've used Arctic as a general dict-type key-value store.

**Comment by shashank88** [comment]
I think @bmoscon was using 3.7 with arctic, not sure if he ran into this. Can take a look at this.

**Comment by bmoscon** [comment]
seems like it might be the same as, or similar to, this issue: https://github.com/manahl/arctic/issues/598

**Comment by seandickert** [comment]
@bmoscon @shashank88 thanks for the help. Ended up figuring it out. It was an issue on my end. Apparently, storing a pickled object no longer requires wrapping it in a bson object.

However, I still have issues loading dataframes that were stored in a python 2.7 environment, but are being read in a python 3.7 environment. Specifically, frames with strings result in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 1: ordinal not in range(128)` errors.

Is there any documentation/guidance on loading dataframes in 3.7 that were stored in 2.7? It looks like you can get around these specific issues by passing the encoding to pickle.load, but that's within the arctic code itself.

**Comment by shashank88** [comment]
Marking dup of https://github.com/manahl/arctic/issues/598
