### ISSUE TITLE
Too many retries insert_many error in TickStore

### ISSUE THREAD

**Issue by rtadewald** [manahl/arctic#737]
#### Arctic Version

```
# 1.74.0
```

#### Arctic Store

```
# TickStore
```

#### Platform and version

Ubuntu 16.04

#### Description of problem and/or code sample that reproduces the issue

I'm been trying to add a big pandas Dataframe to a Tickstore, but i'm getting the following error: 
`Too many retries insert_many [BSONObj size: 36244601 (0x2290C79) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5c93c8e6915c9c583ebbbf94')], raising`

It's a 105658 x 4092 sized df. Using ChunkStore or VersionStore, i don't get the following error, but i'm using Tickstore because of its **column** parameter in the read() method.

**Comment by shashank88** [comment]
@rtadewald will take a look

**Comment by shashank88** [comment]
On a quick glance, my guess would be that the default chunk size, which is 10k, makes your data > 16M which is the maximum document size mongo supports. Can you paste the code segment with issues? Can you try with a smaller chunk size to debug this? Say something like:
`
In [7]: a.initialize_library('tick', 'TickStoreV3')                                                                                                                                                                                       

In [8]: t = a['tick']                                                                                                                                                                                                                     

In [9]: t                                                                                                                                                                                                                                 
Out[9]: 
<TickStore at 0x11b8e2a20>
    <ArcticLibrary at 0x11c0f1f60, arctic.tick>
        <Arctic at 0x11b977588, connected to MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, maxpoolsize=4, sockettimeoutms=600000, connecttimeoutms=2000, serverselectiontimeoutms=30000)>

In [11]: t._chunk_size                                                                                                                                                                                                                    
Out[11]: 100000

In [12]: t._chunk_size = 500   
`
I haven't used tickstore that much, but @jamesblackburn or @reasto might know more?

**Comment by reasto** [comment]
Our dataframes have around 300 columns and most of our data is sparse with perhaps 10 non null values per row so we often use between 10000 and 100,000 rows in a document. You will have to tune yours accordingly.
