### ISSUE TITLE
Binary save from java and fast load in Python

### ISSUE THREAD

**Issue by hlbkin** [manahl/arctic#739]
Hi Team!

I wonder, whether the following pipeline is possible using arctic db:

1) Iterate over ticks (from Cassandra) using already heavy optimized Java code
2) Save vectorized feature on each sampling point to arctic in bulk (for example blobs by date/hour)
3) Load directly daily/hourly blolb into numpy array in Python

Thanks

**Comment by shashank88** [comment]
Hi @hlbkin this would require a Java arctic implementation to write to mongo which @yschimke was looking at iirc. Just curious, why not iterate over cassandra with python and use the python arctic? Does it fall behind due to the write rate?

**Comment by shashank88** [comment]
Closing this, please reopen if this does not answer your question.
