### ISSUE TITLE
TickStore .read() without a date range only returns first 100k entries

### ISSUE THREAD

**Issue by jnd940** [manahl/arctic#742]
#### Arctic Version

```
1.68.0
```

#### Arctic Store

```
TickStore
```

#### Platform and version

Pandas 0.22.0
Numpy 1.15.4

#### Description of problem and/or code sample that reproduces the issue

If one has a time series with more than 100k rows (e.g. a few years of one minute level market data) stored in TickStore, then the read function only returns the first 100k rows, when no date range is given, e.g. ts.read('IBM').

When any sufficiently wide date range is given (e.g. ts.read('IBM', string_to_daterange('1970-2030'), the entire entry is returned correctly.

VersionStore and ChunkStore do not have this issues, they always return the full entry.

**Comment by jnd940** [comment]
Here's a short example code to illustrate the issue:

`import pandas as pd`
`from arctic import Arctic, TICK_STORE`
`from arctic.date import string_to_daterange`

`dr = string_to_daterange('20180101-20190101')`
`dts = pd.date_range(start=dr.start, end=dr.end, freq='min')`
`df_in = pd.DataFrame({'random_values':np.random.random(len(dts))}, index=dts)`
`df_in.index = pd.to_datetime(df_in.index).tz_localize("UCT")`
`arc.initialize_library('test_lib', lib_type=TICK_STORE)`
`arc['test_lib'].write('long_series', df_in)`
`df_out1 = arc['test_lib'].read('long_series')`
`df_out2 = arc['test_lib'].read('long_series', string_to_daterange('2000-2030'))`

df_out1 will only contain the first 100'000 rows, while df_out2 contains all 525'601 rows.

**Comment by shashank88** [comment]
@jnd940 from a quick glance at the [code](https://github.com/manahl/arctic/blob/master/arctic/tickstore/tickstore.py#L233) and from what I understand, tick_store is not meant to be used in an unbounded way as you almost never want every single tick in the collection. When you manually put a time range you are basically overriding the protection the check I linked above gives you.

It returns 100k as that's the default chunk-size i.e ticks per mongo document (which you can set) when you initialize tick_store, and the find_one will just return one doc hence the number.

**Comment by shashank88** [comment]
Let me know if this answers your query and I will close this issue

**Comment by shashank88** [comment]
Yeah, I keep meaning to write documentation about it but haven't found the time yet. If you have used Tickstore it would be quite useful if you could send a PR with some simple documentation here: https://github.com/manahl/arctic/blob/master/docs/tickstore.md
