### ISSUE TITLE
One library with many symbols or several libraries with few symbols?

### ISSUE THREAD

**Issue by luisbaia** [manahl/arctic#748]
Hello,

Currently I am using a single library with 12 symbols (the structure of the data is exactly the same per symbol). This library alone in a couple of weeks already gathered 40GB stored.
I need to increase even more these the number of tables I am storing.

My question is scaling wise: Should I create a library with one symbol each or can I keep using the same library and eventually have something as 20+ symbols and a total of 500GB under this library.

**Comment by shashank88** [comment]
One library with many symbols make more sense. We currently have multiple 500g+ libraries with tons of symbols. There is already an index on symbols (for VersionStore) so you won't gain much performance-wise by having multiple libraries.

**Comment by luisbaia** [comment]
Thank you for the quick answer and the great work. It has been working like a charm.

**Comment by shashank88** [comment]
Np 👍 Glad it worked
