### ISSUE TITLE
What's new file

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#75]
Hello,

it will be nice to add a  What's new file in doc directory

see an example
https://github.com/xray/xray/blob/master/doc/whats-new.rst
or a more complex approach (one file per version) here : https://github.com/pydata/pandas-datareader/tree/master/docs/source/

So building doc will also display release notes

I noticed https://github.com/manahl/arctic/blob/master/CHANGES.md
but the idea is to have this in `docs` directory like other pandas related projects

Kind regards

**Comment by bmoscon** [comment]
Isn't that what is in the Changes.md file?

**Comment by femtotrader** [comment]
Sorry editing... I noticed (lately) https://github.com/manahl/arctic/blob/master/CHANGES.md
but the idea is to have this in docs directory like other pandas related projects

**Comment by femtotrader** [comment]
If doc is build using Read The Docs (like many other Python projects) changelog will appears in doc too

**Comment by jamesblackburn** [comment]
We have the Changes.md file.  Publishing the docs needs to be done as part of #3
