### ISSUE TITLE
Int columns converted to floats on read.

### ISSUE THREAD

**Issue by RayVR** [manahl/arctic#768]
#### Arctic Version

```
All
```

#### Arctic Store

```
TickStore
```

#### Platform and version

All

#### Description of problem and/or code sample that reproduces the issue
See https://github.com/manahl/arctic/issues/391

This issue still exists and I confirmed it is arctic converting int columns to floats. As stated in the closed issue, I don’t think this makes sense since a dataframe column with dtype int could not have contained NaNs when it was persisted so loading as an int column should be safe. If the concern is an update that contained NaNs with a float dtype then insertion logic should validate the dtype of the columns did not change.

**Comment by shashank88** [comment]
I guess this was added before the pandas change that you can't have NaNs in an int column. I can check with @reasto and get back to you on this.

**Comment by MichaelWS** [comment]
I don't think you could ever have ints in NaN columns it would cast those to an object

**Comment by bmoscon** [comment]
I'm thinking that until we support pandas > 0.24.0 this wont be something we'll change
