### ISSUE TITLE
Authenticate using X509 certificates

### ISSUE THREAD

**Issue by MichaelWS** [manahl/arctic#775]
I would like to authenticate using X509 certificates is there an easy approach to this.
 I would like to write a custom authenticate here:
https://github.com/manahl/arctic/blob/master/arctic/arctic.py#L157

**Comment by MichaelWS** [comment]
Obviously we can authenticate with MongoClient but I am a bit confused how to handle a disconnect or timeout.

**Comment by shashank88** [comment]
We have a @mongo_retry decorator to retry failed operations if that's what you meant? There is also a reauth function in arctic that you can use for disconnects.

**Comment by MichaelWS** [comment]
I am a bit confused how  to handle the authenticate function.  Wouldn't that be called regularly?  (Obviously wouldn't have username & password to use over it)

**Comment by shashank88** [comment]
It's available to use as a hook that you can provide a callable for. For example, we use it internally with a wrapper and provide a function for the hook that does the auth. Someone posted a simple example in another issue:
https://github.com/manahl/arctic/issues/327#issuecomment-281253119

```from arctic.auth import Credential
from arctic.hooks import register_get_auth_hook

def arctic_auth_hook(mongo_host, app, database):
    return Credential(
	database="arctic",
	user="username",
	password="password",
    )


def main():
    register_get_auth_hook(arctic_auth_hook)
    store = arctic.Arctic(host, app_name)
    # ...
    

if __name__ == '__main__':
    main()```
