### ISSUE TITLE
Pickle PY3/PY2 compatibility

### ISSUE THREAD

**Issue by fersarr** [manahl/arctic#783]
I am not entirely sure of the use case of this line in particular, but if you need to have cross-python compatibility for writing/reading pickles, then you should consider dropping `HIGHEST_PROTOCOL` in the following line:
https://github.com/manahl/arctic/blob/4d04943c72caf2ad99c8b5e90e2002e234013853/arctic/store/_pickle_store.py#L92

You could also have a parameter to change that if needed or default to `HIGHEST_PROTOCOL` otherwise.

As explained in https://docs.python.org/3/library/pickle.html#pickle.dump, for py2-py3 compat you could use `protocol=2, fix_imports=True`

Using `HIGHEST_PROTOCOL` in Python 3 (as of version 3.6.5) will give you `4` and Python 2 will not be able to read it. PY2 has protocols 0-2 (inclusive)

**Comment by shashank88** [comment]
That's a good point. We could handle this in these ways as discussed:
a) Add an optional argument in write to give the pickle protocol and  pass a python2 supported pickle protocol if this use case is needed
b) Hardcode Arctic to use a lower protocol number
c) Patch Arctic internally to use a lower protocol at all times.

Will discuss with a few people and get back on this.

**Comment by shashank88** [comment]
Decided to go with c) and patch arctic internally. Closing this here.

**Comment by yschimke** [comment]
@shashank88 Can you post the patch here as well, might be useful for others externally if they hit similar issues?
