### ISSUE TITLE
Issue with numpy:int64 in py2 vs py3

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#785]
Maxim Podkolzine ran into an issue numpy int64 not being bson encodable probably because in py3 it's not an instance of int.
Pasting some excerpts from the chat:
```
lib = get_mongoose_lib('mpodkolzine.blah')
lib.insert_many([{'count': np.sum([1,2,3])}])
```
```
bson.errors.InvalidDocument: Cannot encode object: 2171453
where 2171453 is mentioned in the query to a BSON library```
```
```I've added an explicit conversion to int that works for me, but I strongly feel it should be fixed on the lowest level, because it's incredibly easy to get a wrong int in py3```

**Comment by maxim5** [comment]
@shashank88 any luck with this?

**Comment by shashank88** [comment]
Another team ran into a similar issue but in another part of the code base. I haven't thought about the best way to fix this, as it's doesn't just happen in one place and the user can accidentally insert int64 which is not bson serializable, will let you know if I decide something on this

**Comment by shashank88** [comment]
@maxim5 I was thinking about this and I think we shouldn't silently convert the int64 to int for BsonStore as this is meant to be a very thin layer over Mongo operations and if Mongo doesn't support it we should be handling it on the user side. Can discuss in person if you want, closing this for now.
