### ISSUE TITLE
write tick store creates new object in mongo.

### ISSUE THREAD

**Issue by mschatzow** [manahl/arctic#787]
We are storing eod stock data in arctic tickstores.  However, whenever we update one day, it creates a new mongo Object in the collection with the chunk size of a day.  Is there a way to append to a previous object in order to have faster reads?

our calls are `self.store.write(key, frame)`

**Comment by jamesblackburn** [comment]
TickStore is best with large amounts of high frequency data (hundreds of updates per second). For minute or daily data I'd recommend using VersionStore which supports the append behaviour you're looking for.

James

**Comment by mschatzow** [comment]
Thanks James.
