### ISSUE TITLE
FAST_CHECK_DF_SERIALIZABLE does not check if it is 1

### ISSUE THREAD

**Issue by mschatzow** [manahl/arctic#788]
on line 34 here https://github.com/manahl/arctic/blob/master/arctic/_config.py#L34,
This check should be (os.environ.get('FAST_CHECK_DF_SERIALIZABLE') == "1"

because bool("0") evaluates to True

**Comment by shashank88** [comment]
This generally means it assumes the presence of this var in env as a truth type irrespective of the value, and the same notation is used for all env variables

**Comment by mschatzow** [comment]
Is there a reason why environment variables are used for this?

**Comment by shashank88** [comment]
@mschatzow It's generally used as it makes it easy to turn a new feature or a specific kind off bug (eg. pickling related) for a user's build pipeline and in general. Once the feature is better battle-tested we can change the default.

**Comment by shashank88** [comment]
Eg. Some teams here set the Pickle related flag here to force bytes to unicode so their py3 tests pass fine and it only needs to be set once at the beginning of the Jenkins pipeline.
