### ISSUE TITLE
Accessing keep_mins kwarg in _prune_previous_versions

### ISSUE THREAD

**Issue by mschrem** [manahl/arctic#789]
Hello, 
I was wondering how the user can set the keep_mins kwarg when removing older versions. Thank you. 

https://github.com/manahl/arctic/blob/722316c0f9fa7d1d7b757483b8573b57169d97ca/arctic/store/version_store.py#L858

**Comment by shashank88** [comment]
Have not used this before, but the description seems to be self-explanatory? 
`delete versions other than a version that's at least keep_mins minutes old.`

**Comment by mschrem** [comment]
Thank you for getting back to me. _prine_previous_versions is a private member and the keep mins kwarg does not get passed in from public append and write functions. I was wondering if there was a particular reason for this and if not can it be more accessible? Thank you.

**Comment by shashank88** [comment]
Fair point. I am not aware of any specific reason for not having this passed down as a **kwarg or something.  For now, I guess you can use the private method _find_prunable_versions and pass the remaining versions to prune, not very pretty though. Will try and add it this week.

**Comment by mschrem** [comment]
Ok great. Thank you.

**Comment by shashank88** [comment]
@mschrem Have merged the fix, you should be able to pass this in kwargs

**Comment by mschrem** [comment]
Great. Thank you
