### ISSUE TITLE
arctic.exceptions.QuotaExceededException

### ISSUE THREAD

**Issue by sunjun81** [manahl/arctic#79]
hey guys, i got this exception, does anyone knows why? Thanks in advance!

arctic.exceptions.QuotaExceededException: Quota Exceeded: 32.972 / 10 GB used

**Comment by bmoscon** [comment]
You can control how much data arctic stores in the DB. You need to increase the limit.

**Comment by sunjun81** [comment]
thanks a lot

**Comment by TheTradingWarrior** [comment]
Sorry for bringing this up again , but how can I increase the limit?

**Comment by bmoscon** [comment]
library.set_quota(quota)
it takes a quota in bytes
