### ISSUE TITLE
Memory Issues when append in chunkstore

### ISSUE THREAD

**Issue by PalakMunet** [manahl/arctic#798]
#### Arctic Version

```
# 1.79.2
```

#### Arctic Store

```
#  ChunkStore
```

#### Platform and version

Red Hat Enterprise Linux Server release 7.4 (Maipo), 64-bit

#### Description of problem and/or code sample that reproduces the issue

Hi, I am trying to create symbols in chunk store and append data to them, but what I have realized is the memory keeps on increasing while append operation.
Does ChunkStore load data from disk in memory before appending?
If so is there any alternative possible(any api or anything else) to make it less memory-intensive.

**Comment by bmoscon** [comment]
@PalakMunet chunk size matters when writing to chunkstore. If your chunk size is monthly, and you write data every second, its going to be very inefficient and it will read out the data to append to it. you also want to have a chunk size large enough to make use of the compression and other features of arctic (minute chunks might not be a good idea if one minute of data is only a few hundred or thousand rows)

**Comment by bmoscon** [comment]
see https://github.com/manahl/arctic/blob/master/docs/chunkstore.md
