### ISSUE TITLE
Revert incomplete features eg. Forward pointers

### ISSUE THREAD

**Issue by shashank88** [manahl/arctic#799]
Forward pointers are not finished and usage can trigger data corruption in certain cases. This issue is to revert this feature.

**Comment by shashank88** [comment]
Have made a couple of attempts to revert it but there have been plenty of changes after it which makes the revert non trivial given the number of merge conflicts .. Will give it another shot later

**Comment by yschimke** [comment]
Maybe start with just disabling anyway to activate it?

**Comment by shashank88** [comment]
I was considering just hardcoding the config to disable it and not read the env at all, is that what you meant?

**Comment by shashank88** [comment]
Closing this for now, as I have disabled the flag which can enable this. Will revert the code either in bits or later
