### ISSUE TITLE
Store xray.Dataset

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#80]
Hello,

Pandas maintainers are considering deprecating `Panel` in favor of xray `Dataset`.
http://xray.readthedocs.org/

https://github.com/pydata/pandas/issues/8906#issuecomment-167944787
https://gitter.im/pydata/pandas see discussion 2015-12-30

Adding `xray.Dataset`, `DataArray` support to Arctic is probably something to consider in the medium or long term.

Kind regards

**Comment by shashank88** [comment]
Closing this. Please reopen if still relevant.
