### ISSUE TITLE
Inserting into Arctic datastore using multiple python processes.

### ISSUE THREAD

**Issue by rajnish2704** [manahl/arctic#812]
#### Arctic Version
1.79.2
```
# Arctic version here
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Ubuntu 17.10
Python 2.7.14

#### Description of problem and/or code sample that reproduces the issue
If a pool of processes, using the Python multiprocessing module is created, and these processes are used to insert data to Arctic's chunk store; will the data be inserted concurrently or would it be inserted serially?

**Comment by shashank88** [comment]
It will be inserted concurrently but I am not 100% sure if Chunkstore is fork safe ... @bmoscon might know more. I guess if you are writing to different keys in each process, it should be fine?

**Comment by bmoscon** [comment]
As long as each process is writing or modifying unique symbols there is no issue here

**Comment by rajnish2704** [comment]
Where can I find the write benchmarks of Arctic? As to how much data can be inserted to an Arctic datastore per second given some hardware configuration?

**Comment by rajnish2704** [comment]
Since we are using Arctic to insert symbols which are independent, and we are achieving peak insertion rates of 2.5 MBps, are there some optimisations that we can do to achieve higher rates?

**Comment by bmoscon** [comment]
you'd have to do your own benchmarks, there arent any I'm aware of, and any that were done were done years ago. The amount of data that can be inserted will depend on your network, disk speeds, cluster config, replication settings, etc.
