### ISSUE TITLE
append not working as expected

### ISSUE THREAD

**Issue by b3yang** [manahl/arctic#86]
I have a dataframe stored in mongodb using arctic and I would like to append to the existing dataframe, e.g. updating daily prices.
I've tried using version storage and the append() function, however it gives me not implemented for handler error

" File "C:\Anaconda\lib\site-packages\arctic\store\version_store.py", line 496, in append
    raise Exception("Append not implemented for handler %s" % handler)
Exception: Append not implemented for handler <arctic.store._pickle_store.PickleStore object at 0x09274AB0>"

've tried register_library_type('dataframestore', PandasDataFrameStore) but received some other error.

Do you have an example of how to update existing dataframe/series data or is there a rule of thumb?

**Comment by bmoscon** [comment]
you don't need to register the storage types. That happens in https://github.com/manahl/arctic/blob/master/arctic/__init__.py

I'd probably need to see some more code to figure out whats going on, but it looks like you are calling append with something that is not supported. Appending with a numpy array or a dataframe will work, but anything else will default to a pickleStore, which does not support append. Did you get any other logs? Sometimes you'll see something like "cannot convert to dataframe, storing as blob" which means its pickling it.

**Comment by b3yang** [comment]
thank you for the quick response, think some dataframe column types are objects and hence it's stored as Blob, guess I can convert the column types before storing.
One more question (let me know if you want me to start a new thread), is it possible for me to search for symbols based on meta data? (i.e. if i have metadata = {'provider':'quandl'}, can i search for all symbols that are quandl symbols) Or would you recommend just creating a new library.

**Comment by bmoscon** [comment]
I don't know of any way to do that. You should probably just make that part of the name/symbol of the data being written, that way when you get the list of symbols, you can filter by that, something like:

```
quandl_symbols = [ x for x in lib.list_symbols() if 'provider:quandl' in x]
```

**Comment by jamesblackburn** [comment]
@b3yang if you do
`lib.list_symbols(provider=quandl)`

You should get a list of all symbols matching that key.  Note that this will do a full collection scan of the version metadata collection.  This can be mitigated by indexing that field, something like:
`lib._versions.create_index('metadata.provider')` 
should help with this.

We find ourselves creating libraries based on symbol similarity for consumers of the data.  There're no hard and fast rules on when a new library is appropriate vs. sharing an existing library.

**Comment by jamesblackburn** [comment]
@b3yang as @bmoscon says, sounds like you're storing objects, and I don't think there's anything easy we can do here to make append work with these, unless we can make the existing pandas store support DFs with object dtype columns.

I'm closing this for now as it sounds like you can store your DFs using primitive dtypes.

**Comment by b3yang** [comment]
makes alot of sense, thanks alot guys
