### ISSUE TITLE
chunk slice read from version_store

### ISSUE THREAD

**Issue by b3yang** [manahl/arctic#88]
not sure if this is right place, but do have question on using library.read function.
Say if i have a symbol called AA which is pandas dataframe that looks like the following:

        open_ps  high_ps  close_ps
date                                  
1994-05-16    21459      NaN     21459
1994-05-17    21402      NaN     21402
1994-05-18    21296      NaN     21296

and it's being stored in version_store (not as blob), is it possible for me query based on a start date and end date? think @jamesblackburn had a slide on chunking on tick data store, but not sure how this is being done on version store.
workaround is obviously load whole dataframe in memory and filter after, not sure how much of a performance impact this will have.
cheers
B.

**Comment by richardbounds** [comment]
library.read(symbol, date_range) should work, e.g.:
https://github.com/manahl/arctic/blob/master/tests/integration/store/test_pandas_store.py#L652

**Comment by b3yang** [comment]
perfect, thanks!
