### ISSUE TITLE
Does arctic support query? I want to fetch data of some stock between a start time and a end time.

### ISSUE THREAD

**Issue by huaiweicheng** [manahl/arctic#96]
New to arctic. 
I want to do some backtests in a specific time range. So I have to fetch data between a start time and a end time.
Many thanks.

**Comment by AdrianTeng** [comment]
Yes -- assuming you are using `VersionStore`, you can specify `date_range`. See `VersionStore.read` [docstring|https://github.com/manahl/arctic/blob/master/arctic/store/version_store.py#L305-L307]

**Comment by huaiweicheng** [comment]
Thanks. I tried the method. However, the result does not work well.
Something wrong?
![image](https://cloud.githubusercontent.com/assets/4011117/12666051/d5b5384e-c677-11e5-8495-8c9219599ef8.png)
![image](https://cloud.githubusercontent.com/assets/4011117/12666055/dd5ccd6e-c677-11e5-95c1-6c62278c67df.png)

**Comment by jamesblackburn** [comment]
The parameter is `date_range` not `daterange`

**Comment by huaiweicheng** [comment]
@jamesblackburn 
Thanks.
My mistake, so stupid... 
Another issue is that I just wonder why VersionStore does not support columns parameter similar to TickStore.

**Comment by jamesblackburn** [comment]
When we were benchmarking implementations initially the fastest way to read and write the chunks was as a single item without splitting out the columns. 

We also often want most the columns, so it seemed reasonable to leave it to the client.

**Comment by huaiweicheng** [comment]
Thanks a lot. You guys did a fabulous job.
